### ISSUE TITLE
Bot keeps rolling no matter what

### ISSUE THREAD

**Issue by Jeez1221** [vivinano/MudaeAutoBot#102]
The bot keeps rolling and rolling. Even after it gets its 10 rolls in. It started in one discord but now it happening in all of them. The problem started after I left the bot running for a while. How do I fix this? The bot only has one other problem which it rolls 9 instead of 10. Thanks in Advance

**Comment by vivinano** [comment]
Can you show me the time it kept rolling cause normally the problem that get reported is that it’s one short

**Comment by Jeez1221** [comment]
![image](https://user-images.githubusercontent.com/91221944/134417865-67679c22-fdb6-43c3-bca5-2b56f249e1ea.png)
![image](https://user-images.githubusercontent.com/91221944/134417885-5afab78c-de40-4253-94fe-c54924f3766f.png)
it did this across all the servers it was in. Until I stopped and reset it but I don't want it happening again when I don't realize it.

**Comment by vivinano** [comment]
Ya makes sense let me check the Waifu wait as it suppose get the name and the time to wait

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/134440556-5650f77e-31ce-4c9d-b45d-65c6050c027f.png)

right here is the code for this As long as your usersname start off the string it should stop the rolling so im unsure waht happened here

**Comment by Jeez1221** [comment]
let me check that everything is good

**Comment by Jeez1221** [comment]
![image](https://user-images.githubusercontent.com/91221944/134451201-7ef70ce9-cd73-497c-80b7-390a1ffbb8a7.png)
here is what i got

**Comment by vivinano** [comment]
is the issue consistantly happening cause it might be a thing were the internet might have dropped of something and it cause the message gateway to drop which means that it will never receive data to parse

**Comment by Jeez1221** [comment]
It happened again today. wym by the internet dropped off, do you think shitty connection could cause problems?
![image](https://user-images.githubusercontent.com/91221944/134583904-d8fab03a-ea88-4ca6-bb71-dd6c5f617c2c.png)
here is what it says and i did the rolls left thing and it still kept fucking up

**Comment by vivinano** [comment]
Could you do an print(bot.gateway…[username]

Cause I would think it’s not receiving the correct data ? And yes because there is a 5 sec window and If it didn’t receive the stop message

**Comment by Jeez1221** [comment]
wym print bot.gateway? do you want me to take a screenshot?

**Comment by vivinano** [comment]
No write that in the code trying to see if it prints out Oli because the only check I could think about failing is “Oli” being at the start of the mudae response

**Comment by Jeez1221** [comment]
where in the code do you want me to put it in? sorry if I'm being annoying btw I'm kinda new to python.

**Comment by vivinano** [comment]
You can put it before the area that states it in the code and it’s fine 

I’m not able to reproduce the issue on my end so I’m unsure what is going on so I have to basically walk you thru basic troubleshooting

**Comment by Jeez1221** [comment]
so any part of the code right? or before the anti overroll code

**Comment by vivinano** [comment]
`print(bot.gateway.session.user['username'])`
and also put 
`print(varwait['content'])`

the 1st one should print your user name
and the second should print the content and it should help narrow down if this is the issue

![image](https://user-images.githubusercontent.com/33008397/134778299-58cc5f13-d56c-46f3-9291-8f071297a19c.png)

**Comment by vivinano** [comment]
just making sure this was fixed as I havent heard back ?

**Comment by Jeez1221** [comment]
yeah it got fixed, thank you. Idk how though since It hasnt happened in 5 days

**Comment by vivinano** [comment]
I might have been a connection problem so any time your connection drops out it will close the message gateway which will cause issues with stopping the thread
