### ISSUE TITLE
Generally lost (But I don't wanna waste your time)

### ISSUE THREAD

**Issue by Danklin5411** [vivinano/MudaeAutoBot#105]
I've used git cloning to get Discum and the Bot into a path on my c drive, but I'm still getting errors when I run through IDLE.

ModuleNotFoundError: No module named 'discum'

I'm a huge noob. I don't want you to try to walk me thought every step, but I can't figure out what's going on right now, so I'd like a lil nudge. 

Thanks in advanced for your time. 

P.S When I try to use setup.py for DISCUM i get 
SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied.

Sorry again for my incompetency.

**Comment by vivinano** [comment]
this is a python enviroment error these are really touch to locate and is better to google like `pip not installing correctly`

there was a thread that we spent over 300 comment back and forth before finally locating it 

some thing i can tell you is that windows does like to force its "Own version" of python so basically causing you to have 2 instances of python

**Comment by vivinano** [comment]
I will still leave the thread open for a bit for minor help things but deep diving will take a long time

**Comment by Danklin5411** [comment]
Thanks for the tip. I'll look into it.

**Comment by vivinano** [comment]
no problem if you still hit dead ends i think i can think of a few things but mainly its casued from windows and regular pythons both being installed

**Comment by vivinano** [comment]
just checking in making sure everything is okay ?
