### ISSUE TITLE
min_kak It does not work properly

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#106]
Hello, min_kak is not working correctly, even on the server showing the value in kakera during the rolls, it only worked 2x in a week, even coming waifus that would activate min_kak.
In order not to have any errors, I downloaded the bot again and just changed the
   `"claim_delay":0` and `"kak_delay":0`,
and I put `"min_kak":270`, but even so he missed a character with a value greater than 400 kakera, I went to look in the log and he didn't even try to react

below my settings:

![image](https://user-images.githubusercontent.com/82736191/134550461-d2c6b553-25d1-490b-92b0-12cb512e3370.png)

**Comment by vivinano** [comment]
was it within the claim window ? as mention during previous interaction we have that if the bot has sniped something previously then it will not log and ignore the character 

EX: if you made a claim already then the bot will no longer check until the next claim window

**Comment by BellaDona007** [comment]
The bot had not yet spent a claim, the bot did not show anything of the character with more than 400 kakera, when it appeared
