### ISSUE TITLE
Setup help

### ISSUE THREAD

**Issue by BlamoThePollo** [vivinano/MudaeAutoBot#108]
![image](https://user-images.githubusercontent.com/66040494/135190671-448531a6-3490-40dd-8efa-eb5b2dbf69be.png)
These are my settings
And after I run the program(both cmd and IDE), it goes "entering heartbeat" and begins to spam me in cmd prompt infinitely, but on IDE it spams me shortly and gives me a few errors..
![image](https://user-images.githubusercontent.com/66040494/135191073-666b35ad-d2fa-463d-bcc3-06380ff10843.png)
![image](https://user-images.githubusercontent.com/66040494/135191127-ddc57f79-b034-4d48-8f45-c38e717517db.png)

Also, I'm a bit confused how the "min-kak" setting works, depending on its value will the bot automatically claim any character more than min-kak? Or will it only be looking for wishlist characters worth more than min-kak? Either way, if a specifically listed character / series is worth less than min-kak will the bot still claim it?

Thanks, I appreciate your work and efforts.

**Comment by vivinano** [comment]
Yes so it seems like you have a older version of discum which is why it is giving errors 


And yes min kak is a separate sniping option so it will not limit other sniping method if you have a character that is worth 1 kak it will still snipe is because atleast 1 will be true

**Comment by BlamoThePollo** [comment]
Took me a while but I managed to get the correct version of discum and now your program is up and running!
Does it also snipe wishlist characters (Regardless of kakera/if i listed it)? And also what would be the minimum time to be able to get it as fast as possible? (My server has no timer and I set it to 1 as you recommended it but I think it is slower than my friends reaction), can I set it to a float value?

**Comment by vivinano** [comment]
currently there is a small delay added of like .5 seconds but other than that all snipe timers are automated in the current version so it will do the math and see what timer is on what server no need to worry about that per say

you can think of timing in stages
`Computer Processing speed` (how fast your personal computer can run all this codes and the various checks) > `Wait .sleep function if needed` > `Discord Interaction` (speed at which the Discum library functions * out of my control * and your connection to discord servers > `Mudae` (time Mudae sees that you have reacted)


Normal interaction for human can be seen as
`Roll` > `See X` > `Reacts` > `Mudae`(too fast or too slow) 

ultimately the person rolling will always get priority as there are way less steps to do  

the bot usually wins when it comes if someone rolls and someone other than the roller wants to claim X character 

if you need more of an explanation just let me know

as for `Wished` 
All functions are considered one check so `if kak_value > min_kak` is one check  another will be `if username in message.content` is the wish check , `if series_name in series_list` and finally `if name in Embed.name` so if it passes even one of those check it will snipe

**Comment by BlamoThePollo** [comment]
Program has been working pretty well so far, I do recieve this error in command prompt occasionally
![image](https://user-images.githubusercontent.com/66040494/135356817-10f3eaf0-b45c-44fe-a398-2150706959f2.png)
But it hasnt caused any major issues with it yet.

Was also wondering if there is anyway I can make the program even faster? To the point where it could steal a character from whoever was rolling.

**Comment by vivinano** [comment]
Delete every function that is not needed so it doesn’t have to run thru code 

You could also update to the developmental version to possibly speed up discord interactions 


And that error is usually a thing when you get a message from mudae that doesn’t have an embed

**Comment by BlamoThePollo** [comment]
Would you mind outlining which functions I can delete without any issues?
Currently im only checking for if the kakera value of the character > min value or if the character is one of my listed characters or from a listed series, and reacting to the character if so. I am also having the bot react to kakera depending on its color.
I believe that the wait function / setting is unnecessary in my situation, and the automatic rolling / claiming at the end of each 3 hour period as I am not using that either.
And what would I be updating to the developmental version and how would I do that?

Also, even if i were to do so, by how much would this speed up my claim time?

**Comment by vivinano** [comment]
That would fall into the realm of me personally designing the app. I can say that kakera sniping and claim sniping are on the same thread.
You can delete the wish sniping , char sniping etc.

As for developmental version of discum that is a discum dev question as He/she has told me to us about the developmental version so you can contact them also to update 


As for time saved this is variable and based on many factors like processing speed , internet connection , mudae so can’t really give you a estimate without testing on your machine

**Comment by BlamoThePollo** [comment]
Alright, I appreciate it!

**Comment by vivinano** [comment]
No problem let me know if there are any more issues or more features you would like to add. Remember to star to repo if you haven't it's a free way to let me know that my project is well received. I will be closing this issue as of now thank you
