### ISSUE TITLE
how do i fix this

### ISSUE THREAD

**Issue by rratxdd** [vivinano/MudaeAutoBot#111]
![Screenshot (18)](https://user-images.githubusercontent.com/91861743/136136437-ae852e2c-a7e8-498e-b4f9-94d4c1b208f1.png)
I already tried changing the value but nothing happen

**Comment by vivinano** [comment]
Can post channeldata txt

**Comment by rratxdd** [comment]
[891362953507532821.txt](https://github.com/vivinano/MudaeAutoBot/files/7290807/891362953507532821.txt)
here

> Can post channeldata txt
> […](#)
> Sent from my iPhone
> On Oct 5, 2021, at 11:42 PM, rratxdd ***@***.***> wrote: ﻿ I already tried changing the value but nothing happen — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vivinano** [comment]
Yeah the only reason is because the old version did not anticipate #.x values so it sees it as 2 values 

But I have not pushed a release so you will have to clone from the main branch

**Comment by rratxdd** [comment]
> Yeah the only reason is because the old version did not anticipate #.x values so it sees it as 2 values But I have not pushed a release so you will have to clone from the main branch
> […](#)
> Sent from my iPhone
> On Oct 6, 2021, at 10:00 PM, rratxdd ***@***.***> wrote: ﻿ Ah yea the releases so about the releases they are a little behind the current as the new fixes have just been small fixes like the float fix so you have one that was like maybe a month back but that were the problem is from … Sent from my iPhone On Oct 6, 2021, at 9:27 PM, rratxdd @.***> wrote: ﻿ I really think you might have and older version of the repo as with the commit on August I added the support for 2.5 (float) options but I already downloaded the latest version of the repo — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. alright, I'm gonna check those releases. So these things popped up only in a server with snipe protection, cuz when I test it at my private server it worked really well. But yeah, thanks for the help — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

yep I already copy it  from the main branch and it worked so well, and thanks once again
