### ISSUE TITLE
2021-10-06 12:37:19,028:Could not find settings for 864273956411539486, please trigger the '$settings' command in the server and run the bot again.

### ISSUE THREAD

**Issue by Idiot1183** [vivinano/MudaeAutoBot#112]
I have been receiving this error and I don't know why. Server premium 2. Player premium 2.

Edit: It works on my alt account but not my main one

**Comment by vivinano** [comment]
Can I see the channeldata.txt for server and side question are both account able to access the server ??

**Comment by Idiot1183** [comment]
Yeah sure. 
[864273956411539486.txt](https://github.com/vivinano/MudaeAutoBot/files/7295812/864273956411539486.txt)
Also, Yes. Both accounts can access the server

**Comment by vivinano** [comment]
Try renaming that file maybe add like an extra number 

And try to get it to repull the the channeldata

**Comment by vivinano** [comment]
havent heard back for a week closing issue
