### ISSUE TITLE
"min_kak" works when it wants 

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#114]
I just started the bot and a character came with 600 kakera and my min_kak is at 450, he just ignored it.
In my last topic I reported this problem, but strangely it returned to work normally, but now it works again whenever you want, I don't know what can be wrong.
![image](https://user-images.githubusercontent.com/82736191/136620287-d1bb1ccf-40d4-4325-a601-454058ec77b1.png)

I would like to suggest 2 improvements:
1 - After a character's claim, the bot waits to reset the claim to run again (you said it would be interesting to continue running because it could gain keys, but even with a good disablelist, if you don't have all the emblems at the most and many rolls, it's easier for you to rerun your wish)
2 - The person defines a time interval that the bot will randomly choose when it will start running, after the reset, currently resets the rolls and the bot already starts running, ideally it would run randomly within the first 40 minutes to avoid suspicions.

**Comment by vivinano** [comment]
Did someone else claim it during that time ? Cause it will not claim if someone else successfully claimed it

**Comment by BellaDona007** [comment]
> Did someone else claim it during that time ? Cause it will not claim if someone else successfully claimed it

The character was free, the bot didn't react.
It seems to work when it wants to, just now it worked.

**Comment by vivinano** [comment]
I have mine that been running for about 3 weeks and it's hasn't missed a single snipe so the issue might be on connection speed or with the discum library

**Comment by vivinano** [comment]
gonna close issue as have been running and issue hasnt arose
