### ISSUE TITLE
Slash command

### ISSUE THREAD

**Issue by ViviPrimnoia** [vivinano/MudaeAutoBot#115]
How do I make slash command work? 
I have read some of the issue 
I already tried changing channeldata prefix to "/" but I got a normal spam chat (non-slash command, just normal chat that doesn't trigger anything). I even tried adding space to the end of the prefix like "/wx " but it still sending a normal chat.

**Comment by vivinano** [comment]
Functionality has now been added but more variables are added in settings and all that im testing it but feel free to use the slash function now
