### ISSUE TITLE
bot.sendMessage doesn't work

### ISSUE THREAD

**Issue by Aries298** [vivinano/MudaeAutoBot#118]
A few days ago, the bot started acting up. Turned out that everything works except the bot.sendMessage comand, meaning the code gets executed but the message isn't sent. I tried to somehow recreate the issue but even on a simple example it works and doesn't work randomly.
I assume it might be discum issue, so if you're sure nothing is wrong on the bot's side you can close the issue.

**Comment by vivinano** [comment]
Well it has to be discord sided as I also run my bot and it's been sending messages just fine. How are you testing that it is not sending messages ??

**Comment by Aries298** [comment]
![img11](https://user-images.githubusercontent.com/85286463/137628640-fee49864-0033-406f-b111-3ee7a1e60eeb.png)
If I send message directly below the declaration of the bot it works just fine.
![img2](https://user-images.githubusercontent.com/85286463/137628648-6efcc4ab-35e8-4e54-a893-d3f5622c4596.png)
Then, after some lines of code, I put that and only testmsg1 gets printed out in the channel.
![img3](https://user-images.githubusercontent.com/85286463/137628666-3b7ed878-8c90-459d-8195-c951d851093e.png)
Also, I put some text before and after the actual rolling command and it gets printed out normally so the line gets executed but there's no output in the channel.

**Comment by vivinano** [comment]
I think someone tried to use replit and there were some issues u might have to make the whole thing into one file maybe that will get it to run ?
