### ISSUE TITLE
What does the limited version do

### ISSUE THREAD

**Issue by seriaati** [vivinano/MudaeAutoBot#12]
As the title says, there is a mudae auto bot limited.py in the folder, what does it do?
What's the difference between the standard one and the limited one?

**Comment by RecentYogurt** [comment]
the normal version basically runs and snipes from every discord channel that mudae types on across all your servers. The limited version basically makes it so that you can set which specific channels to snipe in using the multi ids in the settings.json

**Comment by seriaati** [comment]
i see, thank you.
