### ISSUE TITLE
Error Most likely something on my behalf

### ISSUE THREAD

**Issue by adam4145** [vivinano/MudaeAutoBot#121]
Here is what idle shows me when I run MudaeAutoBot.py

============= RESTART: C:\Users\Adam\Documents\otherapps\MudaeAutoBot-2.0v3\MudaeAutoBot.py =============
Traceback (most recent call last):
  File "C:\Users\Adam\Documents\otherapps\MudaeAutoBot-2.0v3\MudaeAutoBot.py", line 29, in <module>
    settings = json.load(jsonf)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 337: character maps to <undefined>

**Comment by vivinano** [comment]
It seems like a json file is there a special character that been used in your file ? Upload or screenshot your json file without your token plz

**Comment by adam4145** [comment]
{
	"token": "notmytoken",
	"channel_ids": [
		notmychannelid
	],
	"claim_delay": 0.2,
	"kak_delay": 0.5,
	"use_emoji": "<:keqing_love:795077041761288214>",
	"roll_this": "wa",
	"rolling": "True",
	"pkmrolling": "True",
	"series_list": [],
	"namelist": [
		"Yoruichi Shihōin", "Winry Rockbell", "Orihime Inoue", "Komi Shouko", "Esdeath", "Hitagi Senjougahara", "Black Hanekawa"
	],
	"emoji_list": [
		"kakera",
		"kakeraT",
		"kakeraG",
		"kakeraY",
		"kakeraO",
		"kakeraR",
		"kakeraW",
		"kakeraL"
	],
	"soulemoji_list": [
		"kakeraO",
		"kakeraR",
		"KakeraW",
		"KakeraL"
	],
	"min_kak": 99999
}
python -m pip3 install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git

**Comment by adam4145** [comment]
is it the o in yoruichis name

**Comment by adam4145** [comment]
it probably is

**Comment by adam4145** [comment]
Yep that was the problem, sorry for wasting your time

**Comment by vivinano** [comment]
No worries I think the best way would be to add it to your wishlist to snipe it >_< sorry it would have been okay in python code but because I'm trying to make is easier and user friendly json doesn't support that
