### ISSUE TITLE
Problem about v4

### ISSUE THREAD

**Issue by fookbuck** [vivinano/MudaeAutoBot#122]
Problem:
1. sometime it will roll with both slash and normal rolling
![image](https://user-images.githubusercontent.com/26791163/140597260-336bfe27-f23a-449d-9dfc-96641e164a5d.png)
edit:
I guess this happen because it start both thread for normal roll and slash roll
Is it because my setting is like this? Should I just disable `rolling` and enable `slash_rolling` only?
```
	"rolling":"True",
	"slash_rolling":"True",
```

2. it wont finish last roll with slash command (and also not doing overroll)

**Comment by vivinano** [comment]
1. This is a setting issue. Either turn off "slash rolling" or rolling or use both but with different channels 


2. Known issue rolls until you have one left working on a fix
