### ISSUE TITLE
Blank window. No idea whats wrong. No errors

### ISSUE THREAD

**Issue by d3d43** [vivinano/MudaeAutoBot#124]
![image](https://user-images.githubusercontent.com/47383653/140733647-f7a14ff6-a21b-4066-93dc-c078a77aba17.png)

so ive set up the bot and the config as required in readme. json file is verified on the verifier provided in readme. When I run the py file, it just hangs. no feedback whatsoever. it doesnt crash nor provide anything. just a blank window

**Comment by d3d43** [comment]
running py 3.9. everything is installed. (discum)

**Comment by d3d43** [comment]
could this be due to lack of token? i've looked up how to get the token on various tutorials, but seems to be outdated. the numbers i grabbed may not be token

**Comment by vivinano** [comment]
it could be since there nothing to login to then its just gonna hang but there is no errors to crash the program

**Comment by d3d43** [comment]
is your method for obtaining login token the one with inspect element? I coudlnt find the token like in various yt videos. mind sharing the method?

**Comment by vivinano** [comment]
I used ctrl+shift+I in the discord app itself as it's an electron app 

Then you just refresh a couple of times and it should be there if I remember correctly

**Comment by d3d43** [comment]
cool. seems to be working now. thanks!
