### ISSUE TITLE
No module named 'discum'

### ISSUE THREAD

**Issue by beyabay** [vivinano/MudaeAutoBot#125]
![image](https://user-images.githubusercontent.com/56668359/140749056-aaa38695-c571-40fb-b525-d791dfe0d4be.png)

**Comment by beyabay** [comment]
also do you have a discord where i can contact you with?

**Comment by beyabay** [comment]
oh well im still lost LOL
my discord is beyabay#0001, if you could help but its okies if you won't 
but thanks anyways

**Comment by beyabay** [comment]
oh thanks it worked, but then i ran into this error 
![image](https://user-images.githubusercontent.com/56668359/140799573-accc05a1-4d00-45b0-ac1a-e15603a7200d.png)

**Comment by vivinano** [comment]
Did you get a channeldata instance for the channel that is rolling or snipping in

**Comment by beyabay** [comment]
> Did you get a channeldata instance for the channel that is rolling or snipping in
i fixed it by running the command $settings in the channel,
thanks for helping <3

**Comment by vivinano** [comment]
No problem be sure to follow and give the repo a star to show your support ^^
