### ISSUE TITLE
weird embed error

### ISSUE THREAD

**Issue by beyabay** [vivinano/MudaeAutoBot#126]
![image](https://user-images.githubusercontent.com/56668359/141118709-e2efa183-1551-4242-926c-5b688ae1d062.png)

**Comment by vivinano** [comment]
That usually comes from messages from mudae that doesn't have an embed 

Is this the case here or did something else happen ?

**Comment by beyabay** [comment]
yeah that's the case, i thought it was some type of bug or something

**Comment by vivinano** [comment]
What was the message ?

**Comment by beyabay** [comment]
whenever a user sends a normal msg in the channel t_hat's not a mudae cmd,_ 
the weird embed error block shows in my cmd

**Comment by beyabay** [comment]
also this might be off topic, but the bot keeps on overrolling, is there a way to prevent that?

**Comment by vivinano** [comment]
Over-rolling how it's suppose to stop when it get the message to stop or and ppl say more or so have an issue of under rolling by one

Unless you have both slash rolls and normal rolls on in the same channel 
I think it might be a setting issue

**Comment by beyabay** [comment]
oh wait so you mean i have to disable rolling in mudae settings or the selfbot config settings?
also it says use $rollsleft 0 to prevent it but it doesn't even work 
![image](https://user-images.githubusercontent.com/56668359/141354938-a0ad6a89-a799-4a16-b7e8-93f5f00c2d1c.png)

**Comment by beyabay** [comment]
i have pkmrolling set to false is this slash rolling ? or what does it even stand for?

**Comment by vivinano** [comment]
slash rolling is /wg compared to $wg

so if both are enabled it will do 10 each so it over rolls

**Comment by beyabay** [comment]
oh well makes sense, thanks for explaining

**Comment by beyabay** [comment]
also as a suggestion i think that embed block "error" should be remove or at least showen in a better way , because right now it clogs up the logs
![image](https://user-images.githubusercontent.com/56668359/141359409-f60ada91-e1fa-42fa-ab8a-fa2dec925156.png)

**Comment by vivinano** [comment]
well there isn't suppose to be an error. technically its suppose to be filtered out but I still don't know what triggers this error

**Comment by beyabay** [comment]
i don't know too, maybe its random LOL

**Comment by vivinano** [comment]
seeing r['embeds'] is a code called when message is updated so it would have to be an updated message that causes this error

**Comment by beyabay** [comment]
i think i figured it out,
both users used the cmd $wg and rather than rolling and showing a waifu embed, it showed this msg and my cmd sent the error again 
![image](https://user-images.githubusercontent.com/56668359/141374245-f66bf898-b8e6-413e-a64e-eec95b19d0c7.png)
![image](https://user-images.githubusercontent.com/56668359/141374290-f127e1e8-57ef-4c91-9d9f-c6ba19550a33.png)

**Comment by vivinano** [comment]
Hmm I think that is accounted for as it doesn't have a edited time stamp unless your referring to over rolling

**Comment by beyabay** [comment]
yeah it might be cause of ppl overrolling

**Comment by vivinano** [comment]
Most people I play with here over roll as they just copy pasta until they hit the over roll so I don't think it's the over roll message as I'm not getting the error on my end

**Comment by beyabay** [comment]
hmm, i will try and keep an eye for it

**Comment by beyabay** [comment]
hey so like the embed error showed again when mee6 sent a msg,
i think the errors aren't coming from your bot, and the problem is from discum 
![image](https://user-images.githubusercontent.com/56668359/141704332-1e39df38-9bcf-4d75-aa50-6e91774f969f.png)
![image](https://user-images.githubusercontent.com/56668359/141704346-3525f9d2-07c5-4464-9689-a65e9b8e433c.png)

**Comment by vivinano** [comment]
Lol is that a bot to react to a bot

**Comment by beyabay** [comment]
> Lol is that a bot to react to a bot

LOL no no no, its just a reminder bot, it doesn't react or anything, it basically sends a msg every 4hrs

**Comment by vivinano** [comment]
The bot has a last minute snipe function not sure if it gets used a lot but it snipes in a time frame given with different parameters

**Comment by beyabay** [comment]
this might not be the right place to ask this, but is there a way to whitelist members, 
with this i mean, to make the bot not snipe certain members if you add them to the whitelist

**Comment by vivinano** [comment]
There is a function to not snipe at all (only claiming personal rolls)
But that is it. But for future reference just create a different issue when needed to ask questions
