### ISSUE TITLE
been getting random error msgs in between logs

### ISSUE THREAD

**Issue by beyabay** [vivinano/MudaeAutoBot#127]
![image](https://user-images.githubusercontent.com/56668359/141686635-1d1845a9-75ba-464b-84a4-15eee4a4ab88.png)
idk what happened but my logs are flooded with error msgs

**Comment by vivinano** [comment]
That seems like a discum issue

**Comment by beyabay** [comment]
oh its been spamming the same text for a while now 
![image](https://user-images.githubusercontent.com/56668359/141686874-aa00f8a4-8b72-44b8-947e-f930176ee3ad.png)

**Comment by beyabay** [comment]
> That seems like a discum issue

just tried using this cmd `python -m pip install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git#egg=discum
`
to install discum again. but it didn't work.

**Comment by beyabay** [comment]
also if it helps i downgraded from python 3.9.7 to python 3.8.5 
is me doing that causing this error?

**Comment by vivinano** [comment]
it depends im not sure what python functions are removed from 3.9 to 3.8

**Comment by beyabay** [comment]
> it depends im not sure what python functions are removed from 3.9 to 3.8

so like i reinstall python amd discum, i still have the error,
is there something im doing wrong?
is there any other ways to install discum correctly? 
![image](https://user-images.githubusercontent.com/56668359/141692373-063a88c4-ee1d-4dbf-a411-88be39600c18.png)

**Comment by vivinano** [comment]
Discum questions I really can't answer as I only use their library whatever background things are happening. Your best bet would be to contact the discum developer

**Comment by beyabay** [comment]
> Discum questions I really can't answer as I only use their library whatever background things are happening. Your best bet would be to contact the discum developer

aight thanks

**Comment by beyabay** [comment]
fixed: downgraded from python 3.10 to python 3.9.7

**Comment by vivinano** [comment]
Wait you downgraded from 3.9 to 3.1 ?

**Comment by beyabay** [comment]
> Wait you downgraded from 3.9 to 3.1 ?

no no i went from 3.10 *three point ten* to 3.9
