### ISSUE TITLE
Opens then closes immediately

### ISSUE THREAD

**Issue by Kaizuk-O** [vivinano/MudaeAutoBot#128]
Downloaded the latest version with the slash features - however, after trying to open it closes straight after.

Tried to find out why so I ran it in IDLE and this is what it shows:

```
Traceback (most recent call last):
  File "C:\Users\xxxx\Downloads\ALL MUDAE FILES\xxxxxxxx\MudaeAutoBot.py", line 10, in <module>
    from discum.utils.slash import SlashCommander
ModuleNotFoundError: No module named 'discum.utils.slash'
>>> 
```

Any idea what I could do to fix this? As far as I am aware I have DISCUM installed unless there is a new version?

**Comment by vivinano** [comment]
And it was working before the new push right ?

**Comment by Kaizuk-O** [comment]
Hi yes, it was. I managed to get it to stop closing immediately by installing the latest version of DISCUM however, this is what I am getting now when launching the script:

```
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000217939C23A0>>
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\discum-1.4.0-py3.9.egg\discum\gateway\gateway.py", line 292, in _response_loop
    func(resp)
  File "C:\Users\xxxx\Downloads\ALL MUDAE FILES\xxxxxxx\MudaeAutoBot.py", line 707, in on_message
    bot.gateway.request.searchSlashCommands(str(ghids[0]), limit=100, command_ids=[])
IndexError: list index out of range
```

Very peculiar - is this perhaps a discum issue? Would reverting back to the old release work better?

**Comment by Kaizuk-O** [comment]
Just an update, the previous release still works after running that just now - it seems the latest release is what is giving me this error

**Comment by vivinano** [comment]
Hmm maybe a outdated discum then cause I think when I first released slash commands weren't implemented with older version of discum check if there is a new download from discum

**Comment by Kaizuk-O** [comment]
The most recent error I got was with the latest version of discum (1.4). I'll try downloading it directly from discum releases to see if it makes any difference because I did see that when I got my first error, I had ver 1.3 which didn't have the slash commands, but in my most recent error it does show I have 1.4 installed. 

I'll try a redownload from discum now and update you on whether it's the same issue. 
Just to confirm however, is it worth doing `python setup.py build` before installing it again?
And do you happen to know how to completely uninstall discum?

**Comment by vivinano** [comment]
Did you enter a guild ID or server id that has access to mudae to query the bot

**Comment by Kaizuk-O** [comment]
I just tried the latest release now, it seems I made an error by downloading it via the master code on the home page
![image](https://user-images.githubusercontent.com/89078343/141705088-46203edd-6c53-4a04-8195-a162e62bd49c.png)

Since then I just downloaded it from the releases section and it works now.

I am curious however about the slash rolling:

`{
   "token":"mxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "channel_ids":[
	  8XXXXXXXXXXXXXXXXXXX15
   ],
   "slash_ids":[
	  8XXXXXXXXXXXXXXXXXXX15
   ],
   "slash_guild_ids":[
      8XXXXXXXXXXXXXXXXXXX15
   ],
   "claim_delay":0.5,
   "kak_delay":1,
   "use_emoji":"<:keqing_love:795077041761288214>",
   "roll_this":"mg",
   "rolling":"True",
   "slash_rolling":"True",
   "pkmrolling":"False",`

I have the above settings, but it doesn't seem to roll using the slash commands, instead uses the $ prefix - any ideas?

**Comment by vivinano** [comment]
Slash rolling needs guild id which is a server that has mudae to query 

Guild id is a server and not a channel id I see that your channel id looks like your guild id 

And then the bot itself have to have slash commands enabled to roll with slash commands 

And try not to have the same channel in both as then it try's to roll and slash roll

**Comment by Kaizuk-O** [comment]
Ah, got it. Thank you so much man, appreciate the help! All sorted :)

**Comment by vivinano** [comment]
Okay cool I'll close the issue :3
