### ISSUE TITLE
Bot keeps rolling even after claiming

### ISSUE THREAD

**Issue by Leroys2019** [vivinano/MudaeAutoBot#129]
Unsure of what to do to fix this issue but every time the bot rolls a high claims it claims it then continues to keep rolling leading to it rolling an even higher claim.

Heres an example: 
Reading from File for channel 875201721247342732
Reading from File for channel 831312459276353576
File Not Found using Different Method
Using $settings found during search for channel 872231437598863412
7200 : pokerolling : 872231437598863412
True: Waifu rolling : 875201721247342732
Our user rolled in 872231437598863412
Our user rolled in 872231437598863412
2021-12-02 20:19:00,816:Elaina with a 293 Kakera Value appeared Server:826085363700203520
2021-12-02 20:19:01,650:Sniping time waited Reaction was added
Our user rolled in 872231437598863412
Our user rolled in 872231437598863412
True: Waifu rolling : 831312459276353576
Our user rolled in 872231437598863412
Our user rolled in 872231437598863412
Our user rolled in 872231437598863412
Our user rolled in 872231437598863412
True: Waifu rolling : 872231437598863412

Also I've only changed code within the settings.
![image](https://user-images.githubusercontent.com/72043750/144534098-da8a1a0b-5c63-4970-9372-52e7e584cc80.png)

I've also run into the issue where the bot rolls without having a claim ready so its just rolling without a purpose.

**Comment by vivinano** [comment]
the bot is programmed this way for soul mate rolling this is not technically an "issue"

you could write code to close the rolling thread each time a claim has been made but then you also have to reopen the rolling thread everytime you refresh a claim

**Comment by Leroys2019** [comment]
Oh alright thanks ill try looking into it for now thank you for the help.

**Comment by vivinano** [comment]
no problem the bot was designed for a more broader audience so things like precise to the claim rolling are features that not everyone wants. but its possible with the code. the code should be pretty easy to understand as I've only limited myself to using the standard library for the most part

**Comment by Leroys2019** [comment]
I found a fork of your code already that added a delay timer to the claims. Still testing it out to my liking but it works pretty well.
https://github.com/OMASHE/MudaeAutoBot

**Comment by vivinano** [comment]
Browsing the fork in reference to claim delays I think he just means the delay before claiming a character

What you want is like previously stated is closing the thread(process) that handles rolling for the specific channel and then opening the thread if you want to stop rolling


If the issue is trying to optimize picking the highest out of your rolls then you need to interact with the 
"Msg_buf" variable which if I remember correctly has the messages stored

**Comment by Leroys2019** [comment]
True but I think there might be a way to tweak the already written code. Although Python isn't my most knowledge-able coding lang I found that the user included a wait timer to prevent the bot from rolling $p every 2 hours. 
![image](https://user-images.githubusercontent.com/72043750/144682528-e69de131-5f6b-421f-b072-41f0c4c4409d.png)
Although it's much simpler to have the bot write $p I was thinking if I could write a variable within the waifu thread that'll change once the bot claims a roll that is either in the name list, series_list, or above the min_kak and if that variable turns true then it'll place the bot on another "time.sleep" to prevent rolling another character essentially wasting rolls.

I've tinkered with the code a little earlier but it seems that I don't really have a good understanding of where or how i could implement this change.

def waifu_roll(tide):
    global user
    logger.debug(f"waifu rolling Started in channel {tide}")

    tides = str(tide)
    waifuwait = 0
    
    if tide not in channel_settings:
        logger.error(f"Could not find channel {tide}, skipping waifu roll on this channel.")
        return
    
    c_settings = channel_settings[tide]
    roll_cmd = c_settings['prefix'] + roll_prefix
    
    warned_overroll = False
    while True:
        wait_for_quiet = wait_for(bot,mudae_warning(tides,False),timeout=10)
        if wait_for_quiet != None:
            # don't do stuff
            continue
    
        c_settings['rolls'] = 0
        rolls_left = -1
        while waifuwait == False:
            bot.typingAction(tides)
            time.sleep(0.4)
            bot.sendMessage(tides,roll_cmd)
            rolls_left = rolls_left-1
            
            varwait = wait_for(bot,mudae_warning(tides,False),timeout=5)
            time.sleep(1.0)
            
            if varwait != None and varwait['content'].startswith(f"**{bot.gateway.session.user['username']}") and "$ku" not in varwait['content']:
                # We over-rolled.
                waifuwait = True
                if c_settings['rolls'] > 2 and not warned_overroll:
                    # We overrolled when we shouldn't have. Warn the user they can prevent this
                    warned_overroll = True
                    logger.warning("Please enable $rollsleft 0 feature to prevent overrolling")
                break
            elif varwait != None and rolls_left < 0:
                # Check if our roll featured a warning
                total_text = varwait.get('content','') # $rollsleft 2
                if len(varwait['embeds']):
                    total_text += varwait['embeds'][0].get('footer',{}).get('text','') # $rollsleft 0 (default)
                    total_text += varwait['embeds'][0].get('description','') # $rollsleft 1
                
                # Check if it's our roll
                our_roll = msg_buf.get(varwait['id'],{}).get('rolled',None)
                p = c_settings['pending']
                if our_roll == None and p:
                    # on_message may have not seen our roll, so we should manually check if it was our roll
                    our_roll = p == bot.gateway.session.user['id']
                    
                    
                if our_roll and "\u26a0\ufe0f 2 ROLLS " in total_text:
                    # Has warning for us
                    rolls_left = 2
            if rolls_left == 0:
                # Ran out of rolls
                waifuwait = True
              
        
        print(f"[{tstamp()}] {waifuwait}: Waifu rolling : {tide}")
        print(f"[{tstamp()}] waiting a random amount of time to roll again")
        time.sleep((randomint()+next_reset(tide)-time.time())+1)
        waifuwait = False

**Comment by vivinano** [comment]
Because the sniping and rolling are separate threads you have to pass a variable to that specific thread otherwise they do not see each other as they operate as separate entities

**Comment by OMASHE** [comment]
> Browsing the fork in reference to claim delays I think he just means the delay before claiming a character
> 
> What you want is like previously stated is closing the thread(process) that handles rolling for the specific channel and then opening the thread if you want to stop rolling
> 
> If the issue is trying to optimize picking the highest out of your rolls then you need to interact with the "Msg_buf" variable which if I remember correctly has the messages stored

Yes this is just the delay to wait before the bot adds a reaction, the bot will keep rolling after as I like to keep it rolling for kakera reacts.

**Comment by Leroys2019** [comment]
> 

But the time.sleep you used to pause the $poke rolling for 2 hours could also be used to pause the $waifu rolling if I use a variable within the snipe thread then pass it to the rolling thread once a character has successfully been sniped right?

**Comment by OMASHE** [comment]
> you could write code to close the rolling thread each time a claim has been made but then you also have to reopen the rolling thread everytime you refresh a claim

I think I would do this by setting a variable to true whenever a claim is made, if  that variable is true make the bot send a $mu (marry up) command, then have the bot read mudaes response and set another variable to the time you need to wait for your claim to reset, then you can change the time.sleep of the roller to wait that amount of time before rolling again.

just my idea/suggestion

**Comment by vivinano** [comment]
> > you could write code to close the rolling thread each time a claim has been made but then you also have to reopen the rolling thread everytime you refresh a claim
> 
> 
> 
> I think I would do this by setting a variable to true whenever a claim is made, if  that variable is true make the bot send a $mu (marry up) command, then have the bot read mudaes response and set another variable to the time you need to wait for your claim to reset, then while the first variable is true you can change the time.sleep of the roller to wait that amount of time before rolling again after the time.wait set the first variable to false.
> 
> 
> 
> just my idea/suggestion
> 
> 
> 
> 

Yes but since each is a thread when it comes to rolling you have to communicate that to the specific thread created

As each rolling instance is a separate thread to not clog up the main thread which handles the parsing and sniping

**Comment by OMASHE** [comment]
@Leroys2019 I updated my fork and maybe implemented an option to stop rolling when a claim is used if you want to test it. [https://github.com/OMASHE/MudaeAutoBot](url)

**Comment by vivinano** [comment]
Alright so I looked at the code and it seems like you added a global so the thing about globals it could work but only for a 1 channel basis 

So 

Global A = true

Channel thread 1 = true 
(Stops rolling in theory) 

Different channel thread 2 = true
(Stops rolling even if there is a claim left)

**Comment by OMASHE** [comment]
Ah I see, I did not think about this. Forgot it can be used in multiple channels, hmm maybe a fix would be using a dictionary to keep track of which channels claims have been used in, then that data could be easily pulled and checked in the if statement I added to stop rolling when a claim has been used.

**Comment by vivinano** [comment]
> Ah I see, I did not think about this. Forgot it can be used in multiple channels, hmm maybe a fix would be using a dictionary to keep track of which channels claims have been used in, then that data could be easily pulled and checked in the if statement I added to stop rolling when a claim has been used. 
> 
> 
> 
> -attempted fix 

I looked it over and yes this implementation will work if I'm reading it correctly but just keep in mind that using globals with multithreaded that only one thread can read and write to that variable at a time so you might run into issues down the line

**Comment by Leroys2019** [comment]
After about a day or so of testing both versions, it seems that without using globals the bot stops rolling just fine but doesn't begin rolling again meaning the variable "waifu_wait doesn't return to being false.
![image](https://user-images.githubusercontent.com/72043750/144772635-e27dbad9-ecd6-4561-bf9b-e6884d42cfd2.png)

For the version using globals, the bot tends to continue to roll after a claim has been made and it seems that it begins rolling solely on the rolls reset timer rather than the claim timer.
![botss](https://user-images.githubusercontent.com/72043750/144772136-da136521-6d32-4b55-8dbb-03aef0345dd6.jpg)
Note: I've tried running both codes in the most vanilla form possible without changing the settings to see if it might just be a weird coincidence of some code overseen.

**Comment by OMASHE** [comment]
Thanks for testing. I think I have a better solution than using globals, We can just check foe claim in the rolling thread instead of having a variable passed between threads. 

Also I think it doesn't start rolling again because the way I'm getting the claim time might not be correct/working.

**Comment by OMASHE** [comment]
Also, did you set stop_on_claim to true in the settings json?

**Comment by Leroys2019** [comment]
> 

Yes, I did while testing both versions, and I only used one channel to run the bot.
![image](https://user-images.githubusercontent.com/72043750/144779561-c15d8497-5d8c-48ed-a950-9932c1d315bc.png)

**Comment by vivinano** [comment]
So if you want to check within the thread you can do a "break" in the while loop which will take you out of the rolling loop but the thing is tho you must pass something using queues 

@OMASHE

**Comment by vivinano** [comment]
@OMASHE 
I think I thought of a simple way let me put in a pull request on your repo when I get home
