### ISSUE TITLE
Min Kak Sniping not working

### ISSUE THREAD

**Issue by RecentYogurt** [vivinano/MudaeAutoBot#13]
It doesn't seem to be working at the moment

**Comment by vivinano** [comment]
type $im zero Two it should trigger since it the highest thing i can think off the top of my head

**Comment by RecentYogurt** [comment]
Nothing is being triggered when I do $im zero two. I'm using the limited version.

**Comment by vivinano** [comment]
its not directly linked together u have to run both the message.support.py with the regular method of autobot this is my temporary fix lol its literally spagetthi code at this point

**Comment by RecentYogurt** [comment]
no wait i'm dumb, I don't have the discum module installed

**Comment by RecentYogurt** [comment]
okay I installed it and it's working fine lol

**Comment by vivinano** [comment]
I was going to do some more features like that but now im back to square 1 of learning a library again XD but maybe something similar to a check on if wleft is present
