### ISSUE TITLE
json token setting issue

### ISSUE THREAD

**Issue by LeonardowTN** [vivinano/MudaeAutoBot#130]
Hello uhh, i am getting this error could you help me?
![image](https://user-images.githubusercontent.com/96161526/146126125-e34aae7f-0b46-4427-aa95-4ae50facd815.png)

**Comment by vivinano** [comment]
Wrong formatting it’s trying to read the settings.json file with the key “redline”

**Comment by LeonardowTN** [comment]
So the error was the place where I put the token?

**Comment by LeonardowTN** [comment]
> Wrong formatting it’s trying to read the settings.json file with the key “redline” 
> 
> Sent from my iPhone
> 
> > On Dec 15, 2021, at 12:00 AM, LeonardowTN ***@***.***> wrote:
> > 
> > ﻿
> > Hello uhh, i am getting this error could you help me?
> > 
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 


So the error was the place where I put the token?

**Comment by vivinano** [comment]
Yup the error is a issue with set up the setting json is used to make that process easier

**Comment by vivinano** [comment]
Is the issue solved ?

**Comment by vivinano** [comment]
Going to close as haven't heard a reply for a few days 

Token issue. Given resolution of improper placement of token.
