### ISSUE TITLE
KeyError: 'slash_ids'

### ISSUE THREAD

**Issue by sotongboi** [vivinano/MudaeAutoBot#131]
line 40, in <module>
    shids = [int(sh) for sh in settings["slash_ids"]]
KeyError: 'slash_ids'

Can anyone help me figure out why there's this problem?

**Comment by sotongboi** [comment]
<img width="677" alt="image" src="https://user-images.githubusercontent.com/94187885/147180700-ed0b60a6-41c1-499a-94bb-28dd9a76092a.png">

**Comment by vivinano** [comment]
What is your .json file slash id value

**Comment by sotongboi** [comment]
> What is your .json file slash id value

{
   "token":"*insert my token here*",
   "channel_ids":[
	  741604352774373447
   ],
   "claim_delay":2,
   "kak_delay":2,
   "use_emoji":"<:arandomjarofpeanutbutter:890238775358259241>",
   "roll_this":"w",
   "rolling":"True",
   "pkmrolling":"True",
   "series_list":[
      "Honkai Impact 3rd",
      "Senran Kagura",
	  "Genshin Impact",
	  "Hololive",
	  "Kakegurui", 
	  "5-toubun no Hanayome",
	  "Akame ga Kill!",
	  "Kono Subarashii Sekai ni Shukufuku wo!"
   ],
   "namelist":[
      "Raiden Mei",
	  "Rem",
	  "Zero Two",
	  "Megumin",
	  "Nezuko Kamado",
	  "Mikasa Ackerman",
	  " Hange Zoë",
	  "Asuna",
	  "Rias Gremory",
	  "Saber",
	  "Chika Fujiwara",
	  "Yumeko Jabami",
	  "Emilia",
	  "Shinobu Kochou",
	  "Power",
	  "Makima"
   ],
   "emoji_list":[
	  "kakera",	
      "kakeraT",
      "kakeraG",
      "kakeraY",
      "kakeraO",
      "kakeraR",
      "kakeraW",
      "kakeraL"
   ],
   "min_kak":60,
   "Last_True":"True",
   "last_claim_min": 10,
   "min_kak_last_min": 30
}


That's all I have in the .json file.

**Comment by vivinano** [comment]
Ah your using old version of the json file if you recently updated for slash commands there a new field

**Comment by sotongboi** [comment]
How can I update? Do I just need to overwrite the new one with the old .json file and fill in with the characters and my info?

**Comment by vivinano** [comment]
You can just add the new fields it's only like 2 I think

**Comment by sotongboi** [comment]
Sweet it works now after the update. tysm

**Comment by sotongboi** [comment]
Last question, what value of `min_kak` do you think works best? @vivinano
