### ISSUE TITLE
Setting it up

### ISSUE THREAD

**Issue by ErosZenin** [vivinano/MudaeAutoBot#132]
How do i turn it on? im kinda new with this stuff and i want to use it but i dont know how to, i dont know what "slash_ids" is and i think its not working for me. How do i set up  the discum?

**Comment by ErosZenin** [comment]
![image_2021-12-26_200019](https://user-images.githubusercontent.com/90815466/147424445-44ee73d0-3409-4b21-96da-20c009a46e31.png)
That is what i get when i try to open Setup.py

**Comment by vivinano** [comment]
Ifs it's a discum installation issue please refer to the discum repo link in the readme they can help you install that on their side

**Comment by vivinano** [comment]
Gonna be closing as haven't heard back for a bit
