### ISSUE TITLE
Kakera Sniping Delay not working

### ISSUE THREAD

**Issue by Nixeld** [vivinano/MudaeAutoBot#133]
I'm not sure why but the kakera sniping delay is on 5 seconds even though it is set to 10 in Settings_Mudae.json and in the channeldata
![image](https://user-images.githubusercontent.com/18643932/147495569-2caae0a8-20a9-4e20-a062-43b24d035607.png)
![image](https://user-images.githubusercontent.com/18643932/147495659-ad7cb2b5-db17-4768-8f16-13ed70421426.png)
![image](https://user-images.githubusercontent.com/18643932/147495734-a8d55c41-13f6-40c3-b2a6-7988cc23edae.png)

**Comment by sotongboi** [comment]
Yeah it's the same for me it doesn't go along with the sniping delay it snipes the character in a second or two.

**Comment by vivinano** [comment]
Snipe delay was deprecated To less Important roll where if it finds a channel setting then it will determine best timing to successfully claim a character 

In your case @Nixeld check if you channelid matches the txt in channeldata

**Comment by Nixeld** [comment]
Yes the channelid matches the one in channeldata

I am only running this on one channel so there is only one .txt file in channeldata 
@vivinano

**Comment by vivinano** [comment]
snipe_delay = channel_settings[int(rchannelid)]['kak_snipe'][1]


That line right there pulls out the claim number so after that line you can do a print(snipe_delay) and then right before the snipe happens also put that same line 

Which should see if somewhere along the way we are getting incorrect values 


Also would like to apologize for the delay. 
(Covid issues arose)
