### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by EnesCK-V1** [vivinano/MudaeAutoBot#135]
I'm getting an error like this I don't know what caused it

![image](https://user-images.githubusercontent.com/74046770/151961131-237ce714-040f-4fcf-a2f9-4482fbcb9367.png)

**Comment by EnesCK-V1** [comment]
bot fixed after typing $settings but now it gives this error
![image](https://user-images.githubusercontent.com/74046770/151973963-8564c729-305b-4e38-979e-11b6525e510b.png)

**Comment by vivinano** [comment]
Is the cmd.txt seen by the program ? also what value did you put in the json for roll prefix 

And check the channel data folder to confirm if the prefix is set

**Comment by vivinano** [comment]
Can I see a screenshot? Of the requested so I can better narrow down a solution

**Comment by EnesCK-V1** [comment]
![image](https://user-images.githubusercontent.com/74046770/152029331-0b69dc8c-524e-4a7f-b3ab-048092d9ddb5.png)

**Comment by vivinano** [comment]
Okay so I think it cause with slash interactions it does not have just a "W" value only 

This is why it still works but slash commands will not work 

Basically mudae doesn't have a just only Waifu function

**Comment by EnesCK-V1** [comment]
Thank you for your help
