### ISSUE TITLE
Claim delay not working

### ISSUE THREAD

**Issue by TikaUnas** [vivinano/MudaeAutoBot#136]
For some reason, no matter how high I set the claim and kak delay it still claims immediately. I was wondering what exactly "Affects servers w/o $setting instance" meant because this may be why its not working. I tried looking through all the settings of mudae and the only time instance comes up is for channel instance.

**Comment by vivinano** [comment]
So basically whatever channel it pulls a $setting instance from it will write it to a file and after it
Does that then you should have a time setting if not then it pulls a default setting and uses that

**Comment by TikaUnas** [comment]
Oh alright, thanks. Do you know if there's a way to set it to follow the custom claim delay that we set in the Settings_Mudae.json, so that it doesn't claim instantly?

**Comment by vivinano** [comment]
It's follow whatever is set in channel data the setting mudae has been deprecated to just setting the default instance

**Comment by TikaUnas** [comment]
Oh alright appreciate it.
