### ISSUE TITLE
Slash rolling not working

### ISSUE THREAD

**Issue by fookbuck** [vivinano/MudaeAutoBot#138]
I just notice it stop rolling for many hours, so I try normal rolling and it seem working fine.

**Comment by fookbuck** [comment]
when you hit roll limit, it's same.
but with current slash rolling problem, it did nothing and not even say it is rolling in console

**Comment by vivinano** [comment]
is slash rolling enabled on your server's mudae because there a setting to turn off and on slash rolling on mudae itself ?

**Comment by fookbuck** [comment]
slash command is enabled and i can do it manually but your script just do nothing about it

other function is working fine, like logging about other rolling or do normal rolling

**Comment by vivinano** [comment]
ah alright I have tested the slash rolling feature and it does seem like slash rolling is broken. it has something to do with changes in discum library that is used for discord interactions. 

I will update my library and check for any more issues

**Comment by vivinano** [comment]
changes have been made and the script is now rolling again after update. 

be sure to also update to discum V1.4 (latest at the time of making changes)

![image](https://user-images.githubusercontent.com/33008397/156913861-168e13d6-6de8-4c88-962c-ba8558a72780.png)
