### ISSUE TITLE
Bot Claiming Wrong characters

### ISSUE THREAD

**Issue by Neonliy** [vivinano/MudaeAutoBot#140]
I have a list of 300+ characters and the bot keeps claiming characters that have the same first name as the listed character but isnt matching the last name as well to make sure

**Comment by vivinano** [comment]
Can you send me the list of character that have the name in question that is being claimed ?

**Comment by vivinano** [comment]
Did you put the series name on there ? Cause it could have sniped it via the series name

**Comment by Neonliy** [comment]
nope the only series in there is the default one, which i should probably delete.

**Comment by vivinano** [comment]
And kakera sniping isn’t set to a low value right ?

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/154789153-67b903c5-7ccb-45a2-8601-739c62de97ab.png)


made a mock example on how the name test works and its shouldn't be able to snipe

![image](https://user-images.githubusercontent.com/33008397/154789219-2ea1db01-4e41-4105-9e1a-3b7e64fb1da8.png)

and then final test with the exact name

![image](https://user-images.githubusercontent.com/33008397/154789262-f9abbcc6-6da6-4ecb-a36b-261e8f010563.png)

**Comment by vivinano** [comment]
you changed the min_kak value ?

**Comment by Neonliy** [comment]
no i changed the kak sniping and character sniping times
