### ISSUE TITLE
More users

### ISSUE THREAD

**Issue by RedbrickCobra66** [vivinano/MudaeAutoBot#141]
Is their a way to make it so more than one token can be used at once, so people can have more users watching over channels at once.

**Comment by vivinano** [comment]
I mean there is someone who forked my repo to attempt to do more than 1 user but he still figuring out the logistics. 
ultimately there hurtles like delays so you don't roll at the same time as bot 1. 
but in terms of possibility it is possible

**Comment by RedbrickCobra66** [comment]
Do know where I can find the fork?

**Comment by vivinano** [comment]
i think its owashe fork i think he was working on it unsure tho

**Comment by RedbrickCobra66** [comment]
Do u have a link to it?

**Comment by vivinano** [comment]
I don't have the link but I'm also unsure of the status of his repo if he gotten any of the bugs worked out.
ultimately I do think the bot could handle multiple users.

if you want you could convert the code oneself

I think all it would need is changing the token to a list [token1 , token2] and then using a for loop on the end that launches each bot. 

that is not to say the perfect solution but I think it would get you started on the correct path
