### ISSUE TITLE
discum is the only library that you have to install from the discum repo.

### ISSUE THREAD

**Issue by NFTman798** [vivinano/MudaeAutoBot#142]
discum is the only library that you have to install from the discum repo.

I have a discord but its for personal and at that point this project becomes less for fun and more like a paid job.

_Originally posted by @vivinano in https://github.com/vivinano/MudaeAutoBot/issues/125#issuecomment-963346643_
how do i install discum for visual studio code I installed this link 'pip install discum' and it says it worked but i still get the 'no module named 'discum'

**Comment by vivinano** [comment]
that sounds like a windows environment issue. I haven't used visual studio code but i assume installing it is there various other IDE's
