### ISSUE TITLE
cmd closing

### ISSUE THREAD

**Issue by clovdystackflow** [vivinano/MudaeAutoBot#144]
I tried to open it with IDLE but I still have no idea what's going wrong, I hope this screenshot can help you fix my issue; 
![image](https://user-images.githubusercontent.com/100868740/156623425-d2c8e5d8-3fd2-4f64-9752-61cd06475f6d.png)

**Comment by vivinano** [comment]
your setting json is improperly set up

**Comment by clovdystackflow** [comment]
alright, would you mind telling me whats wrong really quick?
![image](https://user-images.githubusercontent.com/100868740/156644008-1c08fd9e-10ad-4868-94c6-dc50e17c20b0.png)

**Comment by vivinano** [comment]
Try validating your json but also make sure you copied the correct token

**Comment by clovdystackflow** [comment]
i did validate the json, it says its okay, and im pretty sure i copeid the correct token

**Comment by clovdystackflow** [comment]
now it just shows the cmd blank, is that supposed to happen?

**Comment by vivinano** [comment]
The user is usually a token error so try to redo the token

**Comment by clovdystackflow** [comment]
i dont get user error anymore, but i get this
![image](https://user-images.githubusercontent.com/100868740/156832639-159e2bc3-b311-47b3-bb48-6c007ae832a0.png)

**Comment by vivinano** [comment]
Did you have rolling set up ? Or no

**Comment by clovdystackflow** [comment]
![image](https://user-images.githubusercontent.com/100868740/156843861-af55e3c1-ff3a-49d6-9867-35fa4c0fcf12.png)

**Comment by vivinano** [comment]
I shouldn't be $ma it should only be MA

**Comment by clovdystackflow** [comment]
i changed it to MA and the cmd is still blank, not rolling or anything just blank

**Comment by vivinano** [comment]
what is in your channeldata folder ?

**Comment by clovdystackflow** [comment]
there's nothing, just explain.md

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/158002196-94d86fa4-45c3-45b2-b971-0b7b6185e1e0.png)


does channel data look like this ?

**Comment by clovdystackflow** [comment]
i have the latest discum version, but my channeldata has nothing on it

**Comment by vivinano** [comment]
channel data is populated upon finding a instance of $settings in mudae

**Comment by clovdystackflow** [comment]
i did do $settings in the channel however nothing appeared in channeldata

**Comment by vivinano** [comment]
Did $settings trigger mudae to post the settings message ?
