### ISSUE TITLE
setting claim_delay and kak_delay not working

### ISSUE THREAD

**Issue by fookbuck** [vivinano/MudaeAutoBot#145]
as title say, setting `claim_delay` and `kak_delay` not working
after i look at the code, it didnt even use `claim_delay` or `kak_delay` but use `claim_snipe` and `kak_snipe` instead

**Comment by vivinano** [comment]
Yea kak delay and snipe_delay was deprecated to just be used in when channeldata isn’t set you can change the number instance in channeldata and that will change the snipe times

**Comment by fookbuck** [comment]
thank you for reply, i just forgot it was only works for the one without channeldata

**Comment by vivinano** [comment]
Yes sorry about that the snipe_delays based on channel was better for multi server instances so it was overall the better option but wanted to leave the old option if needed
