### ISSUE TITLE
Could not find channel

### ISSUE THREAD

**Issue by iklayx** [vivinano/MudaeAutoBot#146]
Hi, when I run the code It say Could not find a channel.
 It will be appreciated if you replayed
![image](https://user-images.githubusercontent.com/68993593/157553019-2bf05cd9-20dc-4dc2-80ee-d141955bf18d.png)

**Comment by vivinano** [comment]
Channeldata instance was not found in the specified channels

**Comment by iklayx** [comment]
what can I do?

**Comment by iklayx** [comment]
What can I do for it to work. Anything

**Comment by iklayx** [comment]
how do I know?

**Comment by iklayx** [comment]
discum 1.4.0

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/158001696-08349dc0-efc2-4aca-be10-4094bd63028a.png)

this is what a instance of channel data should look like

**Comment by iklayx** [comment]
hello

**Comment by iklayx** [comment]
I have nothing in channel data, the problem is from discum or something else ?
![image](https://user-images.githubusercontent.com/68993593/158017213-f39d2ab5-2909-470d-b25f-05d2ba094ec3.png)

**Comment by vivinano** [comment]
does your channel have a $setting instance to find ?

**Comment by iklayx** [comment]
No, it does not have

**Comment by vivinano** [comment]
Then that might be the issue as it's locking up trying to find $settings 
Either populate one manually or make a $setting command to mudae and let the app parse it

**Comment by iklayx** [comment]
nothing happened

**Comment by vivinano** [comment]
Is it named correctly ? It has to follow the correct naming function to parse correctly

**Comment by iklayx** [comment]
I just realized I'm stupid  I was putting the wrong token, now its working fine, sorry for wasting your time

**Comment by iklayx** [comment]
but I have a problem, it automatically  claim the first roll
 a character that I don't want

**Comment by haseebUm2965** [comment]
> I just realized I'm stupid I was putting the wrong token, now its working fine, sorry for wasting your time

how did you find the correct token i am having the same issue

**Comment by iklayx** [comment]
> > I just realized I'm stupid I was putting the wrong token, now its working fine, sorry for wasting your time
> 
> how did you find the correct token i am having the same issue

just search on google it will teach you how to get it 
search this : how to get discord token

**Comment by iklayx** [comment]
> but I have a problem, it automatically claim the first roll a character that I don't want

@vivinano

**Comment by vivinano** [comment]
Check if last minute claim is on as that will claim a character based on kak during your last roll cycle

**Comment by iklayx** [comment]
sorry i didn't understand but this what i have
![image](https://user-images.githubusercontent.com/68993593/158496677-3f171f1c-e9c6-40aa-a742-eea52f31d2d3.png)
 what changes do I have to make?

**Comment by vivinano** [comment]
last claim True enables claiming during your last claim cycle before reset

last claim min - is during the start of the last hour (60 min) claim something

min_kak_last_min - Claim a char that is > 10 during that last cycle

**Comment by iklayx** [comment]
now what I have to do for it to work, sorry I didn't understand

**Comment by vivinano** [comment]
please read the `read me` as it is there to explain the settings of the `Last minute claim window` but based on the current settings the  "automatically claim the first roll a character that I don't want" was intended

**Comment by iklayx** [comment]
I want him to claim just the characters in my name list

**Comment by iklayx** [comment]
I did adjust the settings it working now, thx for your time
