### ISSUE TITLE
... no response?

### ISSUE THREAD

**Issue by Sczptor** [vivinano/MudaeAutoBot#148]
When running the bot, nothing happens. My settings are configured correctly and there are no errors that are coming back, I have rolled and I've waited for almost 2 hours now... yet nothing has happened. 

Am i missing something?

**Comment by vivinano** [comment]
A lot of users are having token issues so check that

**Comment by Sczptor** [comment]
My user token matchers perfectly. What exactly am I checking?

**Comment by vivinano** [comment]
okay so is it not claiming ? or is it not rolling ??

**Comment by Sczptor** [comment]
It's not doing anything. No claims, no rolls, no reactions, no output on command prompt, no error. It's impossible to tell what the issue is.

**Comment by Sczptor** [comment]
> 

Do you have a discord I can message you on?

**Comment by vivinano** [comment]
I keep my discord for personal use and GitHub separate

**Comment by Sczptor** [comment]
> 

Alright, I've tried for the past 2 days and it's still not working. The user token is completely fine and works perfectly but nothing is happening in command prompt.

**Comment by vivinano** [comment]
It seems like a user try just doing a small test app with the same token and see if it does a login comment prompt

**Comment by Sczptor** [comment]
Managed to fiddle around and got it semi-working.

`  File "MudaeAutoBot.py", line 719, in on_message
    msg = get_server_settings(gid,matched_channel)
  File "MudaeAutoBot.py", line 188, in get_server_settings
    · Prefix: **{settings_hope_prefix}** ($prefix)
UnboundLocalError: local variable 'settings_hope_prefix' referenced before assignment`

I've got this issue now though...

**Comment by vivinano** [comment]
So there no channeldata so it tried to find a message in where the bot user has rolled since it's not finding anything the rolling variable is never set so it errors

**Comment by Sczptor** [comment]
Not sure why it didn't find my first couple of rolls. I rolled again and everything seems to work, thank you for the help.
