### ISSUE TITLE
Bot tried to claim twice 

### ISSUE THREAD

**Issue by kirk33120** [vivinano/MudaeAutoBot#149]
Basically bot tried to claim twice when attempting last min claim.
oh! and add cross platform as feature works well with termux
![image](https://user-images.githubusercontent.com/73415707/158495497-8597a0c6-5166-446f-87c0-437a49b40b98.png)

**Comment by vivinano** [comment]
The attempt will post on the screen as 2 things will appear but the secondary code for the check will stop from posting 2 emojis only The first one will get added 


Also explain cross platform? Cause it should work on Linux
