### ISSUE TITLE
Limited version reacting to mudae messages outside of specified channelid and multiid

### ISSUE THREAD

**Issue by RecentYogurt** [vivinano/MudaeAutoBot#15]
I set channel id to only 1 channel, yet it's reacting to commands in other ones

**Comment by vivinano** [comment]
the message.support might not be limited is it refering to characters ?

**Comment by RecentYogurt** [comment]
I'll wait for you because I have no idea how 🤣

**Comment by RecentYogurt** [comment]
I was also wondering can the claim delay be set to decimal values or is it integer so whole numbers only

**Comment by vivinano** [comment]
someone tested that and says it can but unsure how that works with time.sleep() vs asyncio.sleep()

**Comment by vivinano** [comment]
since moving to new discum gonna close this issue
