### ISSUE TITLE
Option to snipe people's wishes?

### ISSUE THREAD

**Issue by Sczptor** [vivinano/MudaeAutoBot#150]

**Comment by kirk33120** [comment]
the bot could snipe any characters lmao

**Comment by Sczptor** [comment]
> the bot could snipe any characters lmao

right but, specifically people's wishes? so that you don't have to specify each character

**Comment by vivinano** [comment]
In previous versions it did snipe wishes but due to angry non-bot users I nerfed wish sniping to self only

**Comment by Sczptor** [comment]
would it be possible to get the code from that version?

**Comment by vivinano** [comment]
If there is enough users asking I will implement it back into the code but due to various complaints I got from personal use I did change up the wish sniping

**Comment by kirk33120** [comment]
oh I would that feature to be back :D

**Comment by aspectlostx** [comment]
god yes ^ i'd love to be able to do this

**Comment by vivinano** [comment]
well i guess there is some need for this feature. even though It might get people banned from salt ?

**Comment by vivinano** [comment]
so in line 514 `if str(user['id']) in content:` you can edit that to change the way wish sniping works

to avoid just giving out the code I can say is if you find something that is common among all wishes then you can add that in the line and you will be able to snipe other peoples wishes

with that I shall close
