### ISSUE TITLE
Slash rolling not working [Fixed]

### ISSUE THREAD

**Issue by Qearlax** [vivinano/MudaeAutoBot#151]
Hello I am using the bot it helped me so many times so I thank you a lot of making this but I didn't managed to get slash rolling working I am putting the channel ID as `slash_id `and Server ID as `slash_guild_id` but it just not rolling and on the console it shows me blank screen but if someone rolls a char that I want it snipes it but just not rolling with slash commands btw normal rolling works fine but I want that extra %10 and %5 chances.

**Comment by vivinano** [comment]
There was a recent release to fix slash rolling if you didn't download the latest changes 

As for which is which I think my read me lists them and what goes in which

**Comment by Qearlax** [comment]
I already read everything but it just not working for some reason I am trying on different servers too but sadly not working and I downloaded most newest version which you published 15 days ago

**Comment by vivinano** [comment]
Alright so guild id are the server that it is in and it must have a match 

So example 

If server 1 it must match with server 1 Channel 1 


[sever1 , sever1 , server 2]

[sever 1 channel 1 , server 1 channel 2 , server 2 channel 1]

**Comment by Qearlax** [comment]
I am sorry but I didn't understand I don't know how these things are working so I need your help again 😕 
So to put correct ids should I do like this?
```
   "channel_ids":[
      111111111111111111 > The channel we playing mudae
   ],
   "slash_ids":[
      111111111111111111 > The channel that i want to use slash rolling
   ],
   "slash_guild_ids":[
      222222222222222222 > The server that my bot is in
   ],
```
And if i understand correctly im sorry if i didn't so slashid+channelid must match with each other and they need to match with guildid right but the problem is even if they match still bot is not rolling with slash 😢

**Comment by vivinano** [comment]
The guild id must be the id of the server the channel resides in 


Also side note that mudae must also be set to take slash interactions 
ie I have slash commands turned off on my server so slash commands will not work

**Comment by Qearlax** [comment]
Slash commands are enabled but still i just can't do it please show me a way that i can understand cuz im gonna lose my mind while trying to make this to work :(

**Comment by Qearlax** [comment]
```
   "channel_ids":[
      857565456465456415
   ],
   "slash_ids":[
      857565456465456415
   ],
   "slash_guild_ids":[
      901654564654564154
   ],
   
```
   I created a test server and these are the ids what am i doing wrong?

**Comment by Qearlax** [comment]
I also found a weird issue if i put nothing on `"channel_ids":[1],` like this but if i put the actual channel id on `"slash_ids":[857565456465456415],` it says could not found this channel ¯\_(ツ)_/¯ imma lose my mind and i'm really sorry if i look like a dumb rn

**Comment by vivinano** [comment]
There should also be a safety code to not slash roll and normal roll at the same time

**Comment by Qearlax** [comment]
Okay i solved the problem by doing this i installed git bash and installed discum with that way and when i tried it worked lol

**Comment by vivinano** [comment]
ah yes discum had some changes with their code which enabled slash rolling again.

currently their code for slash get it broken which it what my change 23 days ago was for to implement the code again in my own way to allow it to work

**Comment by Qearlax** [comment]
Okay everything is working right now but now i want to use custom emoji and i didn't found the line for (custom emoji only) i mean there is nothing the uncomment there is something on 658 but idk what is that for

**Comment by kirk33120** [comment]
I met with this problem
![Screenshot_20220322-003751~2](https://user-images.githubusercontent.com/73415707/159311885-c26f57c7-5c53-4fdc-8f9c-8b77e576dab2.png)

**Comment by vivinano** [comment]
if slashget is not obtaining anythign which is why your getting the error

**Comment by kirk33120** [comment]
idk either everything is there, I tried it on my 2 server works perfectly well but except this server which is not mine has to do with perms?

**Comment by vivinano** [comment]
The server might not have permissions set to enable slash commands try to do slash commands normally

**Comment by kirk33120** [comment]
tried to do it normally it works normally

**Comment by vivinano** [comment]
have you updated both discum and my repo ?

**Comment by kirk33120** [comment]
slr oh! maybe thats the problem

**Comment by vivinano** [comment]
Did you update both the discum repo and mine ?
