### ISSUE TITLE
load settings

### ISSUE THREAD

**Issue by HentaiRyuu** [vivinano/MudaeAutoBot#152]
Is it possible to read channeldata before it start to read recieve msg?

because, if server is in flood or someone is rolling, bot wont start and throw this error
```
;ERROR;Could not find settings for 123456789, please trigger the '$settings' command in the server and run the bot again.
```
 then I need to restart and hope someone is not rolling when I run bot

**Comment by vivinano** [comment]
The thing is that is does as the bot must receive a ready signal first. This is why I added persistent data option as I was against keeping any type of persistent data. Once the bot grabs data once it’s should be good for the rest
