### ISSUE TITLE
Why's it claiming everything?

### ISSUE THREAD

**Issue by aspectlostx** [vivinano/MudaeAutoBot#153]
Hello! Ive been using snipers for a while now but for some reason cannot figure out why it was sniping every roll?
Here's my settings

(Highly doubt its the series list, ive had it blank before as well but if it is correct me...)

![image](https://user-images.githubusercontent.com/102907856/161428624-041b2a75-1f17-413c-af78-b4faf5b514a2.png)

![image](https://user-images.githubusercontent.com/102907856/161428632-d7a971f5-c8a6-4131-9a20-ec7c76187c69.png)

It claiming random things
![image](https://user-images.githubusercontent.com/102907856/161428702-5162a45c-42dd-44de-8794-4026a42c041b.png)

Once i get an answer or it fixed feel free to delete this. I just dont know how to contact you but this! Thank you

**Comment by vivinano** [comment]
Series list contains “1” which means that any time the like rank or the claim rank contains a 1 it should snipe that character

**Comment by aspectlostx** [comment]
@vivinano Shall I then leave it blank like " " with nothing between or delete the quotation marks separately
