### ISSUE TITLE
Settings_Mudae.json not found

### ISSUE THREAD

**Issue by DargonGamers** [vivinano/MudaeAutoBot#155]
I installed discum but whenever I launch "MudaeAutoBot.py" I get a prompt saying "there is no such file or directory "Settings_Mudae.json"" any clue why?
![unknown](https://user-images.githubusercontent.com/103198632/162217211-d1bb9061-b13f-4df9-ba78-6e7ceb1237d0.jpg)

**Comment by vivinano** [comment]
Personally hate windows store version and even when you attempt to install the standalone version windows just loves to force you to use their windows store version

**Comment by DargonGamers** [comment]
> If you're sure that the settings file is in that same folder and is named correctly, try opening a terminal/command prompt in that folder (shift right click in the folder, click "open in terminal" or "open in command window" depending on your OS) and run the script with the command "python MudaeAutoBot.py"
> 
> I use the windows store version of python on windows 11 and it works fine for me this way.

I opened the file in a command window and whenever I run the script the whole thing just freezes. I press enter after entering "python MudaeAutoBot.py" and nothing happens afterwards and the prompt takes no inputs.

**Comment by DargonGamers** [comment]
Also yes I did have a standalone version of python but windows forced the windows store one.

**Comment by tsumeone** [comment]
Make sure you have Discum installed (I recommend you install git and then install Discum using the command on their GitHub page readme).  If you have Discum installed, make sure you entered your login token in the top of the settings file.
