### ISSUE TITLE
Can't run script, giving errors

### ISSUE THREAD

**Issue by undercovernormie** [vivinano/MudaeAutoBot#157]
Getting these errors, been fiddling all night. Any help? It says it expected a comma? Looked through other Issues and found one similar but I can't get it to work. Have Python 3.9, discum installed, Settings_Mudae.json validated.
![cmd_2022-04-14_02-31-34](https://user-images.githubusercontent.com/85839915/163328496-d161ea54-0831-45dc-ac0c-bf02af5a3c0a.png)

**Comment by vivinano** [comment]
Seems like it’s not finding a json file so ensure the settings json is able to be seen by the script
