### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by borisalmonacid** [vivinano/MudaeAutoBot#158]
How can I check if the connection is successful?
the console does not give me information if it has been connected or not.

This query comes to me why I have the suspicion that this line has exchanged the slash_ids with the channel_ids? because when printing that value it indicates the slash_ids.
_channelid = m['channel_id']_
_if int(channelid) not in mhids:_

**Comment by vivinano** [comment]
You can turn the discum log to true and then it will print all the Gateway stuff
