### ISSUE TITLE
Feature roll_without_claim

### ISSUE THREAD

**Issue by borisalmonacid** [vivinano/MudaeAutoBot#159]
Add the option in the json of roll_without_claim : True/False,
this option allows not to roll in the event that one does not have the option to claim.

Regards
BA

**Comment by vivinano** [comment]
Personally I used the bot more of obtain more `Keys` for my Married characters and possible `Kakera Reacts` while not against this feature testing this would be a long process that would take alot of my free time for a feature I wouldn't use myself
