### ISSUE TITLE
Bot just rolling nonstop

### ISSUE THREAD

**Issue by seriaati** [vivinano/MudaeAutoBot#16]
I'm not sure if this is caused by game mode 2 or not... but the bot keeps on rolling even though mudae tells me that I can only roll 8.

**Comment by vivinano** [comment]
Yeah That cause it’s set at 15 right now In the code since it’s not dynamically set big sad about that personally but just change the amount in the code sorry about that I was more focus on discum conversion since discord.py is moving away from user bots

**Comment by seriaati** [comment]
I fixed it its fine
edited the python file

**Comment by vivinano** [comment]
yeah im trying to get back to a dynamic generated roll system so i dont have to code for each case
