### ISSUE TITLE
How to cofigure the settings .json

### ISSUE THREAD

**Issue by CarIosLopez** [vivinano/MudaeAutoBot#161]
If I want to claim characters upper than 900(because I got a 900 int in **min_kak**, one character of 1200 kak appears and the bot didn't react)

**Comment by vivinano** [comment]
pictures ? and what the cmd printed at the time

**Comment by CarIosLopez** [comment]
I forgot to take a picture but the terminal mentioned something like: someone rolled a 1200 kakera character

Right now I have this issue, sometimes appear, do you know about for what?
![image](https://user-images.githubusercontent.com/99137947/165240412-3d6e335f-78ae-4baf-84cf-c2ae1f3d1f64.png)

**Comment by vivinano** [comment]
Yes that means you don’t have channeldata file present for persistent data which could be why you couldn’t snipe the character

**Comment by vivinano** [comment]
for fix just trigger a $setting command on mudae and copy and paste those settings manully or let the bot try to obtain the settings automatically but you still will have to manually trigger the command
