### ISSUE TITLE
Bot claim wrong series

### ISSUE THREAD

**Issue by HentaiRyuu** [vivinano/MudaeAutoBot#162]
I saw this happen for a while now.

Setting:
```
"series_list":[
	"Nekopara",
	"Nekoparaiten"
]
```

From Log:
`Sage (NP) from Nekopara appeared attempting to snipe in 123456789123456789`

Image:
![image](https://user-images.githubusercontent.com/26791163/165646771-cbd4384f-2965-4561-b101-bc9a2f83ad78.png)

**Comment by vivinano** [comment]
It makes sense as nekopara is in that title
