### ISSUE TITLE
Could not find settings

### ISSUE THREAD

**Issue by Equ1no0x** [vivinano/MudaeAutoBot#167]
So I've managed to avoid the 'user' error by just using an older version of this selfbot and Discum, but I've been stuck with this error message ever since:

![image](https://user-images.githubusercontent.com/77862920/169367220-a9da9cc2-5f04-43dc-ab8f-3a3ce68b8dcb.png)

Any idea what could be causing it? I've used the command multiple times and tested it in different channels.

I'm currently using v4 from the bot and Discum 1.3.1

**Comment by vivinano** [comment]
the older version of the bot didn't have persistence built in so it tries to pull a live setting and sometimes it will error out if the channel is to busy to do a search on

**Comment by Equ1no0x** [comment]
> the older version of the bot didn't have persistence built-in so it tries to pull a live setting and sometimes it will error out if the channel is too busy to do a search on

Is there maybe a way to jerry-rig a fix for this by modifying the python script for this version? Or maybe you can point me to the section where this was fixed on current so I can compare and try and see if it works. I don't want to be wasting your time on a fix on an older version.

**Comment by vivinano** [comment]
There is you can just do a diff check and add the persistence in the get setting function

**Comment by aspectlostx** [comment]
Should just fix the user error by removing servers you do not need anymore and return to the new version of the bot. That's my opinion however, the fix worked for several people!

**Comment by Equ1no0x** [comment]
> Should just fix the user error by removing servers you do not need anymore and return to the new version of the bot. That's my opinion however, the fix worked for several people!

I have seen that this worked for some people, but I don't really want to start leaving servers randomly just to see if it will work, especially when that issue is apparently a problem with discum itself. I do use most of the servers I'm in here and there.

**Comment by vivinano** [comment]
Yeah it fine to use a older version of mudae auto bot that is why they are there ultimately the issue comes from the developer of discum taking a break so maybe some changes were made that broke a few things 

But as for support for my repo I'll offer assistance within reason

**Comment by Equ1no0x** [comment]
> Yeah it fine to use a older version of mudae auto bot that is why they are there ultimately the issue comes from the developer of discum taking a break so maybe some changes were made that broke a few things
> 
> But as for support for my repo I'll offer assistance within reason

Totally understandable, thanks for taking the time to reply!
