### ISSUE TITLE
Doesnt want to start 

### ISSUE THREAD

**Issue by Artborne** [vivinano/MudaeAutoBot#169]
After starting MudaeAutoBot.py there is nothing happening in terminal 
![grafik](https://user-images.githubusercontent.com/105830865/169678123-8d147006-5fe5-413e-8433-941025b0241c.png)

**Comment by vivinano** [comment]
turn console logging on in the code and you will see if there is an issue there

**Comment by Artborne** [comment]
Thank you it was long text i think was token misstake i fixed it it works but for somereason after start it claimed 2 times randomly 
![grafik](https://user-images.githubusercontent.com/105830865/169695620-00979575-a8bf-4541-a2da-1541c04512cd.png)

**Comment by Artborne** [comment]
oh okay i was looking at claim part a little i think issue was in not havving anything in series list , i put "0" will it work fine or should i change to something else ?

**Comment by vivinano** [comment]
No 0 will not work as anything with 0 in it will be claimed

**Comment by Artborne** [comment]
> 

seemed to work fine , i changed to some random text tho thank you for help :)
