### ISSUE TITLE
hmm the py window opens up for 0.1 second and closes by itself, is that normal?

### ISSUE THREAD

**Issue by seriaati** [vivinano/MudaeAutoBot#17]
^^
when I launch "Discum_MudaeAutoBot.py" the window closes by itself.
also thank you very much for working on this project, really appreaciate it

**Comment by RecentYogurt** [comment]
![image](https://user-images.githubusercontent.com/83528449/117558575-72285a80-b033-11eb-8eb8-e3a63971e1bf.png)
despite discum being already installed

**Comment by RecentYogurt** [comment]
also you should add discum to the requirements in the readme

**Comment by vivinano** [comment]
uh it might be the version of discum 
if you installed thru regular pip then it might be outdated ? 

> ![image](https://user-images.githubusercontent.com/33008397/117558629-08b54580-b04d-11eb-9d10-8781721c80e6.png)


ill add it to the readme now

**Comment by RecentYogurt** [comment]
i tried it again after installing it the way you sent but it still has the same error

**Comment by vivinano** [comment]
u using python3 ? or python ? and it was working for you yesterday ? it just the message portion added on with all the other functions.

**Comment by RecentYogurt** [comment]
I'm using python 3.9. The legacy version was working when I double click on the discum_message_support.py and it opens in command prompt but when I try to run it through IDLE it has the same error as the new version

**Comment by vivinano** [comment]
Do pip3 install ? I’m not sure it’s working for me without the module missing issue so it might have to search up a way nothing has changed between the legacy version it’s just adding a few more modules

**Comment by seriaati** [comment]
oh ok ok it was my problem i forgot to do pip install discum
after i did that the window opens correctly and has tons of green texts lmao

**Comment by RecentYogurt** [comment]
oh okay i figured out what it was. I think i accidentally deleted a comma after one of the lines. This fixed the issue but idk why python was saying that the issue was with calling discum

**Comment by vivinano** [comment]
Yeah sometimes that happens can’t always trust errors fully and gotta find out the issues that could lead to the main problem

**Comment by RecentYogurt** [comment]
I just realized that even though I have rolling set to false in settings.json the bot rolls anyway. Not a huge issue but something I noticed

**Comment by vivinano** [comment]
I havent implemented that in the code so right now its just rolls on start if you want you can set 
it on the bottom b4 the start just put the 

.start() commands within a if statement and set those to if settings[roll] == "True" 

but yeah i spent most of the day just getting base function converted all that stuff is more fine tuning

**Comment by vivinano** [comment]
closing as main "title" issue has been resolved
