### ISSUE TITLE
slow claim

### ISSUE THREAD

**Issue by Tachayang** [vivinano/MudaeAutoBot#171]
i've optimized my setting to be as fast as possible but there's still a second delay between when the bot detects roll and claims any fix?
![image_2022-05-29_072315555](https://user-images.githubusercontent.com/106417747/170846874-b92a7d92-a5e3-421a-a791-ce885edc5eca.png)
![image_2022-05-29_072153612](https://user-images.githubusercontent.com/106417747/170846842-cc7ceab2-6e65-411c-9a50-f2ff96a11abb.png)
![image_2022-05-29_072222734](https://user-images.githubusercontent.com/106417747/170846851-48a57652-6a41-4566-8b5e-2a53c1b996ac.png)

_Originally posted by @Tachayang in https://github.com/vivinano/MudaeAutoBot/issues/74#issuecomment-1140349166_

**Comment by vivinano** [comment]
there has to be a slight delay to give time for discord's api to reconqinze that a embed is react-able 

then there delay that is casued by connection to the api itself
