### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by BeyBAN** [vivinano/MudaeAutoBot#173]
### I would be very grateful if you could teach me.

**I have installed the python version 3.9.0 required for Discum.
I downloaded Discum 1.4.0 and M_Auto_v4 files
I have no idea what to do with the rest...**

### There may be typos as I am using the translation.

**Comment by BeyBAN** [comment]
**+) I made the necessary adjustments to the Settings_Mudae.json file**

**Comment by BeyBAN** [comment]
![image](https://user-images.githubusercontent.com/106929612/172112274-55e0b21b-caa6-4bc9-8fcc-74d5be2df708.png)

is it currently operational?

**Comment by BeyBAN** [comment]
![image](https://user-images.githubusercontent.com/106929612/172117730-c0db3c04-5344-4792-b598-78653ba0a152.png)

Doesn't work even though I made "settings"

**+ error applies to subheadings**
![image](https://user-images.githubusercontent.com/106929612/172117885-d060e9e2-12d4-4f0c-bb25-12c59a034206.png)

**Comment by vivinano** [comment]
No it should first get settings from a file or a default setting

**Comment by vivinano** [comment]
Unsure what you mean ?

**Comment by BeyBAN** [comment]
What could be causing the problem? i think i tried all the ways

**Comment by vivinano** [comment]
So if you updated settings_mudae then you also have to have a channel data instance

**Comment by BeyBAN** [comment]
dude i really don't understand i have messed up parts that are working i really need this can you teach me how to install from scratch :( you're free to treat me like a fool

**Comment by vivinano** [comment]
Add the necessary bold symbols where they belong so that it can be parsed correctly

**Comment by BeyBAN** [comment]
![image](https://user-images.githubusercontent.com/106929612/172409980-301a5d50-4596-411c-88aa-b5485651b46e.png)
Is it true that I opened a new document and wrote it this way?

**Comment by vivinano** [comment]
Seems correct , is it existing error code or a new one ? And it seems like your channel doesn't exist to the user or you misconfigured something

**Comment by BeyBAN** [comment]
current error code. I have no idea what's wrong... why does it give an error in sub-titles when working on normal channels

**Let me explain to you what I've done so that we can conclude the matter. First I downloaded the file and opened it with python. Then I installed discum to fix the errors and made the necessary adjustments for Settings_Mudae.json as follows:**

![image](https://user-images.githubusercontent.com/106929612/172417296-8c3315ad-f13a-4ee1-8e2e-cfc0b9ba9b5d.png)

**+ in addition, there is a 3 second delay between detecting and receiving kakera, why is this?**
![image](https://user-images.githubusercontent.com/106929612/172418131-e3daf77f-2beb-4240-aced-4cb3d23069fa.png)

**going back to what i did, i ran the bot and found it working fine on normal channels (applies to rolls, pokerolls)**
![image](https://user-images.githubusercontent.com/106929612/172419258-78f00459-3d83-4b7e-8c81-190274076ae9.png)

**Is there something missing in the Python content?**

**Comment by vivinano** [comment]
There are delays because in a perfect world therewould be none but you are still sending a command to an API so there various factors that come into play like network speed or network traffic 

Ping as you will in terms of games

**Comment by BeyBAN** [comment]
that's not our main problem
If I'm the only one with the problem, can you tell me where I went wrong?

**Comment by vivinano** [comment]
No one is reporting any issue with the bot not working

**Comment by vivinano** [comment]
Hmm so threads are working I thought I had to make actually code edits 

But yeah currently discum broke with slash rolling I made a fix on my end to the discum files but that a different monster and technically outside the scope of my bot but 

If you need slash rolling to work that might be an option

**Comment by BeyBAN** [comment]
@HentaiRyuu **Bro, because I use translation, there may be word mistakes, I said it at first.**
i mean sub channels
![image](https://user-images.githubusercontent.com/106929612/172559162-321c5173-e4b8-4730-a1bd-d2587cac5694.png)

What's the point if I can't use it on the other three channels?
**do you mean "thread" these channels**

**Comment by BeyBAN** [comment]
i know i'm wasting your time i'm sorry but i need to figure this out

**Comment by HentaiRyuu** [comment]
in case you don't know, that sub channel you talking about is called "thread" on discord
![image](https://user-images.githubusercontent.com/26791163/172602350-1b16b30d-c537-47fc-bc06-bfab3ed9f065.png)

**Comment by vivinano** [comment]
It would depend on when you need that message to trigger
