### ISSUE TITLE
Suggestion: Random wait time option for rolling

### ISSUE THREAD

**Issue by strongtaste57** [vivinano/MudaeAutoBot#176]
It can be suspicious if an account always rolls at the exact same time. Would be useful if there was an option in the settings to set a range of minutes the bot will randomly chose from, and add that to the time it takes to start rolling.

**Comment by vivinano** [comment]
You can add a random feature it’s pretty simple just add random in the Waifu roll definition

**Comment by strongtaste57** [comment]
Thanks, I managed to do it. How about an option to turn off rolling when the account doesn't have a claim available? I don't think I can add that easily.

**Comment by strongtaste57** [comment]
Also a way to stop claim attempts if the account doesn't have a claim. Been using the bot and it works great btw.

**Comment by vivinano** [comment]
The bot should not claim if the bot doesn't have claim attempts the only time the bot will claim without a claim attempt is when you launch it and that flag hasn't been set already

**Comment by vivinano** [comment]
> Thanks, I managed to do it. How about an option to turn off rolling when the account doesn't have a claim available? I don't think I can add that easily.

In terms of stop rolling I didn't implement it because I use the bot more for key rolling hence if I lose out on a character because I didn't have a claim I have accepted this risk 

If you want to implement it you would have to learn about threads 
A way to kill that specific thread and a way to relaunch the thread 

Or implement a way in the thread to do stop

**Comment by vivinano** [comment]
Going to close this suggestion

Not going to implement as already have to deal with questions of is the bot working when the bot is like a minute late 

Avoiding this due to not wanting an increase in "issue" post
