### ISSUE TITLE
Problem with custom reactions

### ISSUE THREAD

**Issue by D4rknxss** [vivinano/MudaeAutoBot#178]
Hello, I have a small problem in my discord server, we added several custom reactions and when the bot must take a character it bugs and it displays this 
![unknown](https://user-images.githubusercontent.com/107949493/174865184-f4f06b32-16f7-48d3-a7ac-a2c6450e6522.png)

**Comment by vivinano** [comment]
Well that would be inproper way to add reactions as you can see how the error message you just passed it 14 arguments when it is only expecting 4

**Comment by D4rknxss** [comment]
> Well that would be inproper way to add reactions as you can see how the error message you just passed it 14 arguments when it is only expecting 4

So the bot can only accept a maximum of 4 custom reactions if I understand correctly ?

**Comment by vivinano** [comment]
No the in that area of the code it just send the one emoji that is set any other emoji just overloads the method 

If you want to add more than 1 custom emoji then you need to add more logic statements then just added them on the the send_emoji function

**Comment by D4rknxss** [comment]
> 



> No the in that area of the code it just send the one emoji that is set any other emoji just overloads the method
> 
> If you want to add more than 1 custom emoji then you need to add more logic statements then just added them on the the send_emoji function

Can you show an example if possible please 
![image](https://user-images.githubusercontent.com/107949493/174876530-7a6189b4-48df-490d-b105-9be3377d8aa2.png)

**Comment by vivinano** [comment]
Showing a example in this case would be technically coding that interactive but how you would want to do it would be 

Do an if statement to check if the count of arguments excedd 1 and then if it does then do a random selection 

Personally I do not understand why this is needed as the code already functions in a way to detect the emoji that is present on the character and react accordingly

**Comment by D4rknxss** [comment]
okk I see, but sometimes when I look at the rolls the bot reacts with the heart instead of the emote that appears on the card 
![image](https://user-images.githubusercontent.com/107949493/175427104-26ce270c-83de-4d93-9b79-205c71303159.png)
![image](https://user-images.githubusercontent.com/107949493/175427475-33003cc4-a3e6-4535-a544-ff1bb7317c8d.png)
how to fix it

**Comment by vivinano** [comment]
There might be issue with delays and timings if it goes to fast it reacts with the heart as it doesn’t detect the other emoji being added

**Comment by D4rknxss** [comment]
> 

thanks, I finally solved the problem, it's just that I had set the time sleep to .0 btw I have a question about the json settings what is the best claim delay so that it's fast enough to snipe but not too fast either?

**Comment by vivinano** [comment]
it depends on various factors some out of your control

**Comment by vivinano** [comment]
That depends 

As you computer will first have to process the code > make a request to the api > send that request thru the internet > arrives at discord it says okay sure 

So you can only really control at that first level every thing else in between and the end is out of your control
