### ISSUE TITLE
Getting an Index Error :/

### ISSUE THREAD

**Issue by CADIndie** [vivinano/MudaeAutoBot#180]
```cmd
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\discum\gateway\gateway.py", line 296, in _response_loop
    func(resp)
  File "C:\Users\CADIndie\Downloads\MudaeAutoBot-main\MudaeAutoBot-main\MudaeAutoBot.py", line 764, in on_message
    c_settings = parse_settings_message(msg)
  File "C:\Users\CADIndie\Downloads\MudaeAutoBot-main\MudaeAutoBot-main\MudaeAutoBot.py", line 226, in parse_settings_message
    settings['prefix'] = val_parse(settings_p[0])[0]
IndexError: list index out of range
```
Not really sure the reason, also a note that it says it cant find the channel but then proceeds to say it cant find the settings for the channel after I input any command in said channel.

**Comment by TikaUnas** [comment]
I was having the same issue, especially the part about the settings thing. Except my error was just a bit different than yours. It's been working fine for a while this just started today.


Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000025C0A3EB500>>
Traceback (most recent call last):
  File "C:\Users\shaho\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "D:\Users\shaho\Documents\demon time\bot\MudaeAutoBot.py", line 707, in on_message
    user = bot.gateway.session.user
  File "C:\Users\shaho\AppData\Roaming\Python\Python39\site-packages\discum\gateway\session.py", line 42, in user
    return self.settings_ready['user']
KeyError: 'user'

**Comment by CADIndie** [comment]
Discum getting updated (or broken) maybe?

**Comment by CADIndie** [comment]
I do Java/C++ lol, only time I ever use Python is for Renpy which is about 10 times a year at most. AKA I don't understand python really at all other than programming it

**Comment by vivinano** [comment]
It's basically index error in other languages

**Comment by vivinano** [comment]
It should be your channel data instance doesn't have the bold "*" which makes it fails the regex

**Comment by CADIndie** [comment]
What do you mean? That kind of confused me lol

**Comment by vivinano** [comment]
It doesn't fit the regular expression so it is unable to large the value

**Comment by CADIndie** [comment]
uh, I don't see how that would only affect me as its mudae wide and not just my own bot that changes it

**Comment by vivinano** [comment]
Reading the error message it is issues with getting the prefix which is the first thing that is parsed

**Comment by vivinano** [comment]
Basically gonna close issue as haven't heard a response 


This issue was a copy and paste issue due to copy not including the bold * marks it fails the regular expression used to parse the setting file so the $ prefix want obtained *based on default * set up

**Comment by siddagra** [comment]
> It should be your channel data instance doesn't have the bold "*" which makes it fails the regex

what do u even mean by this?

**Comment by siddagra** [comment]
U say about bold marks or something but it really makes no sense what u are even really talking about and you also don't have a tutorial in the readme to set it up.
