### ISSUE TITLE
When trying to start the bot, the file "Settings_Mudae.json" is not found.

### ISSUE THREAD

**Issue by Bbfreuniao** [vivinano/MudaeAutoBot#184]
When I try to start MudaeAutoBot.py, the screen below flashes quickly and then closes, even though I'm pretty sure there's no syntax error as I haven't changed anything after downloading 'main'. No ideia what to do.

![image](https://user-images.githubusercontent.com/109085408/178278919-ae34136b-25d0-42ac-8c18-2a716b35a417.png)

**Comment by Bbfreuniao** [comment]
Sorry, I didn't understand. What does that mean? What exactly could I do to fix it?

**Comment by vivinano** [comment]
No as this falls into the realm of the environment issue which is specific to each person so it will end up ultimately in a long thread going back and forth for a long time
