### ISSUE TITLE
help

### ISSUE THREAD

**Issue by CriticalMomento** [vivinano/MudaeAutoBot#185]
yea so like i have python installed but for some reason its not running.

**Comment by CriticalMomento** [comment]
ok lol after some stuff i got to this point 
![image](https://user-images.githubusercontent.com/74601249/178652054-b4377cad-5452-49f6-ba54-7d8a199eaa0a.png)

**Comment by CriticalMomento** [comment]
how i got into settings json and see that this is like the only error and idk how to fix 
![image](https://user-images.githubusercontent.com/74601249/178656215-29706bc2-ebcb-4b68-93ab-96bdd57402a8.png)

**Comment by CriticalMomento** [comment]
ok i was able to get past that problem but now i am stuck on this 
![image](https://user-images.githubusercontent.com/74601249/178673618-e371f029-cf57-4118-a5b0-7c6af335704a.png)

**Comment by CriticalMomento** [comment]
ok using vsc , turned on console logging and it keeps looping on this
i have the latest ver of discum tho
![image](https://user-images.githubusercontent.com/74601249/178683931-43e0fe03-b730-481d-ac93-7949f4da629f.png)

**Comment by CriticalMomento** [comment]
ok so now i got to the point where this prints out stuff like this continously , i have zero idea if i am doing anything wrong or correct 
![image](https://user-images.githubusercontent.com/74601249/178706218-3552e976-120f-4104-bf46-2851cd83b2cc.png)

**Comment by vivinano** [comment]
Invalid version of discum for problem one

And Third problem is pertaining to channeldata file

**Comment by CriticalMomento** [comment]
> Invalid version of discum for problem one
> 
> And Third problem is pertaining to channeldata file

As for discum version I used the pip cmd with githib repository link, don't see how it's invalid

The third problem I will see after I sleep

**Comment by CriticalMomento** [comment]
Do you have a discord or something to contact you or someone else viewing this issue that has the bot running
can u contact me on discord? CriticalMomento#2276
i really want to get this working

**Comment by vivinano** [comment]
I do but would rather to keep it on here avoid being dm every night and day about questions

**Comment by CriticalMomento** [comment]
> I do but would rather to keep it on here avoid being dm every night and day about questions

yea ig that would be very annoying..
oh well i will just have to hope someome else helps now..

**Comment by vivinano** [comment]
> > I do but would rather to keep it on here avoid being dm every night and day about questions
> 
> yea ig that would be very annoying.. oh well i will just have to hope someome else helps now.. @vivinano or u could make a tutorial , i bet it would help a ton :D

depends how famous will I get on my YouTube if I make a tutorial lol XD
already created this whole bot for fweeeeeee lol :D

**Comment by CriticalMomento** [comment]
> > > I do but would rather to keep it on here avoid being dm every night and day about questions
> > 
> > 
> > yea ig that would be very annoying.. oh well i will just have to hope someome else helps now.. @vivinano or u could make a tutorial , i bet it would help a ton :D
> 
> depends how famous will I get on my YouTube if I make a tutorial lol XD already created this whole bot for fweeeeeee lol :D

xD , not sure about views but it surely help me :Kek:

**Comment by CriticalMomento** [comment]
@vivinano wis i could talk to u on discord

**Comment by vivinano** [comment]
> @vivinano wis i could talk to u on discord

I have learned to keep personally time separated from strictly supporting repo time. As again this is a repo that I have made and released to the public for free but offering more of my personal time to further support the repo is something I do when I can

**Comment by CriticalMomento** [comment]
ok after tinkering enough i realized i have been using wrong token of my acc
after using correct token this is the error i get 
![image](https://user-images.githubusercontent.com/74601249/185636565-3e2e8fdb-ebfd-48b9-b0c6-dd46eee24e56.png)
any help?
@vivinano

**Comment by vivinano** [comment]
Do you have a settings files in your channeldata folder?

**Comment by CriticalMomento** [comment]
> Do you have a settings files in your channeldata folder?

![image](https://user-images.githubusercontent.com/74601249/185659967-119d86bf-ed20-414e-94de-ed6a761b3c4a.png)
only this in channeldata folder

**Comment by vivinano** [comment]
yeah you need a settings instance to pull the data from

**Comment by CriticalMomento** [comment]
> yeah you need a settings instance to pull the data from
> […](#)
> Sent from my iPhone
> On Aug 19, 2022, at 9:02 AM, CriticalMomento ***@***.***> wrote: ﻿ Do you have a settings files in your channeldata folder? only this in channeldata folder — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

and how will i create a settings file?

**Comment by CriticalMomento** [comment]
nvm i had to do $settings in channel but here is the new problem
![image](https://user-images.githubusercontent.com/74601249/185724740-8ad78ea9-22da-4d32-a1ab-47b75b9ff9b3.png)

**Comment by CriticalMomento** [comment]
i created a setting instance 
![image](https://user-images.githubusercontent.com/74601249/185724944-60badc21-8b00-4913-b553-77c7190e142b.png)
[982607339838406658.txt](https://github.com/vivinano/MudaeAutoBot/files/9386035/982607339838406658.txt)

it still shows this after doing all of that 
![image](https://user-images.githubusercontent.com/74601249/185724978-20e1a1bd-c24c-46d1-b28c-275c54960646.png)

**Comment by Fractune** [comment]
> I have learned to keep personally time separated from strictly supporting repo time. As again this is a repo that I have made and released to the public for free but offering more of my personal time to further support the repo is something I do when I can

I don't see any point in this project of yours if everyone has a problem with setting it up, Imo there's a problem with your explanation and even me who tried to help Critical with his difficulty I'm actually bothered on the reason this isn't working.

**Comment by Fractune** [comment]
It's now an error with the `["user"]` keyword @vivinano

**Comment by vivinano** [comment]
Refer to the key word user error issue and continue

**Comment by CriticalMomento** [comment]
@vivinano i used the temp fix which was in user error issue and this is the result
![image](https://user-images.githubusercontent.com/74601249/186597513-88251e60-3d08-4fc5-814e-a60a9c33f8b2.png)

**Comment by CriticalMomento** [comment]
Alright i managed to make it work by using this as a reference https://github.com/vivinano/MudaeAutoBot/issues/87
