### ISSUE TITLE
An exception occurred: KeyError 'messages'.

### ISSUE THREAD

**Issue by hgartemis3515** [vivinano/MudaeAutoBot#187]
[
![image](https://user-images.githubusercontent.com/107431348/181148038-656ea44b-7a5c-4549-a137-e253ea9946a0.png)
](url)

**Comment by vivinano** [comment]
Settings from a $setting instance was not obtained hence forth the channel Id was removed from the list of channel it can interact with causing an issue because you can’t run code on null

**Comment by vivinano** [comment]
Closing with settings instance were not found causing the channel Id to be removed from the bot returning a null
