### ISSUE TITLE
Not really a issue but a question

### ISSUE THREAD

**Issue by RedbrickCobra66** [vivinano/MudaeAutoBot#189]
Hello I was wondering if anyone knows how I could add a way to do $daily and $rolls and it have a cool down like everything else

**Comment by vivinano** [comment]
Same way the rolls are triggered just add another thread trigger

**Comment by RedbrickCobra66** [comment]
Kind of new two more advanced python code anyway u can help?

**Comment by vivinano** [comment]
Only if there is a group interest in the update I'll implement it otherwise you must implement it yourself

**Comment by xd-mau5** [comment]
> Only if there is a group interest in the update I'll implement it otherwise you must implement it yourself

I'm interested 👀

**Comment by SakaDiscord** [comment]
> Only if there is a group interest in the update I'll implement it otherwise you must implement it yourself

Interested

**Comment by CriticalMomento** [comment]
> Only if there is a group interest in the update I'll implement it otherwise you must implement it yourself

Interested.

**Comment by vivinano** [comment]
I've implemented a test of the daily function which for now is part of pokerolling
