### ISSUE TITLE
I need help setting this up

### ISSUE THREAD

**Issue by AntiMagicDevil** [vivinano/MudaeAutoBot#190]
I am very new to python

when i run the bot through cmd I get this 
![image](https://user-images.githubusercontent.com/108036361/182199375-d00ee2b7-e2ee-4347-9444-1036adec6495.png)

**Comment by vivinano** [comment]
Instructions are located on the read me

**Comment by AntiMagicDevil** [comment]
how do i import discum?

**Comment by vivinano** [comment]
That is also located in the read me
