### ISSUE TITLE
wrong emoji

### ISSUE THREAD

**Issue by marcussla** [vivinano/MudaeAutoBot#191]
the bot attempted to claim a wished character and added a wrong heart emoji on the side, after this added the right emoji but someone else already claimed this, the claim speed is good but the problem is really this. after that the bot succesfully claimed another wished character but i was not present, but i only see the right emoji on in that so i don't know if he did this again but this time got it

https://imgur.com/a/xV6h7DJ
https://imgur.com/a/GDhs0MR

**Comment by AntiMagicDevil** [comment]
yo could you help me set it  up my discord is RustyPizza#5336

**Comment by vivinano** [comment]
The emoji is checked upon the time
It shows up so if you have 0 delay it will see that the message has no emoji on it and then react with a heart 


Basically the bot is seeing the embed before mudae itself adds the emoji to react to

**Comment by marcussla** [comment]
> The emoji is checked upon the time It shows up so if you have 0 delay it will see that the message has no emoji on it and then react with a heart
> 
> Basically the bot is seeing the embed before mudae itself adds the emoji to react to

i removed the 0.5 time sleep, so if i add again you think this will happen less?

**Comment by AntiMagicDevil** [comment]
really finna ignore me??

**Comment by vivinano** [comment]
> > The emoji is checked upon the time It shows up so if you have 0 delay it will see that the message has no emoji on it and then react with a heart
> 
> > 
> 
> > Basically the bot is seeing the embed before mudae itself adds the emoji to react to
> 
> 
> 
> i removed the 0.5 time sleep, so if i add again you think this will happen less?

Yes as you said that it added the heart on the one time but not during the one with the horns basically basically either mudae is slow or the bot is to quick to detect a reaction in that window of time

**Comment by vivinano** [comment]
> really finna ignore me??

No other user is obligated to assist and you already opened an issue which is still open which can be solved by reading over the readme as part of the repo

**Comment by marcussla** [comment]
> > > The emoji is checked upon the time It shows up so if you have 0 delay it will see that the message has no emoji on it and then react with a heart
> > 
> > 
> > > 
> > 
> > 
> > > Basically the bot is seeing the embed before mudae itself adds the emoji to react to
> > 
> > 
> > i removed the 0.5 time sleep, so if i add again you think this will happen less?
> 
> Yes as you said that it added the heart on the one time but not during the one with the horns basically basically either mudae is slow or the bot is to quick to detect a reaction in that window of time



> > > The emoji is checked upon the time It shows up so if you have 0 delay it will see that the message has no emoji on it and then react with a heart
> > 
> > 
> > > 
> > 
> > 
> > > Basically the bot is seeing the embed before mudae itself adds the emoji to react to
> > 
> > 
> > i removed the 0.5 time sleep, so if i add again you think this will happen less?
> 
> Yes as you said that it added the heart on the one time but not during the one with the horns basically basically either mudae is slow or the bot is to quick to detect a reaction in that window of time

i see, so i'll do this, thank you for the help and sorry for taking your time with this simple doubt

**Comment by marcussla** [comment]
after doing this the bot succesfully claimed a wished character without adding a wrong emoji this time so i'm closing this issue

https://imgur.com/a/GBwOYjW
