### ISSUE TITLE
GatewayServer._response_loop of discum error

### ISSUE THREAD

**Issue by Denchyaknow** [vivinano/MudaeAutoBot#192]
Happens on both my boths for 2 diff accounts, tried pulling fresh configs and settings it all up.

Full Log:

PS Z:\Git\MudaeAutoBot> python .\MudaeAutoBot.py
File Not Found using Different Method
Default $settings used for channel 988564585701318662
File Not Found using Different Method
Default $settings used for channel 988564585701318662
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001D4DF537E80>>
Traceback (most recent call last):
  File "C:\Users\BlahBlah\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "Z:\Git\MudaeAutoBot\MudaeAutoBot.py", line 763, in on_message
    msg = get_server_settings(gid,matched_channel)
  File "Z:\Git\MudaeAutoBot\MudaeAutoBot.py", line 189, in get_server_settings
    · Prefix: **{settings_hope_prefix}** ($prefix)
UnboundLocalError: local variable 'settings_hope_prefix' referenced before assignment

This started happening recently like this month.
Any guesses?

**Comment by vivinano** [comment]
It’s saying your files aren’t present for the channel

**Comment by vivinano** [comment]
No further details given going to close issue as resolved
