### ISSUE TITLE
Why does the the program try to immediately snipe a character. I think i have a correct claim list that matches my WL.

### ISSUE THREAD

**Issue by MidnightPrince** [vivinano/MudaeAutoBot#193]
],
   "namelist":[
      "Blossom", "Tommy Oliver", "Whitebeard", "Monkey D. Luffy", "Sasuke Uchiha", "Madara Uchiha", "Yoruichi Shihouin"

 ],
   "min_kak":500,
   "Last_True":"False",
   "last_claim_min": 180,
   "min_kak_last_min": 10

![wrong claim](https://user-images.githubusercontent.com/110657135/183026008-f8d2f0b8-7e50-4369-82d6-4dafad81f6e8.png)
![wl](https://user-images.githubusercontent.com/110657135/183026210-16479316-2619-46a2-8d78-5dcddac4f6cb.png)

**Comment by vivinano** [comment]
That seems like a series list snipe atleast the claim message does

**Comment by MidnightPrince** [comment]
I don't have anything on the claim list.

**Comment by vivinano** [comment]
Well there already a wish list claiming you wouldn’t need to add anything to the character list as the bot has wishlist sniping coded into it

**Comment by MidnightPrince** [comment]
Ok, I'll remove it and try again.

**Comment by vivinano** [comment]
Does the wishes character have a “@“ user ??
