### ISSUE TITLE
Bot puts random letters in front of slash command

### ISSUE THREAD

**Issue by SacredZenpie** [vivinano/MudaeAutoBot#194]
Screenshot of bot trying to roll
![image](https://user-images.githubusercontent.com/110957549/183808218-9d55e4c9-8dfa-4d15-8f47-6bc923bfdcb2.png)

**Comment by vivinano** [comment]
Uh can't reproduce it on my side can you give me more information ?

**Comment by vivinano** [comment]
no further info given so Going to close
