### ISSUE TITLE
bot wont run

### ISSUE THREAD

**Issue by Fractune** [vivinano/MudaeAutoBot#196]
Using the old src of a bot and the latest version of Discum. I tried to find solutions for the matter where the bot never runs, it remains stuck after executing `py main.py` (the bot file) If I attempt to set auto_reconnect to False, it exits within a second orso.

![image](https://user-images.githubusercontent.com/74881934/184500214-939190c7-30a5-4661-bef8-258927ec7b7d.png)

**Comment by vivinano** [comment]
The old src has to be ran with an older version of discum due to discum changing some keywords for certain things that was changed in the newer version

**Comment by Fractune** [comment]
> The old src has to be ran with an older version of discum due to discum changing some keywords for certain things that was changed in the newer version
> […](#)
> Sent from my iPhone
> On Aug 13, 2022, at 11:19 AM, Oni ***@***.***> wrote: ﻿ Using the old src of a bot and the latest version of Discum. I tried to find solutions for the matter where the bot never runs, it remains stuck after executing py main.py (the bot file) If I attempt to set auto_reconnect to False, it exits within a second orso. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Oke, I'll try that.
