### ISSUE TITLE
Future Kakera Button Support ?

### ISSUE THREAD

**Issue by SakaDiscord** [vivinano/MudaeAutoBot#198]
Can/Will auto claim for kakera be added? 

Being able to auto claim kakera would be really useful.

**Comment by vivinano** [comment]
It's was added but with button support being added I haven't felt like adding the button kakera press

**Comment by SakaDiscord** [comment]
> 

So you won't add the button kakera press ever? Or just not right now?

**Comment by vivinano** [comment]
If you toggle.button off then you can claim kakera but 

As for adding button support trying to figure a way that is more optimal then just adding it into the message gateway

**Comment by SakaDiscord** [comment]
I understand. 
Thank you so much for your work and fast replies!
The Bot is amazing.

**Comment by BellaDona007** [comment]
> > 
> 
> So you won't add the button kakera press ever? Or just not right now? It would be a great feature and i read multiple people suggestion it/asking for it.
> 
> Adding another question since i read about it too. Will the Bot auto claim Kakera again if i do $togglebuttons?
> 
> [Solved, tried it myself. Whoever reads this, if you want the bot to automatically claim Kakera disable the buttons in mudae with $togglebuttons.]

$togglebuttons: (MOD) Display buttons to click instead of reactions (rolls only), or the opposite. See $togglereact for more options.

That is, it does not work for other servers that you are not a mod.

**Comment by xd-mau5** [comment]
Now we need the button implementation, we can disable the butttons.
`Buttons are now mandatory due to Discord enforcing their rate limits (number of reactions allowed for the bot).
`
