### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by NightCrii** [vivinano/MudaeAutoBot#2]
Trying to figure out how to set it up using the settings. Any way to contact you?

**Comment by cheroso1337** [comment]
"token" - token of ur acc to do the things
"channel_id" - id of the channel to roll/claim
"claim_delay" - delay to react  for claiming, i use 1
"kak_delay" - delay to react forkakera, i use 8
"use_emoji" - emoji to react with
"roll_this" - command to send, ($w/wg/m/ma etc)
"rolling" - if u want to roll or not
"pkmrolling" - $p rolling
"series_list" - series that u want to snipe
"min_kak" - min kakera to snipe if not from series list, i use 600

**Comment by vivinano** [comment]
Basically above unless there is something more you need?

**Comment by vivinano** [comment]
Gonna be closing this issue. as I'm assuming this has been resolved as I haven't heard anything else in 24 hours
