### ISSUE TITLE
min_kak It does not work properly

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#200]
Even though I had claim and set min_kak to 681, a character with value 876 appeared and the bot simply ignored it, the funny thing is that sometimes it works, but only if the bot was recently opened.
I noticed that the bot sometimes after a while it stops working, it counts the rolls, but does not take any action

**Comment by vivinano** [comment]
Did you confirm that it was within your claim cycle cause if it's not within your claim window then it will not snipe

**Comment by vivinano** [comment]
no response gonna close issue
