### ISSUE TITLE
Key error "user"

### ISSUE THREAD

**Issue by anwarlopoo** [vivinano/MudaeAutoBot#203]
[
![image](https://user-images.githubusercontent.com/104317268/187704172-049b1e48-4a10-4d0d-bbba-7a778c8e3554.png)
](url)

**Comment by CriticalMomento** [comment]
https://github.com/vivinano/MudaeAutoBot/issues/137
refer to this

**Comment by anwarlopoo** [comment]
but this is not clear

**Comment by anwarlopoo** [comment]
> #137 refer to this
can you explain me?

**Comment by CriticalMomento** [comment]
> > #137 refer to this
> > can you explain me?

i am sure if u actually read all the comments there you would know what to do
you can do it!
just read!

**Comment by anwarlopoo** [comment]
> > > #137 refer to this
> > > can you explain me?
> 
> i am sure if u actually read all the comments there you would know what to do you can do it! just read!

im not good at speaking english and im not good at coding

**Comment by CriticalMomento** [comment]
> > > > #137 refer to this
> > > > can you explain me?
> > 
> > 
> > i am sure if u actually read all the comments there you would know what to do you can do it! just read!
> 
> im not good at speaking english and im not good at coding

Go to your discum package folder: /discum/gateway/types.py. Add some type under channelTypes. For instance:
channelTypes = {
0: "guild_text",
1: "dm",
2: "guild_voice",
3: "group_dm",
4: "guild_category",
5: "guild_news",
6: "guild_store",
10: "guild_news_thread",
11: "guild_public_thread",
12: "guild_private_thread",
13: "guild_stage_voice",
14: "type_14",
15: "type_15"
}

**Comment by anwarlopoo** [comment]
> channelTypes = {
> 0: "guild_text",
> 1: "dm",
> 2: "guild_voice",
> 3: "group_dm",
> 4: "guild_category",
> 5: "guild_news",
> 6: "guild_store",
> 10: "guild_news_thread",
> 11: "guild_public_thread",
> 12: "guild_private_thread",
> 13: "guild_stage_voice",
> 14: "type_14",
> 15: "type_15"
> }

i need to replace all the file with only this?

**Comment by CriticalMomento** [comment]
> > channelTypes = {
> > 0: "guild_text",
> > 1: "dm",
> > 2: "guild_voice",
> > 3: "group_dm",
> > 4: "guild_category",
> > 5: "guild_news",
> > 6: "guild_store",
> > 10: "guild_news_thread",
> > 11: "guild_public_thread",
> > 12: "guild_private_thread",
> > 13: "guild_stage_voice",
> > 14: "type_14",
> > 15: "type_15"
> > }
> 
> i need to replace all the file with only this?

yes

**Comment by CriticalMomento** [comment]
> > channelTypes = {
> > 0: "guild_text",
> > 1: "dm",
> > 2: "guild_voice",
> > 3: "group_dm",
> > 4: "guild_category",
> > 5: "guild_news",
> > 6: "guild_store",
> > 10: "guild_news_thread",
> > 11: "guild_public_thread",
> > 12: "guild_private_thread",
> > 13: "guild_stage_voice",
> > 14: "type_14",
> > 15: "type_15"
> > }
> 
> [ ![image](https://user-images.githubusercontent.com/104317268/187713886-f1857e45-b7c9-43c1-9cda-22cd0c4f71d0.png) ](url)



> [ ![image](https://user-images.githubusercontent.com/104317268/187714862-92686e56-c50d-4deb-8ea8-5f94e4018d01.png) ](url)

oh man 
i worded it wrong you only need replace channel types

**Comment by anwarlopoo** [comment]
now its doing me this

**Comment by anwarlopoo** [comment]
[
![image](https://user-images.githubusercontent.com/104317268/187724226-08241d52-10c2-4556-a6ba-94b309409e63.png)
](url)

**Comment by CriticalMomento** [comment]
> > > > channelTypes = {
> 
> [ ![image](https://user-images.githubusercontent.com/104317268/187724120-7c088196-43e6-4112-93db-68648fe5d879.png) ](url)

do $settings in the channel you want the bot to run
then run the bot
it should create a empty txt file with channel id as its name in channel data folder
fill up the txt file manually
bold the stuff by adding **

**Comment by anwarlopoo** [comment]
> 

[
![image](https://user-images.githubusercontent.com/104317268/187725312-d858c0d7-c8d5-4675-b149-f4314674bea6.png)
](url)

**Comment by CriticalMomento** [comment]
> > 
> 
> [ ![image](https://user-images.githubusercontent.com/104317268/187725312-d858c0d7-c8d5-4675-b149-f4314674bea6.png) ](url)

you are using main version? with slash right?
i am having the same issue with slash version
altho v4 works fine
it doesnt have button support

**Comment by anwarlopoo** [comment]
> > > 
> > 
> > 
> > [ ![image](https://user-images.githubusercontent.com/104317268/187725312-d858c0d7-c8d5-4675-b149-f4314674bea6.png) ](url)
> 
> you are using main version? with slash right? i am having the same issue with slash version altho v4 works fine it doesnt have button support

can i have the v4 link?

**Comment by anwarlopoo** [comment]
nvm

**Comment by anwarlopoo** [comment]
[
![image](https://user-images.githubusercontent.com/104317268/187728252-810b4c5f-8637-4b75-942a-2f377017bc1a.png)
](url)

**Comment by anwarlopoo** [comment]
i have this with the v4

**Comment by CriticalMomento** [comment]
> i have this with the v4

check ur json.settings file correctly

**Comment by CriticalMomento** [comment]
actually its probably related to ur channel data txt files

**Comment by anwarlopoo** [comment]
[
![image](https://user-images.githubusercontent.com/104317268/187730361-a546a186-6ca5-4621-9757-95ed2c9d7c4d.png)

](url)

**Comment by CriticalMomento** [comment]
> [ ![image](https://user-images.githubusercontent.com/104317268/187730361-a546a186-6ca5-4621-9757-95ed2c9d7c4d.png)
> 
> ](url)

something def wrong with ur json file

**Comment by anwarlopoo** [comment]
[
![image](https://user-images.githubusercontent.com/104317268/187730843-153cea39-89e0-4231-bca8-638bcf54de51.png)
](url)

**Comment by CriticalMomento** [comment]
do you see any errors?
visual studio code should help show

**Comment by anwarlopoo** [comment]
idk how to use it

> do you see any errors? visual studio code should help show

**Comment by anwarlopoo** [comment]
can you give me your discord? it will be better

**Comment by anwarlopoo** [comment]
[
![image](https://user-images.githubusercontent.com/104317268/187742505-870ebec0-5645-46f8-8fdf-c22d3295cdf6.png)
](url)

**Comment by CriticalMomento** [comment]
> [ ![image](https://user-images.githubusercontent.com/104317268/187742505-870ebec0-5645-46f8-8fdf-c22d3295cdf6.png) ](url)

it seems like you need config your channel data file

**Comment by vivinano** [comment]
Closing issue as there trying to keep all key error users under 1 issue
