### ISSUE TITLE
ModuleNotFoundError: No module named 'discum.utils'; 'discum' is not a package

### ISSUE THREAD

**Issue by bachaun** [vivinano/MudaeAutoBot#204]
![mudae bot problem](https://user-images.githubusercontent.com/66851009/188296764-b714864a-d2a5-494b-b0c0-2beabd458293.png)
 
i ran into this problem, i don't know what to do, any ideas?

**Comment by vivinano** [comment]
Install discum

**Comment by bachaun** [comment]
i already installed it twice :c i swear.

**Comment by vivinano** [comment]
Then you have a different instance of python somewhere on the computer and only installed for the one your not using

**Comment by vivinano** [comment]
this is a issue with windows store install of python dealing with these types of issues require alot of time and remote access to issuers computer which is out of the scope of this project
