### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by cat-chan** [vivinano/MudaeAutoBot#206]
- loop send $us 20 if rolls_left == 0
- random sleep between each roll
- divorce reclaim char
![Discord_qNn2wc05I7](https://user-images.githubusercontent.com/106933377/193485603-b30af3cf-3e7b-4c26-b56f-ed8f4fa60204.png)

**Comment by vivinano** [comment]
What would be the purpose of using all rolls from your kakeraloot ? If there a purpose I'll consider the addition 

Random time between rolls would make it more suspicious that you are a bot which defeats the goal currently the bot wait for a quiet moment in the channel before making all rolls 
If you were to add a random wait time for a user with 50 rolls or a bigger number than it will annoy other users that you are taking way to long etc etc 


I don't know that the divorce reclaim function existed would you care to elaborate on the use of this function ?

**Comment by cat-chan** [comment]
I want to farm keys with $us in order to increase characters value. Then I can use do "divorce reclaim".
![image](https://user-images.githubusercontent.com/106933377/193658028-195f496c-a07f-4ab0-80d5-6e4cc70d2074.png)

I do this in my private server where I play alone

"divorce reclaim" is a term about the process of divorce a certain character then claim it again in order to get kakera from divorce + claiming (emerald 4)

**Comment by vivinano** [comment]
I can technically tell you that the changes you want are in the realm of possibility but these are more tailored to your personal needs and wants 

The code is technically available if you need to change or amend the code to fit your needs 

And you can do more specialized testing in your server to fine tune the program to you as I don't have access to any disposable kakera I want to use on kakeraloots for testing

**Comment by cat-chan** [comment]
```                
                bot.sendMessage(tides,roll_cmd)
                time_to_sleep = random.uniform(2.5, 3.2)
                time.sleep(time_to_sleep)
```
like this?

**Comment by vivinano** [comment]
Rolls are handled by a different thread so you have to make changes to that thread and then claiming is handled by the main thread which you would have to set to never set the wait variable to true that is what you would want to do

**Comment by cat-chan** [comment]
ty and how can i do this + divorce only if char name in divorce_list
```
                    # Successful claim, mark waifu claim window as used
                    waifu_wall[rchannelid] = next_claim(rchannelid)[0]
                    bot.sendMessage(divorce_channel,"$divorce "+ divorce_name)
                    time.sleep(0.5)
                    bot.sendMessage(divorce_channel,"y")
                    print(divorce_name," deceived")
```
