### ISSUE TITLE
I Don't understand last minute claim.

### ISSUE THREAD

**Issue by The-guide-00** [vivinano/MudaeAutoBot#208]
so i set tup the bot and everything is working perfect but i have a question about what "last minute claim" is, idk if im just dense but the explanation was kinda confusing, i was also wondering what soul kakera is and what the diffrent colors of kakera mean?

> "min_kak - A minimum kakera value ### to snipe a claimable character regardless of whether it's in the series/name lists
> Last_True - (True|False) enable Last Minute Claim windows

**last_claim_min - (1-180) the window the window is open for e.g. 10 means last 10 minutes**

> min_kak_last_min - same as min kak but only within the last minute claim window"

**Comment by cat-chan** [comment]
https://github.com/vivinano/MudaeAutoBot/issues/143#issuecomment-1055812011

> So how last minute claims work is that if your claim is still available it will claim during the last claim window fitting the min kak there

so if
```
last_claim_min: 60
min_kak_last_min: 500
```
that mean the script will claim wishes and chars from `name_list`
then if `1h` left for reset claim the script will claim any char has `500kak` value

soul kakera mean Kakera reactions on char that have **10 keys** or more
![image](https://user-images.githubusercontent.com/106933377/194734244-349e4f41-d3ad-4f2b-891e-784442358ca4.png)

> LVL 10 (Chaos) => **Kakera** reactions on this character cost **half the power** for the character owner.

> Your characters with 10+ keys consume half the power (15%)

**Comment by The-guide-00** [comment]
this cleared it up for me,
Thank you so much!


> [#143 (comment)](https://github.com/vivinano/MudaeAutoBot/issues/143#issuecomment-1055812011)
> 
> > So how last minute claims work is that if your claim is still available it will claim during the last claim window fitting the min kak there
> 
> so if
> 
> ```
> last_claim_min: 60
> min_kak_last_min: 500
> ```
> 
> that mean the script will claim wishes and chars from `name_list` then if `1h` left for reset claim the script will claim any char has `500kak` value
> 
> soul kakera mean Kakera reactions on char that have **10 keys** or more ![image](https://user-images.githubusercontent.com/106933377/194734244-349e4f41-d3ad-4f2b-891e-784442358ca4.png)
> 
> > LVL 10 (Chaos) => **Kakera** reactions on this character cost **half the power** for the character owner.
> 
> > Your characters with 10+ keys consume half the power (15%)
