### ISSUE TITLE
Exception has occurred: IndentationError

### ISSUE THREAD

**Issue by XLThinOreos1** [vivinano/MudaeAutoBot#209]
![bild](https://user-images.githubusercontent.com/111511159/195851980-fa882b53-230f-43eb-88f0-ba7d6896001c.png)

This occurs after typing $settings, or well anything after starting the bot

**Comment by vivinano** [comment]
to many spaces then so try to align the spaces

**Comment by XLThinOreos1** [comment]
> to many spaces then so try to align the spaces

I have not modified your code whatsoever and I am not really sure why this is happening. Everything is aligned as it should without causing any errors

**Comment by vivinano** [comment]
Based on what you provided to me that is the only answer I can provide

**Comment by XLThinOreos1** [comment]
> Based on what you provided to me that is the only answer I can provide

What can I show that could be helpful?

**Comment by vivinano** [comment]
Well I would say just redownload the files and try again probably for the best to fix a indention error

**Comment by XLThinOreos1** [comment]
> Well I would say just redownload the files and try again probably for the best to fix a indention error

Reinstalling discum fixed the problem but then the notorious "KeyError 'user' " showed up.
