### ISSUE TITLE
Question concerning the bot

### ISSUE THREAD

**Issue by gardiens** [vivinano/MudaeAutoBot#210]
Hello, 
I found your github by chance but their is several problem:
<img width="614" alt="Capture d’écran 2022-10-16 à 12 12 11" src="https://user-images.githubusercontent.com/84439209/196029720-03e08669-3819-4f47-a3d2-7451124ef79d.png">

when the app runs indefinitily and no messages appears, is it normal?

**Comment by cat-chan** [comment]
use IDLE

**Comment by gardiens** [comment]
When I use the idle, I still get the problem.
However when I keyboard interrupt  I got this error message, maybe It can
help
[image: Capture d’écran 2022-10-16 à 16.13.34.png]

**Comment by cat-chan** [comment]
can you resend the image?

**Comment by gardiens** [comment]
<img width="1170" alt="Capture d’écran 2022-10-16 à 17 17 31" src="https://user-images.githubusercontent.com/84439209/196043464-aaf20ae5-16f9-496e-b8e8-2ef8dcbd8583.png">
 here it is :)

**Comment by cat-chan** [comment]
try this https://github.com/vivinano/MudaeAutoBot/issues/137#issuecomment-1210024855

**Comment by gardiens** [comment]
didn't work too, I will dive into it tomorrow

**Comment by vivinano** [comment]
That looks like an environment error have you set things up correctly?

**Comment by gardiens** [comment]
Well as said in the github, I just add  my token_id in the Settings_mudae.json and the channel I want.
I tried to debug it but it is strange that self.settings_ready[user} is empty before the error message 
![Capture d’écran 2022-10-17 à 08 38 08](https://user-images.githubusercontent.com/84439209/196106304-a8da3184-7148-46cf-b93f-4c5c63fa51d5.png)

**Comment by vivinano** [comment]
Yeah if your getting the user error bug I can't really resolve it as I have not gotten that error myself ? So it's hard/impossible to solve something I don't know how it is triggered or experiencing myself
