### ISSUE TITLE
Key error: user

### ISSUE THREAD

**Issue by VSeaV** [vivinano/MudaeAutoBot#215]
Tried that temp fix. Didn't work

Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001D94F0B2770>>
Traceback (most recent call last):
  File "C:\Users\Borut\AppData\Roaming\Python\Python310\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\Borut\Desktop\MudaeAutoBot-4\MudaeAutoBot.py", line 686, in on_message
    user = bot.gateway.session.user
  File "C:\Users\Borut\AppData\Roaming\Python\Python310\site-packages\discum\gateway\session.py", line 42, in user
    return self.settings_ready['user']
KeyError: 'user'
2022-10-27 16:55:17,458:Could not find settings for 1026999547769131108, please trigger the '$settings' command in the server and run the bot again.

Also doesn't create a txt file when I do $settings

**Comment by VSeaV** [comment]
Thought it was fixed but it wasnt.

**Comment by louis50171** [comment]
did you try to tape $setting then launch the bot (order matter here)

**Comment by VSeaV** [comment]
> 

Yes, It didn't make a text file though so I dont really know what to do from here. I also tried that channeltypes fix and it didn't seem to do anything.

**Comment by kyeong6250** [comment]
Mine also did not make a text file. Tried multiple times, should I just make it manually? If so, what should i name the txt and a template would help as well

**Comment by vivinano** [comment]
> Mine also did not make a text file. Tried multiple times, should I just make it manually? If so, what should i name the txt and a template would help as well

There a default set up in the code itself that you can copy and edit and it should be named the channelid

**Comment by VSeaV** [comment]
> > Mine also did not make a text file. Tried multiple times, should I just make it manually? If so, what should i name the txt and a template would help as well
> 
> There a default set up in the code itself that you can copy and edit and it should be named the channelid

Well even if thats fixed im still left with the key error, which was not fixed using that temp fix in the other thread.

**Comment by VSeaV** [comment]
> > Mine also did not make a text file. Tried multiple times, should I just make it manually? If so, what should i name the txt and a template would help as well
> 
> There a default set up in the code itself that you can copy and edit and it should be named the channelid

where in the code is it located?

**Comment by vivinano** [comment]
> > > Mine also did not make a text file. Tried multiple times, should I just make it manually? If so, what should i name the txt and a template would help as well
> 
> > 
> 
> > There a default set up in the code itself that you can copy and edit and it should be named the channelid
> 
> 
> 
> Well even if thats fixed im still left with the key error, which was not fixed using that temp fix in the other thread.

This issue falls outside the scope of an issue I can fix as it doesn't pertain to my code but within the disum library 

I personally have tried but am unable to recreate the key user error myself so in that regards can't fix something I can't recreate

**Comment by VSeaV** [comment]
> > > > Mine also did not make a text file. Tried multiple times, should I just make it manually? If so, what should i name the txt and a template would help as well
> > 
> > 
> > > 
> > 
> > 
> > > There a default set up in the code itself that you can copy and edit and it should be named the channelid
> > 
> > 
> > Well even if thats fixed im still left with the key error, which was not fixed using that temp fix in the other thread.
> 
> This issue falls outside the scope of an issue I can fix as it doesn't pertain to my code but within the disum library
> 
> I personally have tried but am unable to recreate the key user error myself so in that regards can't fix something I can't recreate

yeah Im wondering if i installed discum wrong and python and stuff because im new to this whole thing so its very possible

**Comment by cat-chan** [comment]
> > > > > Mine also did not make a text file. Tried multiple times, should I just make it manually? If so, what should i name the txt and a template would help as well
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > There a default set up in the code itself that you can copy and edit and it should be named the channelid
> > > 
> > > 
> > > Well even if thats fixed im still left with the key error, which was not fixed using that temp fix in the other thread.
> > 
> > 
> > This issue falls outside the scope of an issue I can fix as it doesn't pertain to my code but within the disum library
> > I personally have tried but am unable to recreate the key user error myself so in that regards can't fix something I can't recreate
> 
> yeah Im wondering if i installed discum wrong and python and stuff because im new to this whole thing so its very possible

i have the same Issues but when i use simple script that only send message it works anyway i will try reinstall python and discum 
![image](https://user-images.githubusercontent.com/106933377/198862740-22a1ca5f-10ae-4ad5-a6f8-aea6f9e1b2af.png)

**Comment by VSeaV** [comment]
> 

can u add me on disc and help me install python and discum if u ever get it working? thanks.

**Comment by VSeaV** [comment]
> > > > Mine also did not make a text file. Tried multiple times, should I just make it manually? If so, what should i name the txt and a template would help as well
> > 
> > 
> > > 
> > 
> > 
> > > There a default set up in the code itself that you can copy and edit and it should be named the channelid
> > 
> > 
> > Well even if thats fixed im still left with the key error, which was not fixed using that temp fix in the other thread.
> 
> This issue falls outside the scope of an issue I can fix as it doesn't pertain to my code but within the disum library
> 
> I personally have tried but am unable to recreate the key user error myself so in that regards can't fix something I can't recreate

IM starting to think that maybe I got the slash Id and guild channel slash id's wrong. How do i obtain those?

**Comment by cat-chan** [comment]
> > > > > > Mine also did not make a text file. Tried multiple times, should I just make it manually? If so, what should i name the txt and a template would help as well
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > There a default set up in the code itself that you can copy and edit and it should be named the channelid
> > > > 
> > > > 
> > > > Well even if thats fixed im still left with the key error, which was not fixed using that temp fix in the other thread.
> > > 
> > > 
> > > This issue falls outside the scope of an issue I can fix as it doesn't pertain to my code but within the disum library
> > > I personally have tried but am unable to recreate the key user error myself so in that regards can't fix something I can't recreate
> > 
> > 
> > yeah Im wondering if i installed discum wrong and python and stuff because im new to this whole thing so its very possible
> 
> i have the same Issues but when i use simple script that only send message it works anyway i will try reinstall python and discum ![image](https://user-images.githubusercontent.com/106933377/198862740-22a1ca5f-10ae-4ad5-a6f8-aea6f9e1b2af.png)

it did not work even after reinstall python and discum but the script works fine when i use replit
![image](https://user-images.githubusercontent.com/106933377/198877650-9f137d0c-d763-4bb9-b13f-591a8913f458.png)

**Comment by VSeaV** [comment]
> 

Cool. Can you tell me how to get this?

**Comment by kyeong6250** [comment]
Made my own txt for the $settings and I still got the user error. Anyone found a fix?

**Comment by vivinano** [comment]
Well since there now 2 issues open for the same issue you can check the other one also and see if there is a fix

**Comment by cat-chan** [comment]
> Made my own txt for the $settings and I still got the user error. Anyone found a fix?

https://github.com/vivinano/MudaeAutoBot/issues/213#issuecomment-1297398307

**Comment by VSeaV** [comment]
> 

ever figure out what exactly fixed it?

**Comment by Shirokumowo** [comment]
\src\discum\discum\gateway\gateway.py
Changing line 88 from `"capabilities": 1021,` to `"capabilities": 509,` fixed it for me. Dunno how good/bad of a solution that is.

**Comment by SerisLyy** [comment]
> \src\discum\discum\gateway\gateway.py Changing line 88 from `"capabilities": 1021,` to `"capabilities": 509,` fixed it for me. Dunno how good/bad of a solution that is.
Thanks bro, I had tried all possible fixes and nothing worked, yours solved my problem.

**Comment by VSeaV** [comment]
> \src\discum\discum\gateway\gateway.py Changing line 88 from `"capabilities": 1021,` to `"capabilities": 509,` fixed it for me. Dunno how good/bad of a solution that is.

thank you. where is this folder located tho?
