### ISSUE TITLE
last_claim_min does not work

### ISSUE THREAD

**Issue by siddagra** [vivinano/MudaeAutoBot#216]
last_claim_min triggers even if there is an hour or more left. Even though it is set to 30.

It also does not keep track of claims to disable further claiming or disable rolling.

```
{
   "token":"NjEzMDg1MTU2OTMyMTkwMjQ0.GIk6yo.AbFlT2xTsG2KQZ9Id5G0Gt158J0DR27D5qvnbg",
   "channel_ids":[
      1002165157000134716
   ],
   "slash_ids":[
      1002165157000134716
   ],
   "slash_guild_ids":[
      1002165157000134716
   ],
   "claim_delay":3,
   "kak_delay":3,
   "use_emoji":"<:keqing_love:795077041761288214>",
   "roll_this":"wg",
   "rolling":"True",
   "slash_rolling":"True",
   "pkmrolling":"True",
   "series_list":[
      "Date A Live"
   ],
   "namelist":[
      "Kurumi Tokisaki"
   ],
   "emoji_list":[
	  "kakera",	
      "kakeraT",
      "kakeraG",
      "kakeraY",
      "kakeraO",
      "kakeraR",
      "kakeraW",
      "kakeraL"
   ],
   "soulemoji_list":[
      "kakeraO",
      "kakeraR",
      "KakeraW",
      "KakeraL"
   ],
   "min_kak":200,
   "Last_True":"True",
   "last_claim_min": 30,
   "min_kak_last_min": 50
}
```
Any way to avoid it claiming/sniping garbage even when there is an hour or more left on the claim reset?

Is there no way to parse the $tu command like https://github.com/JasonYuan869/AutoWaifuClaimerV3 or https://github.com/Znunu/EzMudae does?

**Comment by vivinano** [comment]
The timing is parsed with your $settings mudae as it has thing like the exact minute your claim timer resets as doing a timer up command would have to be made thru sending a message and awaiting response which would be less efficient 

As for stopping rolling it has to receive a response from mudae that you are on cooldown which will stop the roll if there an issue I'll try to troubleshoot it with you try to provide images 


And last min sniping on works with kakera value at the moment and you have it set on > 50

**Comment by vivinano** [comment]
I'll have to check if something in terms of timestamp is messing up I'll let you know if I can reproduce it

**Comment by vivinano** [comment]
after testing last minute claim window works like intended ensure that your settings file is correct as it is used for parsing the variables
