### ISSUE TITLE
Not working in CMD but working in IDLE

### ISSUE THREAD

**Issue by The-guide-00** [vivinano/MudaeAutoBot#217]
So, I've had the bot up and working perfectly for a while now, but I was uninstalled and reinstalled python to try and fix smith else on my system but it ended up breaking the bot,  I've got it to work inside of idle perfectly but when I try to Lauch the .Py file like I had before it just flashes on the screen and closes as if I had configured my Json wrong, if anyone has any tips on how to fix this id love to hear

**Comment by vivinano** [comment]
Well seems like a window environment error So you now probably have multiple installed instances of python as windows computers aren't very smart and you are launching one from your $Path variable that doesnt exist or some type of issue 

That the best I got as I don't really try to deal with environment issues much as that will turn into a very long thread

**Comment by The-guide-00** [comment]
ok thank you so much! this will be really useful to me in fixing it, have a nice day :D
