### ISSUE TITLE
Sorry Viviano, solved my own problem, I can't delete this though <//3.

### ISSUE THREAD

**Issue by The-guide-00** [vivinano/MudaeAutoBot#218]

**Comment by The-guide-00** [comment]
how do i delete a issue <//3

**Comment by The-guide-00** [comment]
they won't let you delete it yourself <//3?

**Comment by cat-chan** [comment]
ig you can only
![image](https://user-images.githubusercontent.com/106933377/200655653-6c0a572f-0ef4-42e8-a285-c2a6ab94edc4.png)
