### ISSUE TITLE
Is there a way to add the add reaction, remove, and then add reaction to bypass the snipe timer with the "new" bot?

### ISSUE THREAD

**Issue by DaMagicFox** [vivinano/MudaeAutoBot#22]
await asyncio.sleep(1)
                        if message.reactions != [] and not message.reactions[0].custom_emoji:
                            emoji = message.reactions[0].emoji
                        await message.add_reaction(emoji)
                        await asyncio.sleep(1)
                        await message.remove_reaction(emoji,self.user)
                        await asyncio.sleep(claim_delay)
                        await message.add_reaction(emoji)

I had added that in the old version of the bot to get the bypass to toggle snipe, how would I do something like it now?

**Comment by vivinano** [comment]
`time.sleep(1)`
`if "reactions" in bot.getMessage(channelid, messageid).json()[0] and bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]['id'] == None:`
`bot.addReaction(channelid, messageid, bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]["name"])`
`time.sleep(1)`
`bot.removeReaction(channelid,messageid,bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]["name"])`
`time.sleep(1)`
`bot.addReaction(channelid, messageid, bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]["name"])`


i think atleast try it out

**Comment by DaMagicFox** [comment]
![image](https://user-images.githubusercontent.com/67620778/117896349-f70ab280-b285-11eb-805b-b61e48e663a3.png)

That is the error I'm getting.

![image](https://user-images.githubusercontent.com/67620778/117896510-549eff00-b286-11eb-97b6-3da481f2b3b1.png)

That is what the code looks like.

**Comment by vivinano** [comment]
That is an python indent error find and fix the correct spacing

**Comment by DaMagicFox** [comment]
> That is an python indent error find and fix the correct spacing

Yeah um, I've been trying for a while and just seem can't see it.

**Comment by vivinano** [comment]
Why is time.sleep not indented ?

**Comment by DaMagicFox** [comment]
> Why is time.sleep not indented ?

Oh wow. That's right, I thought I had to leave all the time.sleep in the same "indent" (don't know the actual term)

**Comment by DaMagicFox** [comment]
> > Why is time.sleep not indented ?
> 
> Oh wow. That's right, I thought I had to leave all the time.sleep in the same "indent" (don't know the actual term)

But It isn't claiming anymore now.

**Comment by vivinano** [comment]
I only translated  the section of code you shown me
It will only claim if their is a reaction and is not a custom emoji because of the if statement

**Comment by DaMagicFox** [comment]
> I only translated the section of code you shown me It will only claim if their is a reaction and is not a custom emoji because of the if statement

Yeah but at least before, even if I did "$im" it added a heart emoji.

**Comment by vivinano** [comment]
Because there was an “else:” that allowed that logic to happen the code that there right now only has a if there is a reaction logic case

**Comment by DaMagicFox** [comment]
> Because there was an “else:” that allowed that logic to happen the code that there right now only reacts if there is a reaction logic case

I don't know where it was then 
![image](https://user-images.githubusercontent.com/67620778/117910255-3b577c00-b2a1-11eb-97c2-60da529738a4.png)

If anything, can I do that again in this code? How?

**Comment by vivinano** [comment]
in the legacy one "emoji" was set by the "if" statement

the new one the "if" does a similar check but instead adds the correct emoji while also running the add_reaction code so it can be added with a "elif" that allows messages without a reaction to also be reacted to

**Comment by DaMagicFox** [comment]
> the "if" does a similar check but instead adds the correct emoji while also running

How could I add an elif so that I can check if it's working? I could maybe have one with elif to see if it is working and then just run the other one.

**Comment by vivinano** [comment]
you could also add an else which doesnt require you to set up a check to add the reaction

**Comment by DaMagicFox** [comment]
> you could also add an else which doesnt require you to set up a check to add the reaction

What do you mean?

**Comment by vivinano** [comment]
so ur current changes only allow 
message with reactions in messages to be reacted to
`if "reactions" in bot.getMessage(channelid, messageid).json()[0] and bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]['id'] == None:`

if you add an "else" statement then it will allow things that don't already have reactions added by mudae to be reacted to

**Comment by DaMagicFox** [comment]
> so ur current changes only allow
> message with reactions in messages to be reacted to
> `if "reactions" in bot.getMessage(channelid, messageid).json()[0] and bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]['id'] == None:`
> 
> if you add an "else" statement then it will allow things that don't already have reactions added by mudae to be reacted to

Sure, how doul I do that? Or basically I would just like to have a way of knowing if the bot is working.

**Comment by vivinano** [comment]
> > `time.sleep(1)`
> > `if "reactions" in bot.getMessage(channelid, messageid).json()[0] and bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]['id'] == None:`
> > `bot.addReaction(channelid, messageid, bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]["name"])`
> > `time.sleep(1)`
> > `bot.removeReaction(channelid,messageid,bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]["name"])`
> > `time.sleep(1)`
> > `bot.addReaction(channelid, messageid, bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]["name"])`
`else: `
`same code as above minus if`

**Comment by DaMagicFox** [comment]
> `time.sleep(1)`
> `if "reactions" in bot.getMessage(channelid, messageid).json()[0] and bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]['id'] == None:`
> `bot.addReaction(channelid, messageid, bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]["name"])`
> `time.sleep(1)`
> `bot.removeReaction(channelid,messageid,bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]["name"])`
> `time.sleep(1)`
> `bot.addReaction(channelid, messageid, bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]["name"])`

Where would I add that?
it would be a way of checking if bot is working with "$im" right?

**Comment by DaMagicFox** [comment]
![image](https://user-images.githubusercontent.com/67620778/117913732-807eac80-b2a7-11eb-9a3f-cae30447322c.png)
I did this but it doesn't try to claim "$im"

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/117914179-c9872e80-b2b0-11eb-85e9-e5e0f7db3aea.png)

doesnt return a reaction because there is no reaction to return in the else case so change it to a reaction

**Comment by DaMagicFox** [comment]
> reaction because there is no reaction to return in the else case so change it to a reaction

Where should I put the "❤"?

**Comment by vivinano** [comment]
> ![image](https://user-images.githubusercontent.com/33008397/117914179-c9872e80-b2b0-11eb-85e9-e5e0f7db3aea.png)

**Comment by DaMagicFox** [comment]
Like this ?
![image](https://user-images.githubusercontent.com/67620778/117915374-c4bf7c00-b2aa-11eb-99a9-8f28fe7077b9.png)

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/117915441-4915fd00-b2b3-11eb-8c64-1ac77413852e.png) , ❤️ )

**Comment by DaMagicFox** [comment]
> ![image](https://user-images.githubusercontent.com/33008397/117915441-4915fd00-b2b3-11eb-8c64-1ac77413852e.png) , ❤️ )

yeah i figured it by looking at the other sections, my bad.

**Comment by vivinano** [comment]
its okay. glad I could help

**Comment by DaMagicFox** [comment]
![image](https://user-images.githubusercontent.com/67620778/117915697-7363bc80-b2ab-11eb-945b-07f4f11fe9d0.png)


> its okay. glad I could help

Then this should be good and should also add reaction on things like "$im"?

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/117915954-410a8d00-b2b4-11eb-80fd-0b26b5d3062f.png)
  
No 
![image](https://user-images.githubusercontent.com/33008397/117916002-554e8a00-b2b4-11eb-89f9-e8e5b98e4463.png)

**Comment by DaMagicFox** [comment]
> ![image](https://user-images.githubusercontent.com/33008397/117915954-410a8d00-b2b4-11eb-80fd-0b26b5d3062f.png)
> 
> No
> ![image](https://user-images.githubusercontent.com/33008397/117916002-554e8a00-b2b4-11eb-89f9-e8e5b98e4463.png)

Huh? so I add it in replacement of where it says "reactions"?

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/117916575-719ef680-b2b5-11eb-88ae-7b772b4d8c89.png)
 
just this remove json to end

**Comment by DaMagicFox** [comment]
> ![image](https://user-images.githubusercontent.com/33008397/117916575-719ef680-b2b5-11eb-88ae-7b772b4d8c89.png)
> 
> just this remove json to end

I did that
![image](https://user-images.githubusercontent.com/67620778/117916957-c8083700-b2ad-11eb-8484-990520a7113c.png)
But now I'm getting this error:
![image](https://user-images.githubusercontent.com/67620778/117917028-e706c900-b2ad-11eb-83d0-98e9ac2040d1.png)

**Comment by vivinano** [comment]
)

**Comment by DaMagicFox** [comment]
> )

? What does that mean?

**Comment by DaMagicFox** [comment]
> )

What do you mean by that?

**Comment by DaMagicFox** [comment]
![image](https://user-images.githubusercontent.com/67620778/117918635-02270800-b2b1-11eb-81b5-a3297d7f4d5a.png)
I did this and there were no errors but no reaction to "$im"

**Comment by vivinano** [comment]
bot.addReaction(channelid,messageid, ❤️ )

**Comment by DaMagicFox** [comment]
> bot.addReaction(channelid,messageid, ❤️ )

yeah but when i have it like that I get the syntax error

**Comment by vivinano** [comment]
show code and the error

**Comment by DaMagicFox** [comment]
![image](https://user-images.githubusercontent.com/67620778/117919059-f5ef7a80-b2b1-11eb-8482-7946a680cd35.png)
Code
![image](https://user-images.githubusercontent.com/67620778/117919146-1a4b5700-b2b2-11eb-8554-363c8b63ae34.png)
Error

**Comment by vivinano** [comment]
that error is because you didnt close your ( ) and that why u have and syntax error

**Comment by DaMagicFox** [comment]
> that error is because you didnt close your ( ) and that why u have and syntax error

Exactly, that's why I added the ")" at the end, but even with that it wasn't reacting to "$im".

I didn't get that you meant that I had to remove the other ( ) as a whole. It's now working, thank you for your support and for being tolerant
