### ISSUE TITLE
Bot claiming the first thing pulled, ignoring series_list or namelist

### ISSUE THREAD

**Issue by ChromCE** [vivinano/MudaeAutoBot#221]
Hello,

I'm trying to configure the bot on my custom server, but i'm unable to make it work.

The bot instant claim the first pull, kinda like issue 193.

![image](https://user-images.githubusercontent.com/118669999/202904526-04276386-e0d0-4375-83be-354a95ca907f.png)

I'm using this as test settings 

![image](https://user-images.githubusercontent.com/118669999/202904625-6fd911fa-b7b2-4293-9009-18837bbde5b3.png)

And as you can see, it ignore both

I do have a wishlist, i added 2 differents character( not from the namelist nor series_list), and its public, with $wishdm Y N N 

Any idea? 

Also additionnal question, if it set 

>    "series_list":[
>       "" 
>     ],

      
  The script will ignore this series_list? or accept anything?

**Comment by vivinano** [comment]
The wishing snipe works off of your @ when a wish pops up along with your userID so if those match it will snipe

**Comment by ChromCE** [comment]
> The wishing snipe works off of your @ when a wish pops up along with your userID so if those match it will snipe

Ok, so for WL snipe to work, the public ping have to be up.

But for the instant claim? you have an idea?

**Comment by vivinano** [comment]
it seems like this is a settings issue as somehow its finding Kill la Kill in a null variable and returning true

**Comment by ChromCE** [comment]
Hmmm, so if i remove it, and use "" it will be the same? since there is no series named _null_ ? i shall add at least once ?

**Comment by vivinano** [comment]
you can add something like AAAAAAAAA or BBBBBBB something that will never be true

**Comment by ChromCE** [comment]
Ok, i will test with those, to force ignore the series_list and check if it instant claim again

**Comment by ChromCE** [comment]
Ok, it seems to work, it took some time since i was the only one pulling on my test server, but the bot reacted correctly
