### ISSUE TITLE
Works fine, until it just stops working after some time?

### ISSUE THREAD

**Issue by cpryz** [vivinano/MudaeAutoBot#223]
it works fine until it just stops working after a random amount of time and i have to restart again.

**Comment by Seonius** [comment]
I have the same issue

**Comment by BellaDona007** [comment]
I have also faced this problem, it works fine for a few minutes, the bot even registers that they are rolling, but it doesn't do any action like picking up kakera or character.

**Comment by whaleiodas** [comment]
hello, may i ask you how you can run the bot bc there is no .exe 
or if its in cdm can someone explain to me how it works step by step

**Comment by vivinano** [comment]
You can enable gateway logs and then let me know what happens during the time frame that it stops is all I can ask for as it hasn't happened to me personally

**Comment by cpryz** [comment]
might be a silly question but how do i enable gateway logs?

**Comment by vivinano** [comment]
Change to logging to true Sent from my iPhoneOn Jan 12, 2023, at 10:56 PM, cpryz ***@***.***> wrote:﻿
might be a silly question but how do i enable gateway logs?

**Comment by cpryz** [comment]
you mean this?
![image](https://user-images.githubusercontent.com/22884222/212449293-54dbb22a-69b1-48fc-8699-ad087cfdc628.png)

**Comment by vivinano** [comment]
Yeah that is a discum command tho Sent from my iPhoneOn Jan 13, 2023, at 10:46 PM, cpryz ***@***.***> wrote:﻿
you mean this?

**Comment by cpryz** [comment]
im not that great with code stuff sorry ahahaha

**Comment by cpryz** [comment]
![image](https://user-images.githubusercontent.com/22884222/212466048-667ad8c7-7ebb-421a-8a41-0ddf7b2bc797.png)
this is what im getting with the discum log btw

**Comment by vivinano** [comment]
This is when it fails right ? Sent from my iPhoneOn Jan 14, 2023, at 4:47 AM, cpryz ***@***.***> wrote:﻿

this is what im getting with the discum log btw

**Comment by cpryz** [comment]
yep, basically when it stops working, the bottom part just repeats forever

**Comment by vivinano** [comment]
Make sure your using the latest version of discum and then if it still persist let the developer of discum know as it part of their repo Sent from my iPhoneOn Jan 14, 2023, at 7:25 AM, cpryz ***@***.***> wrote:﻿
yep, basically when it stops working, the bottom part just repeats forever

**Comment by BellaDona007** [comment]
here I'm having to open several bot pro same channel and even then some don't work, or stop working, being forced to close everything and reopen every 10~20 minutes 
![image](https://user-images.githubusercontent.com/82736191/215570088-0bc18acf-6cbc-412c-839a-9211cbc04a41.png)

**Comment by vivinano** [comment]
going to close for now 
if issue still persist please update with basic trouble shooting being done 
I've tested bot now for 10 hours without any issues ib 2/20/2023
