### ISSUE TITLE
idk how to install the bot 

### ISSUE THREAD

**Issue by whaleiodas** [vivinano/MudaeAutoBot#224]
hello, may i ask you how you can run the bot,bc i tried in IDLE and its says restart something but theres nothing happening
![gdfgnhhjuztrtfdghuji](https://user-images.githubusercontent.com/122222754/211700435-34caec88-5b52-4a40-b241-b8ecdf001eb9.png)
and should it roll on discord app or web

or if its in cdm or python can someone explain to me how it works step by step or reply to me with images 
the reason is im not very good in the tech world and theres no instruction how to do all of this

thank you

**Comment by vivinano** [comment]
You should just be able to load your discord token and be good to go within idle if you like

**Comment by whaleiodas** [comment]
> You should just be able to load your discord token and be good to go within idle if you like

i already pasted my token into JSON in the idle i pasted but it didnt work

**Comment by vivinano** [comment]
Any error ? That pops up Sent from my iPhoneOn Jan 13, 2023, at 3:41 AM, shalanor ***@***.***> wrote:﻿

You should just be able to load your discord token and be good to go within idle if you like

i already pasted my token into JSON in the idle i pasted but it didnt work
