### ISSUE TITLE
Bot impossible to use

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#227]
The bot is needing to be reopened every 10 minutes (because it stops working and you don't even notice) and open several instances, to ensure that some will work, unfortunately I don't know if this is because the bot is 1 year outdated or is due to something in the Dis.c.u.m, unfortunately I don't even know what I should ask on the Dis.c.u.m forum to know if it is something there.
Is there anyone who is having this problem and has found a solution to this problem or also managed to implement the kakera Button?
I understand that for the creator of the bot must have been uninteresting the project for not playing mudae anymore or even for not receiving support from users, I myself would help if the currency of my country was strong or 1:1 with the dollar.
Unfortunately having to reopen the bot every time and have to open several to ensure that some work, ends up taking the practicality that it should provide 

I am using python 3.9 and DisCum 1.4.1

Translated with www.DeepL.com/Translator (free version)

**Comment by vivinano** [comment]
Cant fix something that is not happening to me and if it falls into discum example gateway not reconnecting is something i can't fix
