### ISSUE TITLE
Seem to be having an issue preventing the bot from just claiming the first character it sees. 

### ISSUE THREAD

**Issue by zerlure** [vivinano/MudaeAutoBot#228]
Looking through the settings I don't see what I have missed. I have characters filled out. My last 4 lines are:

   "min_kak":500,
   "Last_True":"False",
   "last_claim_min": 10,
   "min_kak_last_min": 60
}
I didn't put anything under series, does that cause it to look at all series? Is there a way to do like, [Series] >150 ?

**Comment by JuliaYuki** [comment]
Did you manage to solve? Mine is also claiming the first character it sees

**Comment by vivinano** [comment]
So if it's in the last min window it will snipe whatever falls within that range Sent from my iPhoneOn Jun 17, 2023, at 9:21 PM, JuliaYuki ***@***.***> wrote:﻿
Did you manage to solve? Mine is also claiming the first character it sees

**Comment by JuliaYuki** [comment]
How do you resolve this? Change something about snipe in MudaeAutoBot.py or settings_mudae?

**Comment by vivinano** [comment]
Changing the last minute setting in settingsSent from my iPhoneOn Jun 17, 2023, at 11:10 PM, JuliaYuki ***@***.***> wrote:﻿
How do you resolve this? Change something about snipe in MudaeAutoBot.py or settings_mudae?

**Comment by JuliaYuki** [comment]
Thank you!
