### ISSUE TITLE
Bot not parsing sniping delay correctly

### ISSUE THREAD

**Issue by m-cf-b** [vivinano/MudaeAutoBot#233]
For some reason it does not parse the sniping time correctly and tries to snipe with 1 second
[channel.txt](https://github.com/vivinano/MudaeAutoBot/files/11181230/channel.txt)

**Comment by vivinano** [comment]
Sniping time is set in the Json Sent from my iPhoneOn Apr 7, 2023, at 4:02 PM, m-cf-b ***@***.***> wrote:﻿
For some reason it does not parse the sniping time correctly and tries to snipe with 1 second
channel.txt

**Comment by m-cf-b** [comment]
The default would be 8 seconds for claim_delay, but that time is only valid if there is no delay in the server right? Or am I seeing the wrong variable?

**Comment by vivinano** [comment]
What are you wanting it to do delay a couple of seconds ? Sent from my iPhoneOn Apr 8, 2023, at 10:32 PM, m-cf-b ***@***.***> wrote:﻿
The default would be 8 seconds for claim_delay, but that time is only valid if there is no delay in the server right? Or am I seeing the wrong variable?

**Comment by m-cf-b** [comment]
The server in question has the default togglesnipe 2 with 8 seconds delay, but the bot tries to snipe with 1 second of the roll. I tried increasing the claim delay but it didn't work.

**Comment by vivinano** [comment]
if that the case you can go into the code and there should be a snipe function that you should manually be able to add a delay too. not sure why its not set up as it should be defined in get snipe time function based on your channel claim number

**Comment by m-cf-b** [comment]
I find it weird as well because it is parsing the roll time correctly
but here is some outputs from my term

I also checked and the claim was available

The mudae message was at 2023-04-13 18:12:35,919
2023-04-13 18:12:35,990:Venti from Genshin Impact appeared attempting to snipe in ###             
2023-04-13 18:12:37,128:Sniping time waited Reaction was added                                                          
2023-04-13 18:12:37,139:Venti with a 503 Kakera Value appeared Server:###

Here is my setting files just in case
[Settings_Mudae.txt](https://github.com/vivinano/MudaeAutoBot/files/11228325/Settings_Mudae.txt)

**Comment by vivinano** [comment]
So the claim delay is set to a more automated delay time I think the claim delay I made more of a fall back
