### ISSUE TITLE
the kakera does not react

### ISSUE THREAD

**Issue by kiliss** [vivinano/MudaeAutoBot#234]
I tried the bot but it doesn't react when kakera appears, any solution?

**Comment by vivinano** [comment]
Haven’t gotten to adding button support for kakera only for claims Sent from my iPhoneOn Apr 12, 2023, at 6:56 PM, Fabricio Cuevas ***@***.***> wrote:﻿
I tried the bot but it doesn't react when kakera appears, any solution?
