### ISSUE TITLE
Bot stops working after 1h open

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#236]
My bot works "normal" for an hour, I say normal, because I have to open 3 or more bots to be sure it works, because some open ones do not work
If you let the bot roll, it will be running infinitely after 1h

Does anyone have a solution for this, I reinstalled the bot and the problem still continues.
In case someone doesn't have this problem, could you please inform the version of Python and discum?

**Comment by vivinano** [comment]
tested and this is not a issue
