### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by KosakiAjami** [vivinano/MudaeAutoBot#237]
![image](https://github.com/vivinano/MudaeAutoBot/assets/61561851/67e6e862-6466-4528-aa4d-d17d434552b9)
Have this error can someone help me please?

**Comment by vivinano** [comment]
You might have the wrong token it seems like your failing the access to gateway hence everything is probably returning empty

**Comment by KosakiAjami** [comment]
Don't think so because I tried to connect to discord with the token and it works do u have discord please it will be more simple to communicate?

**Comment by KosakiAjami** [comment]
I tried to dl old release of mudaebot and all works fine but it doesn't react with the embed message so I don't know It set a reaction and that's all

**Comment by Kaizuk-O** [comment]
I'm having the same thing, old release works fine but doesn't react with embeds on the new one

**Comment by vivinano** [comment]
I’ll check it out Sent from my iPhoneOn May 21, 2023, at 3:34 PM, Kaizuk-O ***@***.***> wrote:﻿
I'm having the same thing, old release works fine but doesn't react with embeds on the new one

**Comment by Kaizuk-O** [comment]
Let me know if you have an update, thanks!

**Comment by Kaizuk-O** [comment]
Did you find anything or do you need any details off me? 😅

**Comment by vivinano** [comment]
I've tested the bot on my account and it seems to be running fine 

Are you guys obtaining the $settings option or no

**Comment by ilyoni** [comment]
It tries to obtain the $settings but when I do it, it cant find the settings even though it's there even after restarting the bot multiple times

**Comment by vivinano** [comment]
Is there a setting that you can show me cause it searches a specific term so can you screenshot it Sent from my iPhoneOn May 26, 2023, at 2:54 PM, ilyoni ***@***.***> wrote:﻿
It tries to obtain the $settings but when I do it, it cant find the settings even though it's there even after restarting the bot multiple times

**Comment by Kaizuk-O** [comment]
Hi, so I just did a $settings in the server and cleared the channel data as well:
![Screenshot 2023-05-26 221214](https://github.com/vivinano/MudaeAutoBot/assets/89078343/24e6384f-9b88-4470-8edf-538f1f80aad1)
![Screenshot 2023-05-26 221305](https://github.com/vivinano/MudaeAutoBot/assets/89078343/25d15d25-1ba2-410e-887c-6f5f3f5024df)
![Screenshot 2023-05-26 221447](https://github.com/vivinano/MudaeAutoBot/assets/89078343/d73d82d3-26fb-40f9-badb-f69406e4e273)


I've attached my bot settings too - is there anything out of the ordinary? I'm assuming it's the same for ilyoni seeing as they've got the same error as mine?

**Comment by ilyoni** [comment]
Yeah, [
![image](https://github.com/vivinano/MudaeAutoBot/assets/80600288/f434af39-c47a-4b5a-9d19-c52051ebb5ce)
[](url)](![image](https://github.com/vivinano/MudaeAutoBot/assets/80600288/490ed1c9-821d-4fd9-b363-3c200b9377f7))

**Comment by ilyoni** [comment]
This also happens in non-premium servers ^

**Comment by ilyoni** [comment]
Yeah, same problem except the settings file is there but it still can't read it and the other error listed

**Comment by vivinano** [comment]
Is it a hidden file or somethingSent from my iPhoneOn May 26, 2023, at 9:10 PM, ilyoni ***@***.***> wrote:﻿
Yeah, same problem except the settings file is there but it still can't read it and the other error listed

**Comment by ilyoni** [comment]
No because it creates the file but after a restart it wont read it [
![image](https://github.com/vivinano/MudaeAutoBot/assets/80600288/e08e11f8-2bc6-4d00-b4b8-4d7b6c0d2478)
[
![image](https://github.com/vivinano/MudaeAutoBot/assets/80600288/8224a781-632a-4471-8bf9-af1028caf074)
]([]([](url)](![image](https://github.com/vivinano/MudaeAutoBot/assets/80600288/bad9ae9e-c163-4c02-8e64-1a784e2408c2))))

**Comment by ilyoni** [comment]
[
![image](https://github.com/vivinano/MudaeAutoBot/assets/80600288/0f483baa-86c7-4beb-b5ba-d1cef12687ab)
](url)

**Comment by Kaizuk-O** [comment]
Yep, just can't seem to figure out why it won't even create a channeldata file for me, just gives the error I've posted on the earlier comment - is there something missing from my bot settings file that is possibly causing this?

**Comment by vivinano** [comment]
If necessary you could just manually copy and paste the settings you must need the bold asterisks around the values And also with the setting file there is it showing the ?? As a file specific thing or is it just for show type thing like IDE intellsense markings Sent from my iPhoneOn May 27, 2023, at 6:34 AM, Kaizuk-O ***@***.***> wrote:﻿
Yep, just can't seem to figure out why it won't even create a channeldata file for me, just gives the error I've posted on the earlier comment - is there something missing from my bot settings file that is possibly causing this?

**Comment by Kaizuk-O** [comment]
```
{
   "token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxF6Q",
   "channel_ids":[
	  XXXXXXXXXXXXXXXX15
   ],
   "slash_ids":[
	  
   ],
   "slash_guild_ids":[
      
   ],
   "claim_delay":1,
   "kak_delay":1,
   "use_emoji":"<:keqing_love:795077041761288214>",
   "roll_this":"ma",
   "rolling":"True",
   "slash_rolling":"False",
   "pkmrolling":"True",
   "series_list":[
      
   ],
   "namelist":[
      
   ],
   "emoji_list":[
	  "kakera",	
      "kakeraR",
      "kakeraW",
      "kakeraL"
   ],
   "soulemoji_list":[
      "kakeraO",
      "kakeraR",
      "KakeraW",
      "KakeraL"
   ],
   "min_kak":300,
   "Last_True":"True",
   "last_claim_min": 61,
   "min_kak_last_min": 10
}

```

So above are my settings for the bot - what do you reckon needs to be changed? Also not sure what you mean by is it showing the ?? as a file specific thing?

**Comment by vivinano** [comment]
So you’re able to get a channeldata file ? Or not Sent from my iPhoneOn May 27, 2023, at 7:57 AM, Kaizuk-O ***@***.***> wrote:﻿
{
   "token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxF6Q",
   "channel_ids":[
	  XXXXXXXXXXXXXXXX15
   ],
   "slash_ids":[
	  
   ],
   "slash_guild_ids":[
      
   ],
   "claim_delay":1,
   "kak_delay":1,
   "use_emoji":"<:keqing_love:795077041761288214>",
   "roll_this":"ma",
   "rolling":"True",
   "slash_rolling":"False",
   "pkmrolling":"True",
   "series_list":[
      
   ],
   "namelist":[
      
   ],
   "emoji_list":[
	  "kakera",	
      "kakeraR",
      "kakeraW",
      "kakeraL"
   ],
   "soulemoji_list":[
      "kakeraO",
      "kakeraR",
      "KakeraW",
      "KakeraL"
   ],
   "min_kak":300,
   "Last_True":"True",
   "last_claim_min": 61,
   "min_kak_last_min": 10
}


So above are my settings for the bot - what do you reckon needs to be changed? Also not sure what you mean by is it showing the ?? as a file specific thing?

**Comment by Kaizuk-O** [comment]
Nope, with those settings, when I run the bot, I'm not able to generate a channeldata file at all, it throws the error as soon as the bot starts and says list index out of range - just as shown in my earlier screenshot

**Comment by vivinano** [comment]
Alright try to copy paste the settings manually and rename it the channel Id number and remember to put the bold asterisk and see if it’s just the search function Cause I know if channel is marked nsfw the search function doesn’t work Sent from my iPhoneOn May 27, 2023, at 8:24 AM, Kaizuk-O ***@***.***> wrote:﻿
Nope, with those settings, when I run the bot, I'm not able to generate a channeldata file at all, it throws the error as soon as the bot starts and says list index out of range - just as shown in my earlier screenshot

**Comment by Kaizuk-O** [comment]
Just tried that, made sure to use the bold asterisks and checked the channel is definitely not an NSFW one as well:

```
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000021931F7C760>>
Traceback (most recent call last):
  File "C:\Users\XXXXX\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "D:\XXXXX\XXXXXXXX\XXXXXXXX\XXXXXXXXXX\MudaeAutoBot.py", line 776, in on_message
    bot.gateway.request.searchSlashCommands(str(ghids[0]), limit=100, command_ids=[])
IndexError: list index out of range


```

Still getting the above

**Comment by vivinano** [comment]
That a different error actually I think you just need to put the correct ids into the slash id field since if your enabled slash commands that needs to be set in settings mudae Sent from my iPhoneOn May 27, 2023, at 10:22 AM, Kaizuk-O ***@***.***> wrote:﻿
Just tried that, made sure to use the bold asterisks and checked the channel is definitely not an NSFW one as well:
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000021931F7C760>>
Traceback (most recent call last):
  File "C:\Users\XXXXX\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "D:\XXXXX\XXXXXXXX\XXXXXXXX\XXXXXXXXXX\MudaeAutoBot.py", line 776, in on_message
    bot.gateway.request.searchSlashCommands(str(ghids[0]), limit=100, command_ids=[])
IndexError: list index out of range



Still getting the above

**Comment by Kaizuk-O** [comment]
So I've tried that and now it reads the channeldata file, but this is the error now:
```

Reading from File for channel XXXXXXXXXXXXXXXX715
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000002216EA6F630>>
Traceback (most recent call last):
  File "C:\XXXXXXXXX\XXXXXXX\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "D:\XXXXX\XXXXXXXX\XXXXX\XXXXXXXXXXXXXXXXXXXXXXXX\MudaeAutoBot.py", line 784, in on_message
    c_settings = parse_settings_message(msg)
  File "D:\XXXXX\XXXXXXXX\XXXXX\XXXXXXXXXXXXXXXXMudaeAutoBot.py", line 237, in parse_settings_message
    settings['claim_snipe'][0] = int(settings['claim_snipe'][0])
IndexError: list index out of range

```

any ideas?

**Comment by Kaizuk-O** [comment]
Also, it is now able to create a channeldata file from scratch too... progress! 😄

**Comment by vivinano** [comment]
alright now what is inside that file

**Comment by Kaizuk-O** [comment]
This is what's inside the channeldata file: 

`_ __**Server Settings**__ _
(Server not premium)

· Prefix: **$** ($prefix)
· Lang: **en** ($lang)
· Claim reset: every **180** min. ($setclaim)
· Exact minute of the reset: xx:**00** ($setinterval)
· Reset shifted: by +**0** min. ($shifthour)
· Rolls per hour: **8** ($setrolls)
· Time before the claim reaction expires: **45** sec. ($settimer)
· Spawn rarity multiplicator for already claimed characters: **4** ($setrare)
· Server game mode: **2** ($gamemode)
· $servlimroul = 7000 $wa, 7000 $ha, 4000 $wg, 4000 $hg
· This channel instance: **1** ($channelinstance)
· Slash commands: enabled ($toggleslash)

· Ranking: enabled ($toggleclaimrank/$togglelikerank)
· Ranks displayed during rolls: claims and likes ($togglerolls)
· Hentai series: enabled ($togglehentai)
· Disturbing imagery series: enabled ($toggledisturbing)
· Child characters: enabled ($togglechildtag)
· Rolls sniping: 0 ($togglesnipe)
· Kakera sniping: 0 ($togglekakerasnipe)
· Limit of characters per harem: **8100** ($haremlimit)
· Reacts: ****for all your rolls**** ($togglereact)
· Custom reactions: no ($claimreact)
· Kakera reactions more recognizable: no ($kakerareact switchset)

· Kakera trading: enabled ($togglekakeratrade)
· Kakera calculation: **like ranks only** (and number of claimed characters) ($togglekakeraclaim/$togglekakeralike)
· Kakera value displayed during rolls: enabled ($togglekakerarolls)
· $kakeraloot wishprotect: enabled ($togglewishprotect)`

**Comment by Kaizuk-O** [comment]
Side note: I noticed the 4 asterisks around the 'for all your rolls' and removed two to make it bold - still gives the same error as before

**Comment by Veirt** [comment]
Hello @vivinano, I made a pull request regarding this issue. Can you review #241?

**Comment by idontsmokegas** [comment]
does anyone know how to fix this?

**Comment by bycEEE** [comment]
@idontsmokegas I put up #251 cause I'm running into the same thing.
