### ISSUE TITLE
Vivinano i need help

### ISSUE THREAD

**Issue by MissileKey** [vivinano/MudaeAutoBot#239]
i came across the bot and im new i need help setting it up if anyone can help me my discord is Qip#0069

**Comment by vivinano** [comment]
what is the issue

**Comment by MissileKey** [comment]
i have no idea what im doing like i dont even know what to do first

**Comment by vivinano** [comment]
get discord user token

**Comment by MissileKey** [comment]
i got the channel id and user token but i need to know like how to run it

**Comment by vivinano** [comment]
You can just run it in CMD Sent from my iPhoneOn May 28, 2023, at 1:27 PM, MissileKey ***@***.***> wrote:﻿
i got the channel id and user token but i need to know like how to run it
