### ISSUE TITLE
Program closes after time?

### ISSUE THREAD

**Issue by RecentYogurt** [vivinano/MudaeAutoBot#24]
I don't really know if its replicable but I think the program just closes after being left open for a while. I'm not sure if this is an issue on my end.

**Comment by vivinano** [comment]
https://github.com/Merubokkusu/Discord-S.C.U.M/issues/65

this was listed in the current issue. it is an issue with discum they have said that they have made changes to their gateway.py if this issues arises then add onto the issue linked so it helps with the issue on their end

**Comment by RecentYogurt** [comment]
I'll try it out 👍

**Comment by vivinano** [comment]
so far the bot hasn't crashed after 12 hour of use. gonna keep it running for longer but it seems to be okay but hasnt been using multi server watching and stuff so let me know. how yours go so I can let the dev of discum know the status of their changes

**Comment by vivinano** [comment]
Ive been running the bot for 24hours no issues have arose gonna close this issue for now @RecentYogurt feel free to reopen if you still have issues
