### ISSUE TITLE
changing emoji

### ISSUE THREAD

**Issue by snickermigger** [vivinano/MudaeAutoBot#242]
hey I have a question, do you think you could guide me better on how to change the reaction emoji to the claim? thanks

**Comment by snickermigger** [comment]
any help

**Comment by vivinano** [comment]
Use to use custom emojis but instead it now uses the first button or reaction that is listed and since mudae is switching off of emoji support over to buttons Sent from my iPhoneOn Jun 17, 2023, at 8:10 AM, snickermigger ***@***.***> wrote:﻿
any help

**Comment by snickermigger** [comment]
i didnt understand what u meant sorry, is it impossible to change now is that what u meant?

**Comment by snickermigger** [comment]
is there anyway i can put something else reacting instead of the heart and if there is a way how?

**Comment by snickermigger** [comment]
still waiting on help

**Comment by vivinano** [comment]
you can still change it if it just the emoji but you will have to uncomment out code or just change it so it applies custom emoji Sent from my iPhoneOn Jun 20, 2023, at 4:48 AM, snickermigger ***@***.***> wrote:﻿
still waiting on help

**Comment by snickermigger** [comment]
okay and what part of the code exactly do I have to uncomment and change because I've been through the code and unfortunately my coding skills are very limited and I cant figure where I should change, if you could help on that it'd be great :)

**Comment by vivinano** [comment]
you could switch to a older version and see the differences between them and you should be able to get that snippnet of code other than that someone else can assist sorry. But It was easier to take away custom options as I already get enough issues on settings
