### ISSUE TITLE
KeyError: 'guilds'

### ISSUE THREAD

**Issue by MaSangtae** [vivinano/MudaeAutoBot#247]
Doesn't claim any kakera but everything else worked fine on most of the accounts I tried using it on but I did get this error whenever I ran the bot on a specific account.

![image](https://github.com/vivinano/MudaeAutoBot/assets/114552700/ec82648d-c8d9-437b-9d8d-9a39d29d218a)

This account was in over 100+ servers while the other accounts were only in 2-3 so I think that might have been the problem. Is there any way to fix this without having to leave any of my servers? I could alt but I don't really feel like starting over.

**Comment by sieucapoccho3717** [comment]
I'm having the same issue and not sure what's the cause in my case
![image](https://github.com/vivinano/MudaeAutoBot/assets/124008590/df35495a-e8bc-4d15-8499-80dd60192595)

**Comment by vivinano** [comment]
seems like the "fix" to user just runs into another issue which is now guild

**Comment by MaSangtae** [comment]
How do I get a dump of all my guilds? I've made an empty guild.txt file but I don't really know what format/syntax I should be using. Should I just go through all my servers and get the guild ids that way?
![image](https://github.com/vivinano/MudaeAutoBot/assets/114552700/03bbbced-00cc-44ad-a007-106389b6d5b5)

**Comment by nuuvemold** [comment]
![image](https://github.com/vivinano/MudaeAutoBot/assets/48504747/aa01c547-6321-4cc2-b20e-c42902d9040f)
This is the error I get, this is my first time trying to run the script, and this is my configuration
![image](https://github.com/vivinano/MudaeAutoBot/assets/48504747/2fbeb55e-fbc1-4039-b8a1-c4122537237d)
