### ISSUE TITLE
Please Help Me

### ISSUE THREAD

**Issue by Nicksw21** [vivinano/MudaeAutoBot#249]
Hello im new to python and the auto mudae bot so i know less than nothing. Im getting this error when i run the code:
Traceback (most recent call last):
  File "C:\Users\nicos\Desktop\MudaeAutoBot-4\MudaeAutoBot.py", line 10, in <module>
    from discum.utils.slash import SlashCommander
ModuleNotFoundError: No module named 'discum.utils'; 'discum' is not a package
What can i do to fix it?
Thank you

**Comment by vivinano** [comment]
Install discum library Sent from my iPhoneOn Jul 20, 2023, at 12:22 AM, Nicksw21 ***@***.***> wrote:﻿
Hello im new to python and the mudae bot so i know less than nothing. Im getting this error when i run the code:
Traceback (most recent call last):
File "C:\Users\nicos\Desktop\MudaeAutoBot-4\MudaeAutoBot.py", line 10, in 
from discum.utils.slash import SlashCommander
ModuleNotFoundError: No module named 'discum.utils'; 'discum' is not a package
What can i do to fix it?
Thank you

**Comment by Nicksw21** [comment]
Thats the problem i already have the library installed it just says that it cant find the module named 'discum.utils', and that discum is not a package. I did paste this "python -m pip install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git#egg=discum" so it should be there.

**Comment by vivinano** [comment]
Could be a multi instance of python issue Sent from my iPhoneOn Jul 20, 2023, at 12:04 PM, Nicksw21 ***@***.***> wrote:﻿
Thats the problem i already have the library installed it just says that it cant find the module named 'discum.utils', and that discum is not a package. I did paste this "python -m pip install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git#egg=discum" so it should be there.

**Comment by Nicksw21** [comment]
Sorry i dont really know much about python can you tell me what to do to try and fix it?

**Comment by Nicksw21** [comment]
Should i try to make a virtual enviroment and try there or what do i do?

**Comment by Nicksw21** [comment]
Nope tried it in a virtual enviroment within the MudaeAutoBot-main folder and its the same error
Traceback (most recent call last):
  File "C:\Users\nicos\Desktop\MudaeAutoBot-main\MudaeAutoBot.py", line 10, in <module>
    from discum.utils.slash import SlashCommander
ModuleNotFoundError: No module named 'discum.utils'; 'discum' is not a package
i installed discum again in that enviroment and executed the MudaeAutoBot.py but nothing. Same error

**Comment by vivinano** [comment]
Windows 10 just has issues with installation of python it wants to install the windows store version and not the stand alone one which then causes issues Sent from my iPhoneOn Jul 20, 2023, at 12:28 PM, Nicksw21 ***@***.***> wrote:﻿
Nope tried it in a virtual enviroment within the MudaeAutoBot-main folder and its the same error
Traceback (most recent call last):
File "C:\Users\nicos\Desktop\MudaeAutoBot-main\MudaeAutoBot.py", line 10, in 
from discum.utils.slash import SlashCommander
ModuleNotFoundError: No module named 'discum.utils'; 'discum' is not a package
i installed discum again in that enviroment and executed the MudaeAutoBot.py but nothing. Same error

**Comment by Nicksw21** [comment]
So what should i do?

**Comment by vivinano** [comment]
determine if you have 2 instances of python you can use programs like search everything and see if that is the case

**Comment by Nicksw21** [comment]
![image](https://github.com/vivinano/MudaeAutoBot/assets/140040295/76ae9eb7-bc0a-4d87-83e1-661b3674e4ad)
I used search everything and got this. I dont know how to recognise 2 instances

**Comment by vivinano** [comment]
If you open idle and run import discum what does it do Sent from my iPhoneOn Jul 20, 2023, at 1:35 PM, Nicksw21 ***@***.***> wrote:﻿

I used search everything and got this. I dont know how to recognise 2 instances

**Comment by Nicksw21** [comment]
it says: = RESTART: C:/Users/nicos/AppData/Local/Programs/Python/Python311/discumtest.py

**Comment by vivinano** [comment]
Feel like a test version of discum was installed then it seems I’m not seeing the error or your windows version so I’m unsure Sent from my iPhoneOn Jul 20, 2023, at 1:51 PM, Nicksw21 ***@***.***> wrote:﻿
it says: = RESTART: C:/Users/nicos/AppData/Local/Programs/Python/Python311/discumtest.py

**Comment by Nicksw21** [comment]
this are the specifications of the discum i have installed
![image](https://github.com/vivinano/MudaeAutoBot/assets/140040295/6b9b075d-da2d-4d28-88e0-1070f089b8d1)

**Comment by vivinano** [comment]
These are the version I’m using but it might not work forever one Sent from my iPhoneOn Jul 20, 2023, at 3:09 PM, Nicksw21 ***@***.***> wrote:﻿
Should i try uninstalling everything (python and discum) and installing the recommended versions python 3.7 and discum 1.3?

**Comment by Nicksw21** [comment]
Alright ill try that and let you know what happens

**Comment by Nicksw21** [comment]
Okay so i made some progress, the old error no longer appears instead a new one happens: 
![image](https://github.com/vivinano/MudaeAutoBot/assets/140040295/c7a6b067-bfca-4e89-b903-d57f3ce01de8)
this happens when i execute the MudaeAutoBot.py script with python i already configured my settings and token, all that stuff.
Any clue what it is?

**Comment by Nicksw21** [comment]
Here are my settings if they help:
{
   "token":"token removed for security lol imagine like its here",
   "channel_ids":[
	  992894625100611604
   ],
   "slash_ids":[
	  992894625100611604
   ],
   "slash_guild_ids":[
      992894625100611604
   ],
   "claim_delay":1,
   "kak_delay":1,
   "use_emoji":"<:keqing_love:795077041761288214>",
   "roll_this":"wa",
   "rolling":"True",
   "slash_rolling":"True",
   "pkmrolling":"True",
   "series_list":[
      "Megumin"
   ],
   "namelist":[
      "Megumin",
      "Mai Sakurajima",
      "Nezuko Kamado",
      "Rias Gremory",
      "Saber",
      "Mikasa Ackerman",
      "Hatsune Miku",
      "Power",
      "Albedo",
      "Miku Nakano",
      "Nami",
   ],
   "emoji_list":[
	  "kakera",	
      "kakeraY",
      "kakeraO",
      "kakeraR",
      "kakeraW",
      "kakeraL"
   ],
   "soulemoji_list":[
      "kakeraO",
      "kakeraR",
      "KakeraW",
      "KakeraL"
   ],
   "min_kak":500,
   "Last_True":"True",
   "last_claim_min": 61,
   "min_kak_last_min": 10
}

**Comment by vivinano** [comment]
You got an extra comma somewhere is a validator on your json file Sent from my iPhoneOn Jul 20, 2023, at 5:26 PM, Nicksw21 ***@***.***> wrote:﻿
Here are my settings if they help:
{
"token":"token removed for security lol imagine like its here",
"channel_ids":[
992894625100611604
],
"slash_ids":[
992894625100611604
],
"slash_guild_ids":[
992894625100611604
],
"claim_delay":1,
"kak_delay":1,
"use_emoji":"<:keqing_love:795077041761288214>",
"roll_this":"wa",
"rolling":"True",
"slash_rolling":"True",
"pkmrolling":"True",
"series_list":[
"Megumin"
],
"namelist":[
"Megumin",
"Mai Sakurajima",
"Nezuko Kamado",
"Rias Gremory",
"Saber",
"Mikasa Ackerman",
"Hatsune Miku",
"Power",
"Albedo",
"Miku Nakano",
"Nami",
],
"emoji_list":[
"kakera",
"kakeraY",
"kakeraO",
"kakeraR",
"kakeraW",
"kakeraL"
],
"soulemoji_list":[
"kakeraO",
"kakeraR",
"KakeraW",
"KakeraL"
],
"min_kak":500,
"Last_True":"True",
"last_claim_min": 61,
"min_kak_last_min": 10
}

**Comment by Nicksw21** [comment]
Ok so i fixed that but now i get this: 
![image](https://github.com/vivinano/MudaeAutoBot/assets/140040295/a6f5a502-c174-45cf-93e3-371a0be56340)

**Comment by vivinano** [comment]
Pushed a merge apprently mudae added a new variable in the settings list

**Comment by Nicksw21** [comment]
ill update the fil, try it, and let you know what happens.

**Comment by Nicksw21** [comment]
Ok works perfectly now, just one question what should i put in "series_list":[ if i dont want it to roll any series. Because i left it empty and its just claiming anything that is not listed i just want the bot to snipe the characters i wrote in "namelist":[

**Comment by JuliaYuki** [comment]
> 

just put some random characters

"series_list": ["¶"],

**Comment by Nicksw21** [comment]
alr

**Comment by Nicksw21** [comment]
ill put that one

**Comment by JuliaYuki** [comment]
That work for me ;)

**Comment by Nicksw21** [comment]
thank you very very much for your help, and sorry for bothering you so much!

**Comment by Nicksw21** [comment]
Also one more question in "min_kak" if i put 500 it will snipe any character with 500+ regardless of the restrictions i put right?

**Comment by JuliaYuki** [comment]
yup, will claim any 500+ character and if you have a -500kak character in the "namelist", it will claim too

**Comment by Nicksw21** [comment]
Thank you!!

**Comment by Nicksw21** [comment]
Will abuse this

**Comment by JuliaYuki** [comment]
be happy xD

**Comment by Nicksw21** [comment]
I put the ["¶"] in series list and its still sniping anything it finds. What can i put there to disable series list or something?

**Comment by JuliaYuki** [comment]
this is strange as soon as I put this character it stopped claiming any character.

"claim_delay": 0,
  "kak_delay": 0,
  "use_emoji": [
    "<:heart:>",
    "<:orange_heart:>",
    "<:yellow_heart:>",
    "<:green_heart:>",
    "<:blue_heart:>",
    "<:purple_heart:>",
    "<:black_heart:>",
    "<:brown_heart:>",
    "<:white_heart:>",
    "<:broken_heart:>",
    "<:two_hearts:>",
    "<:revolving_hearts:>",
    "<:heartbeat:>",
    "<:heartpulse:>",
    "<:sparkling_heart:>",
    "<:cupid:>",
    "<:gift_heart:>",
    "<:mending_heart:>",
    "<:heart_on_fire:>",
    "<:heart_decoration:>"
  ],
  "roll_this": "ma",
  "rolling": "False",
  "slash_rolling": "False",
  "pkmrolling": "False",
  "series_list": ["¶"],
  "namelist": [
    "Fubuki",
    "Mirko",
    "Reze",
    "Toph Beifong",
    "Azula",
    "Aang",
    "Sokka",
    "Katara",
    "Korra",
    "Kyoshi",
    "Luz Noceda",
    "Amity Blight",
    "Kobayashi",
    "Portgas D. Ace",
    "Ai Hoshino",
    "Yuu Nishinoya",
    "Loid Forger",
    "Stocking Anarchy",
    "Kei Tsukishima",
    "Tony Tony Chopper",
    "Biribiri",
    "Touji Fushiguro",
    "Kenma Kozume",
    "Toge Inumaki",
    "Chuuya Nakahara",
    "Raven",
    "Ymir",
    "Maki Oze",
    "Crona",
    "Tooru Oikawa",
    "Spider-Gwen (Gwen Stacy)",
    "Shanks",
    "Carrot",
    "Zuko",
    "Konoha's Yellow Flash",
    "Sabo",
    "Spider-Man (Miles Morales)",
    "The King of Curses",
    "Ai Hayasaka",
    "Mary Saotome"
  ],
  "emoji_list": [
    "kakera",
    "kaguya",
    "kakeraG",
    "kakeraY",
    "kakeraO",
    "kakeraR",
    "kakeraW",
    "kakeraL"
  ],
  "soulemoji_list": ["kakeraO", "kakeraR", "kakeraW", "kakeraL"],
  "min_kak": 400,
  "Last_True": "False",
  "last_claim_min": 1,
  "min_kak_last_min": 10
}

**Comment by JuliaYuki** [comment]
I don't let the auto roll I think it's broken so I prefer to roll myself

**Comment by Nicksw21** [comment]
Does the snipe work good for you? Also, can i use it on browser discord? (Instead of app)

**Comment by Nicksw21** [comment]
Do you recommend the claim delay and kakera delay on 0?
