### ISSUE TITLE
(Feature Suggestion?) Better logging.

### ISSUE THREAD

**Issue by DaMagicFox** [vivinano/MudaeAutoBot#25]
The bot is awesome and is working great! While it's not needed, I think a better log would be a good idea for when you're running the script. This is most certainly NOT necessary but I think it would be a good idea for the bot to keep in mind. It could help the user be more in line with what the bot is doing.

An example could be: 
"Character" ("wished"/"characterlist"/"serieslist") was detected in "channel" from "server". 
Claim (succesful/failed).

While this would be going a bit further and way less necessary than the one before, a good log idea (In my opinion, and I get why people wouldn't see the appeal) could also be showing The characters it's ignoring and their kak value.

**Comment by vivinano** [comment]
The old version use to log all the things but it seemed a bit spammy. im thinking about adding those back in but im on the fence you can add those back with a simple print command and variable if you want it to print

**Comment by DaMagicFox** [comment]
> The old version use to log all the things but it seemed a bit spammy. im thinking about adding those back in but im on the fence you can add those back with a simple print command and variable if you want it to print

How can that be done?

**Comment by vivinano** [comment]
look up how to use a python print command and go from there. its really simple
`print("hello world")`

**Comment by DaMagicFox** [comment]
> look up how to use a python print command and go from there. its really simple
> `print("hello world")`

Yeah but atm the bot has some crazy logs, would those just not appear?

**Comment by vivinano** [comment]
those logs are provided by default thru discum library and is set off to false by this application what I think is happening is that you are running an older version of discum 
please follow the documentation on the discum github to install the latest version

**Comment by DaMagicFox** [comment]
> those logs are provided by default thru discum library and is set off to false by this application what I think is happening is that you are running an older version of discum
> please follow the documentation on the discum github to install the latest version

I installed latest version but now bot is stuck in 
![image](https://user-images.githubusercontent.com/67620778/118175606-f133df00-b3f5-11eb-99c4-aca73b5a4749.png)

**Comment by vivinano** [comment]
its not stuck it working there no log because its set to false. 

for future reference any issue with discum should be directed towards discum as that is outside of my control

**Comment by DaMagicFox** [comment]
> its not stuck it working there no log because its set to false.
> 
> for future reference any issue with discum should be directed towards discum as that is outside of my control

Ok. Now how would I do a detection for if a claim was succesful or not?

And how would I do the "ignoring character" thing?

**Comment by vivinano** [comment]
u can add the wait_for check and have it "print" success if it appears

and you can have it print anything that it didnt add reaction probably only need to add that elif to the last if check.

**Comment by DaMagicFox** [comment]
> u can add the wait_for check and have it "print" success if it appears
> 
> and you can have it print anything that it didnt add reaction probably only need to add that elif to the last if check.

I honestly didn't have the slightest idea for how to the "wait_for" check might work and how to make it print "success" or "fail"

I have been trying to do the print ignored character for like 30 mins now but i just can't get it to work on the series side of things. I would like to know what would make "elif ser not in series_list" work. I believe it might not work because the bot can;t determine what the "ser" or series in this case is, but if that was true i couldn't understand how the series list check works.

**Comment by vivinano** [comment]
it would work but that specific elif command would just make it be true for everything and will create a alot of spam and will not check for success or fail. 
if you want to know success or fail then you have to figure out the wait_for function

**Comment by DaMagicFox** [comment]
> it would work but that specific elif command would just make it be true for everything and will create a alot of spam and will not check for success or fail.

What's weird is that i can do "charname.lower() not in chars" and it works as intended.

**Comment by vivinano** [comment]
if u have it on 1 then it should be fine for the generalist knowledge of what was rolled cause if u had the same check then the same character will be prinited 3 times as it fails each check

**Comment by DaMagicFox** [comment]
> if u have it on 1 then it should be fine for the generalist knowledge of what was rolled cause if u had the same check then the same character will be prinited 3 times as it fails each check

I have nothing written.
The character is only printed once though.

What i'm trying to figure out rn is how to prevent series list characters from being printed as both series claim and ignored.

**Comment by vivinano** [comment]
I’m lost at what ur trying to do now at this point

**Comment by DaMagicFox** [comment]
> I’m lost at what ur trying to do now at this point

I'm going to try and explain. So basically I wrote this. (Idk how good it is but it was what i could come up with)
![image](https://user-images.githubusercontent.com/67620778/118228996-cfb41100-b450-11eb-922a-d2b020882015.png)
It works perfectly fine. But I also needed it to be like this and work.
![image](https://user-images.githubusercontent.com/67620778/118229079-f83c0b00-b450-11eb-9768-f0b879f0c33d.png)
The thing is that when i do that one it doesn't work and out of all the changes I tried the one that got me the closest basically registered charcters that weren't on character list as ignored but also registered characters from the a series in series list as ignorred, even if it had even tried to claim them.

**Comment by vivinano** [comment]
that basically the logic issue using elif within the blocks itself example char snipe for Mei from Honkai impact 100 kak value : 
Personal settings - Mei (char) , HI3 (ser) , 500 kak_value
char prints - Success
series prints - Success
Kak value print - Ignored

Kiana - Hi3 - 100 kak

Char prints - ignored
series print - success
kak_value - ignored


so gotta fix the logic which will fix the false positives

**Comment by vivinano** [comment]
Added some more logging features thru the logging library so if u want to see the ignored characters you can set the logging.info > logging.DEBUG

**Comment by DaMagicFox** [comment]
> Added some more logging features thru the logging library so if u want to see the ignored characters you can set the logging.info > logging.DEBUG

What is that?

**Comment by DaMagicFox** [comment]
![image](https://user-images.githubusercontent.com/67620778/118300797-f2bddf80-b4a7-11eb-8e11-8b69f7fb103a.png)
I am basically having the same issue that I had before. If the attempted claim is due to the character being in series list, it appears as claim attempted and ignored.

**Comment by vivinano** [comment]
Did you make edits to the code ?

**Comment by DaMagicFox** [comment]
> Did you make edits to the code ?
> […](#)
> Sent from my iPhone
> On May 14, 2021, at 12:32 PM, DaMagicFox ***@***.***> wrote: ﻿ I am basically having the same issue that I had before. If the attempted claim is due to the character being in series list, it appears as claim attempted and ignored. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

The only edits I did were to get the Claim-Remove-Claim

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/118344121-b49ddb80-b4fa-11eb-9cc5-9e380e9ba9ba.png)
![image](https://user-images.githubusercontent.com/33008397/118344125-bb2c5300-b4fa-11eb-854d-47dd6f9e070f.png)
yeah im not sure how urs is working ? mine isnt even me false positivies using series snipe

**Comment by DaMagicFox** [comment]
> ![image](https://user-images.githubusercontent.com/33008397/118344121-b49ddb80-b4fa-11eb-9cc5-9e380e9ba9ba.png)
> ![image](https://user-images.githubusercontent.com/33008397/118344125-bb2c5300-b4fa-11eb-854d-47dd6f9e070f.png)
> yeah im not sure how urs is working ? mine isnt giving me false positivies using series snipe

I could send the file so you can check it...

**Comment by vivinano** [comment]
just show me the changes if u send me the screen of ur code

**Comment by DaMagicFox** [comment]
> just show me the changes it will be easier that way for me the solve the issue

![image](https://user-images.githubusercontent.com/67620778/118345761-3e01dd80-b4fc-11eb-9dcc-adf60274d3cb.png)
![image](https://user-images.githubusercontent.com/67620778/118345771-54a83480-b4fc-11eb-8fe5-ae0bc7915798.png)
If I changed anything, the change would be over there.

**Comment by vivinano** [comment]
well it might because u have the extra Kak check in that is set to a static variable. while everything else is on kak_min so there will be chances that both can be true so that basically what is going on logic wise

**Comment by DaMagicFox** [comment]
> well it might because u have the extra Kak check in that is set to a static variable. while everything else is on kak_min so there will be chances that both can be true so that basically what is going on logic wise

The thing is I don't want to basically claim every single character from the series that appears, i set the kakera minimum so that odds are it's a better character.

**Comment by vivinano** [comment]
Yeah i understand but this might be something you have to accept then unless you want to make your own code fixes to remove the false negative
