### ISSUE TITLE
Can i have multiple instances of this running at the same time?

### ISSUE THREAD

**Issue by Nicksw21** [vivinano/MudaeAutoBot#254]
Im wondering if you can have the autobot running in two different accounts in the same pc at the same time. Thanks in advance

**Comment by vivinano** [comment]
You should be able to yes Sent from my iPhoneOn Jul 21, 2023, at 4:27 PM, Nicksw21 ***@***.***> wrote:﻿
Im wondering if you can have the autobot running in two different accounts in the same pc at the same time. Thanks in advance

**Comment by Nicksw21** [comment]
Would it be possible to monitor two channels at the same time? if so, how would i have to put it in settings?

**Comment by vivinano** [comment]
the best way would be to copy the folder and then change the setting in the new one and launch both. windows aint too smart like that if you were on linux you probably could off just the same folder.
