### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Nicksw21** [vivinano/MudaeAutoBot#255]
So i got this error today while i was afk and i dont know what its related to:
![image](https://github.com/vivinano/MudaeAutoBot/assets/140040295/4f48ebab-a2fe-4194-8163-a1aadffb66a2)

**Comment by vivinano** [comment]
Seems like your network dropped during the night where you couldn’t get the next message to be parsed Sent from my iPhoneOn Jul 22, 2023, at 5:44 PM, Nicksw21 ***@***.***> wrote:﻿
So i got this error today while i was afk and i dont know what its related to:
