### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Mesh3al1** [vivinano/MudaeAutoBot#257]
![Screenshot_35](https://github.com/vivinano/MudaeAutoBot/assets/140486308/3fd9df6e-04c3-4be0-9f1d-fa3ca59ce20c)
I'm new to this not sure what to do here

**Comment by vivinano** [comment]
Uncompress it Sent from my iPhoneOn Jul 25, 2023, at 2:53 AM, Mesh3al1 ***@***.***> wrote:﻿

I'm new to this not sure what to do here
