### ISSUE TITLE
Claim delay question

### ISSUE THREAD

**Issue by sa-larios22** [vivinano/MudaeAutoBot#260]
The bot seems to work perfectly, however it seems to stop working after leaving it on for some time, if I encounter this issue again I'll create a new issue regarding this.

I have a question about the delay between the detection time and reaction time, I have currently set it to 0
`"claim_delay":0,
   "kak_delay":0,`
And it claimed correctly a 400+ value character
![image](https://github.com/vivinano/MudaeAutoBot/assets/68086604/db2e087e-2767-48bb-a5cb-701123a87232)

However, the guy I stole from inmediately realized it's a bot, so I want to add claim delay, my question is, does it have to be an integer value or it can be a decimal number? I think a 0.18 sec delay time is somewhat realistic, but I'm not sure if it's valid in the JSON file

**Comment by vivinano** [comment]
It might be a issue with discum not being able to reconnect Sent from my iPhoneOn Aug 12, 2023, at 3:37 PM, Sergio Larios ***@***.***> wrote:﻿
The bot seems to work perfectly, however it seems to stop working after leaving it on for some time, if I encounter this issue again I'll create a new issue regarding this.
I have a question about the delay between the detection time and reaction time, I have currently set it to 0
"claim_delay":0, "kak_delay":0,
And it claimed correctly a 400+ value character

However, the guy I stole from inmediately realized it's a bot, so I want to add claim delay, my question is, does it have to be an integer value or it can be a decimal number? I think a 0.18 sec delay time is somewhat realistic, but I'm not sure if it's valid in the JSON file

**Comment by vivinano** [comment]
You have to delete channel data and try to repoll the mudae settings to be updated so that way your only stopped by the delay itself

**Comment by sa-larios22** [comment]
So remake the channel data file and it should work? I'll try that, thank you

**Comment by sa-larios22** [comment]
Also, can the `claim_delay ` in the JSON file be a double or it has to be an integer?

**Comment by vivinano** [comment]
it can be a double
