### ISSUE TITLE
Visual guide

### ISSUE THREAD

**Issue by magicalhobo2001** [vivinano/MudaeAutoBot#262]
Answered

**Comment by vivinano** [comment]
Not that much of a artist so no just text guides lol sorry about that Sent from my iPhoneOn Sep 18, 2023, at 7:51 PM, magicalhobo2001 ***@***.***> wrote:﻿
Hi, does a visual guide to set this up exist anywhere? I can't get this working for the life of me. Sorry to be a bother.

**Comment by magicalhobo2001** [comment]
Alright, I've got the bot working. Thank you.

Also, can you add multiple discord tokens in the Settings_Mudae.json folder (To operate multiple accounts at once)
