### ISSUE TITLE
pls help 

### ISSUE THREAD

**Issue by farbensplasch** [vivinano/MudaeAutoBot#268]
idk what to do 
![Screenshot 2023-11-19 020703](https://github.com/vivinano/MudaeAutoBot/assets/134007677/bfb2534c-f826-493a-ae90-c831d193dc03)

**Comment by farbensplasch** [comment]
when i use a token from an other account i got this
![image](https://github.com/vivinano/MudaeAutoBot/assets/134007677/cc430360-4ce2-49b2-9f45-618914c31d08)

**Comment by vivinano** [comment]
The second one is successfully populated a user token Sent from my iPhoneOn Nov 19, 2023, at 5:19 AM, farbensplasch ***@***.***> wrote:﻿
when i use a token from an other account i got this

**Comment by Nixeld** [comment]
https://github.com/Nixeld/MudaeAutoBot
You can use my fork instead, made some quick fixes for the features I use but few things are still not working.

Update user.txt and guild.txt under the user folder and Settings_Mudae.json with the correct information.

**Comment by AugustoRcx** [comment]
Sometimes this happens to me, but I pause the bot, enter $settings in the server chat, start the bot again and it works again!

**Comment by AugustoRcx** [comment]
> não sei o que fazer ![Captura de tela 2023-11-19 020703](https://user-images.githubusercontent.com/134007677/284030472-bfb2534c-f826-493a-ae90-c831d193dc03.png)

Às vezes isso acontece comigo, mas eu pauso o bot, insiro $settings no chat do servidor, inicio o bot novamente e ele funciona novamente!

**Comment by GuillermoDiazFentanes** [comment]
@Nixeld 
Reading from UserFile
It seems like you were unable to get all the guilds you are in please obtain your users settings
reading from Guild file
File Not Found using Different Method
Default $settings used for channel 1172768785107791903
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000024848C0E8A0>>
Traceback (most recent call last):
  File "C:\Users\Guille\AppData\Local\Programs\Python\Python311\Lib\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\Guille\Downloads\MudaeAutoBot-main\MudaeAutoBot.py", line 487, in on_message
    snipe_delay = channel_settings[int(channelid)]['kak_snipe'][1]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
72000 : daily_rolling : 1172768785107791903
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000024848C0E8A0>>
Traceback (most recent call last):
  File "C:\Users\Guille\AppData\Local\Programs\Python\Python311\Lib\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\Guille\Downloads\MudaeAutoBot-main\MudaeAutoBot.py", line 487, in on_message
    snipe_delay = channel_settings[int(channelid)]['kak_snipe'][1]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^

Im trying your version and i get this, what can i do?? does it work for you?

**Comment by Nixeld** [comment]
> @Nixeld Reading from UserFile It seems like you were unable to get all the guilds you are in please obtain your users settings reading from Guild file File Not Found using Different Method Default $settings used for channel 1172768785107791903 Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000024848C0E8A0>> Traceback (most recent call last): File "C:\Users\Guille\AppData\Local\Programs\Python\Python311\Lib\site-packages\discum\gateway\gateway.py", line 299, in _response_loop func(resp) File "C:\Users\Guille\Downloads\MudaeAutoBot-main\MudaeAutoBot.py", line 487, in on_message snipe_delay = channel_settings[int(channelid)]['kak_snipe'][1] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^ IndexError: list index out of range 72000 : daily_rolling : 1172768785107791903 Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000024848C0E8A0>> Traceback (most recent call last): File "C:\Users\Guille\AppData\Local\Programs\Python\Python311\Lib\site-packages\discum\gateway\gateway.py", line 299, in _response_loop func(resp) File "C:\Users\Guille\Downloads\MudaeAutoBot-main\MudaeAutoBot.py", line 487, in on_message snipe_delay = channel_settings[int(channelid)]['kak_snipe'][1] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
> 
> Im trying your version and i get this, what can i do?? does it work for you?

It is unable to get your channel settings, run $settings in your channel before running the bot again.

**Comment by farbensplasch** [comment]
It worked with your fork thx @Nixeld 

but now I have another problem.

this is my settings_Mudae.json file:
{
   "token":"xxxxxxxxxx",
   "channel_ids":[
	  xxxxxxxxxxx
   ],
   "slash_ids":[
	  xxxxxxxxxxxx
   ],
   "slash_guild_ids":[
      xxxxxxxxxxx
   ],
   "claim_delay":1,
   "kak_delay":1,
   "use_emoji":"<:keqing_love:795077041761288214>",
   "roll_this":"m",
   "slash_this":"m",
   "rolling":"False",
   "slash_rolling":"False",
   "dailyrolling":"False",
   "pokerolling":"False",
   "series_list":[
      "AAAAAAAAAAAAAAAAAAAAAAA"
   ],
   "namelist":[
"Raiden Mei",
"Lysithea",
"Tali'Zorah nar Rayya",
"Dorothy Haze",
"Cosmo Imai",
"Norman",
"Tanya Degurechaff",
"Hajime Hanafusa",
"Anna Graem",
"Ray",
"Judy Alvarez",
"Garrus Vakarian",
"Griffith",
"Baki Hanma",
"Ulquiorra Cifer",
"Tetsuya Kuroko",
"Jack Hanma",
"Alpha",
"Beta",
"Delta",
"Alphys",
"Annoying Dog",
"Asgore",
"Asriel",
"Bird That Carries You Over A Disproportionately Small Gap",
"Bratty",
"Burgerpants",
"Catty",
"Chara",
"Doggo",
"Endogeny",
"Everyman",
"Flowey",
"Frisk",
"Gerson",
"Greater Dog",
"Grillby",
"Heats Flamesman",
"Ice Wolf",
"Ice-E",
"Jerry (UT)",
"Lemon Bread",
"Lesser Dog",
"Mad Dummy",
"Mad Mew Mew",
"Mettaton",
"Monster Kid",
"Muffet",
"Napstablook",
"Nice Cream Guy",
"Onionsan",
"Papyrus",
"Reaper Bird",
"RG 01",
"RG 02",
"River Person",
"Sans",
"Shyren",
"Snowdin Shopkeeper",
"Snowdrake",
"Snowdrake's Mother",
"Snowman",
"So Sorry",
"Temmie",
"Toriel",
"Undyne",
"W. D. Gaster",
"Cid Kagenou",
"Airi Sakura",
"Akane Tachibana",
"Akito Miyake",
"Albert Yamada",
"Arisu Sakayanagi",
"Chiaki Matsushita",
"Chie Hoshinomiya",
"Chihiro Shiranami",
"Fuuka Kiryuuin",
"Haruka Hasebe",
"Haruki Yamauchi",
"Hiyori Shiina",
"Honami Ichinose",
"Ichika Amasawa",
"Ikuto Kiriyama",
"Kakeru Ryuuen",
"Kanji Ike",
"Kayano Onodera",
"Kazuomi Hosen",
"Kei Karuizawa",
"Ken Sudou",
"Kikyou Kushida",
"Kiyotaka Ayanokouji",
"Kokoro Inogashira",
"Kouhei Katsuragi",
"Mako Amikura",
"Manabu Horikita",
"Masumi Kamuro",
"Maya Satou",
"Mei-Yu Wang",
"Mio Ibuki",
"Miyabi Nagumo",
"Nazuna Asahina",
"Nene Mori",
"Rokusuke Kouenji",
"Ryuuji Kanzaki",
"Sae Chabashira",
"Sakurako Tsubaki",
"Satoru Kaneda",
"Satsuki Shinohara",
"Suzune Horikita",
"Takeko Nishino",
"Takuya Yagami",
"Teruhiko Yukimura",
"Tsubasa Nanase",
"Yousuke Hirata",
"Yuki Himeno (CotE)",
"Aguri Yukimura",
"Akira Takaoka",
"Gakuhou Asano",
"Gakushuu Asano",
"Gastro",
"Hinano Kurahashi",
"Hinata Okano",
"Hiroto Maehara",
"Irina Jelavić",
"Itona Horibe",
"Kaede Kayano",
"Karma Akabane",
"Kirara Hazama",
"Koki Mimura",
"Koro-sensei",
"Kotaro Takebayashi",
"Lovro Brovski",
"Manami Okuda",
"Masayoshi Kimura",
"Meg Kataoka",
"Nagisa Shiota",
"Rinka Hayami",
"Rio Nakamura",
"Ritsu",
"Ryouma Terasaka",
"Ryuunosuke Chiba",
"Sosuke Sugaya",
"Sumire Hara",
"Tadaomi Karasuma",
"Taiga Okajima",
"Taisei Yoshida",
"Takuya Muramatsu",
"Tomohito Sugino",
"Touka Yada",
"Yuji Norita",
"Yukiko Kanzaki",
"Yuuma Isogai",
"Yuzuki Fuwa",
"Airi (RW)",
"Akira (RW)",
"Alpha (RW)",
"Aricia",
"Carol (RW)",
"Elena (RW)",
"Katsuya",
"Lucia (RW)",
"Nelia",
"Reina (RW)",
"Sara (RW)",
"Sheryl (RW)",
"Shiori (RW)",
"Shizuka (RW)",
"Viola (RW)",
"Yumina",
"Yuuichi Katagiri",
"Tenji Mikasa",
"Shinji Shiba",
"Shiho Sawaragi",
"Kei Shinomiya",
"Jin-Woo Sung",
"Zero Two",
"Ichigo",
"Princess of Klaxosaurs",
"Kokoro",
"Vladilena Milizé",
"Chako",
"Nagi Aoe",
"Reiji Kurose",
"Yuko Kurose",
"Yuri Shibasawa",
"Kuga Daichi",
"Shigoku Kyou",
"Shun Uruma",
"Asuna",
"Sinon",
"Alice Synthesis Thirty",
"Leafa",
"Yuuki Konno",
"Kirito",
"Alice Zuberg",
"Yui (SAO)",
"Sachi (SAO)",
"Megumin",
"Kurisu Makise",
"Holo",
"Albedo (GI)",
"Arataki Itto",
"Arlecchino",
"Baizhu",
"Barbara",
"Beidou",
"Bennett",
"Chongyun",
"Collei",
"Columbina",
"Cyno",
"Dainsleif",
"Dehya",
"Diluc",
"Eula",
"Fischl",
"Hu Tao",
"Jean",
"Kaedehara Kazuha",
"Kaeya",
"Kamisato Ayaka",
"Kamisato Ayato",
"Keqing",
"Komaki",
"Lisa",
"Mona",
"Ningguang",
"Noelle",
"Paimon",
"Raiden Shogun",
"Razor",
"Rosaria",
"Sangonomiya Kokomi",
"Shenhe",
"Sucrose",
"Tartaglia",
"Thoma",
"Tighnari",
"Xiangling",
"Venti",
"Wanderer",
"Xiao",
"Xingqiu",
"Xinyan",
"Yae Miko",
"Yanfei",
"Yelan",
"Yoimiya",
"Zhongli",
"Kokoa Yoshizaki",
"Ryuuto Suzuki",
"Yamada Asaemon Sagiri",
"Gabimaru the Hollow",
"Yuzuriha of the Seishu",
"Shija",
"Nene Yashiro",
"Hanako-kun",
"Tsukasa Yugi",
"Aoi Akane",
"Kou Minamoto",
"Touka Kirishima",
"Ken Kaneki",
"Rize Kamishiro",
"Eto",
"Juuzou Suzuya",
"Tessia Eralith",
"Emma",
"Ray",
"Norman",
"Nazuna Nanakusa",
"Akira Asai",
"Megumin",
"Mai Sakurajima",
"Rias Gremory",
"Asuna",
"Satoru Gojou",
"Makima",
"Emilia",
"Aqua",
"Akame",
"Yumeko Jabami",
"Nino Nakano",
"Kaguya Shinomiya",
"Akeno Himejima",
"Ram",
"Himiko Toga",
"Esdeath",
"Hinata Hyuuga",
"Mitsuri Kanroji",
"Shiro",
"Gawr Gura",
"Nobara Kugisaki",
"Rei Ayanami",
"Asuka Langley Soryu",
"Raphtalia",
"Sinon",
"Darkness",
"Rikka Takanashi",
"Kanna Kamui",
"Itsuki Nakano",
"Yotsuba Nakano",
"Lucy Heartfilia",
"Ai Hoshino",
"Tatsumaki",
"Chizuru Ichinose",
"Jolyne Cujoh",
"Fubuki",
"Taiga Aisaka",
"Mirko",
"Tanjirou Kamado",
"Megumi Fushiguro",
"Katsuki Bakugou",
"Misato Katsuragi",
"Sukuna",
"Shouko Nishimiya",
"Tsuyu Asui",
"Sasha Braus",
"Ai Ohto",
"Ichika Nakano",
"Shinobu Oshino",
"Kaori Miyazono",
"Momo Yaoyorozu",
"Dio Brando",
"Hestia",
"Yukino Yukinoshita",
"Jeanne d'Arc",
"Alice Synthesis",
"Izuku Midoriya",
"Mary Saotome",
"Erina Nakiri",
"Inugami Korone",
"Venom",
"Astolfo",
"Roxy Migurdia",
"Jinx",
"Futaba Sakura",
"Hitagi Senjougahara",
"Amelia Watson",
"Jeanne d'Arc (Alter)",
"Yamato",
"Krista Lenz",
"Inosuke Hashibira",
"Trollface",
"Black Hanekawa",
"Ann Takamaki",
"Jibril",
"Noelle Silva",
"Kyouka Jirou",
"Son Goku",
"Zenitsu Agatsuma",
"Midnight",
"Raiden Shogun",
"Cynthia",
"Koneko Toujou",
"Makoto Niijima",
"Hoshimachi Suisei",
"Vladilena Milizé",
"Eris Boreas Greyrat",
"Maki Oze",
"Hitori Gotou",
"Bulma",
"Houshou Marine",
"Howl",
"Elma",
"Tony Tony Chopper",
"Aiz Wallenstein",
"A2",
"Mirai Kuriyama",
"Booette",
"Alice Nakiri",
"Schwi Dola",
"Ninomae Ina'nis",
"Kobayashi",
"Mashiro Shiina",
"Juvia Lockser",
"Wiz",
"Nero Claudius",
"Senko",
"Mina Ashido",
"Godzilla",
"Eru Chitanda",
"Celestia Ludenberg",
"Shinoa Hiiragi",
"Phosphophyllite",
"Pieck Finger",
"Elaina",
"Yoko Littner",
"Elizabeth Liones",
"Kagamine Rin",
"Usada Pekora",
"Madoka Kaname",
"Shirakami Fubuki",
"Kanae Kochou",
"Nagito Komaeda",
"Chuuya Nakahara",
"Chitoge Kirisaki",
"Nero",
"Ghostface",
"Kiryu Coco",
"Nekomata Okayu",
"Mash Kyrielight",
"Hanako-kun",
"Xenovia Quarta",
"Tanya Degurechaff",
"Foo Fighters",
"Wojak",
"Nico Yazawa",
"Mio Akiyama",
"Leon S. Kennedy",
"Shouyou Hinata",
"Alluka Zoldyck",
"Toge Inumaki",
"Spider-Gwen (Gwen Stacy)",
"Osana Najimi",
"Mewtwo",
"Daki",
"Yunyun",
"Ereshkigal",
"Kasumi Miwa",
"Ibuki Mioda",
"Leone",
"Yuuta Okkotsu",
"Nazuna Nanakusa",
"Perona",
"Shizuku Murasaki",
"Destiny",
"Homura Akemi",
"Gunter",
"Shikimori-san",
"Krul Tepes",
"Spider-Man (Peter Parker)",
"Mikoto Misaka",
"Saitama",
"Nefertari Vivi",
"Kiana Kaslana",
"Uruha Rushia",
"Usopp",
"Holo",
"Mew",
"Ilulu",
"Sonic the Hedgehog",
"Mei Misaki",
"Nelliel Tu Odelschwanck",
"Leafa",
"Yuuki Konno",
"Chelsea",
"Tartaglia",
"Miia",
"Rangiku Matsumoto",
"Asia Argento",
"Hae-In Cha",
"Ino Yamanaka",
"Giorno Giovanna",
"Miko Iino",
"Mikey",
"Ririka Momobami",
"Aigis",
"Azusa Nakano",
"Atsuko Kagari",
"Tobio Kageyama",
"Yui Yuigahama",
"Kuroka",
"Ruby Hoshino",
"Iris",
"Eijirou Kirishima",
"Megurine Luka",
"Takanashi Kiara",
"Haru Okumura",
"Shigeo Kageyama",
"Muichirou Tokitou",
"Kei Shirogane",
"Mei Hatsume",
"Hibana",
"Merlin",
"Mirajane Strauss",
"Minato Aqua",
"Tsukasa Yuzaki",
"Kenma Kozume",
"Yato",
"Asta",
"Anna Nishikinomiya",
"Tsubasa Hanekawa",
"Gudetama",
"Raiden Mei",
"Beatrice (RZ)",
"Uta",
"Stocking Anarchy",
"Angel Devil",
"Loid Forger",
"Kana Arima",
"Rimuru Tempest",
"Saiki Kusuo",
"Sebastian Michaelis",
"Siesta",
"Nakiri Ayame",
"Vi",
"Midari Ikishima",
"Yae Sakura",
"Starfire",
"Chisato Nishikigi",
"Brook",
"Akiko Yosano",
"Stella Vermillion",
"Kanade Tachibana",
"Izumi Miyamura",
"Kaede Azusagawa",
"Shuna",
"Satella",
"Mayuri Shiina",
"Caitlyn",
"Akane Kurokawa",
"Illyasviel von Einzbern",
"Sagiri Izumi",
"Arataka Reigen",
"Hello Kitty",
"Tamayo",
"Filo",
"Yue",
"Eula",
"Takagi-san",
"Diamond",
"Runa Yomozuki",
"Amber",
"Tooru Oikawa",
"Akai Haato",
"Aoi Asahina",
"Shadow the Hedgehog",
"Envy",
"Spider-Man (Miles Morales)",
"Batman (Bruce Wayne)",
"Dawn",
"Sheele",
"Irina Shidou",
"Eevee",
"Sylphiette",
"Rory Mercury",
"Saeko Busujima",
"GUMI",
"Obanai Igurou",
"Shishiro Botan",
"Isla",
"Spike Spiegel",
"Stephanie Dola",
"Tokoyami Towa",
"Mimosa Vermillion",
"Rebecca",
"Hinatsuru",
"Shion (TenSura)",
"Origami Tobiichi",
"Yuu Nishinoya",
"Vaporeon",
"Nadeko Sengoku",
"Loki (Loki Laufeyson)",
"Haruhi Suzumiya",
"Maika Sakuranomiya",
"Camie Utsushimi",
"Bishamon",
"Goro Akechi",
"Albedo (GI)",
"Okita Souji",
"Ruby Rose",
"Kaeya",
"Suma",
"Mitsuki Bakugou",
"Aoi Kanzaki",
"Misaki Ayuzawa",
"Peko Pekoyama",
"Touko Fukawa",
"Lisa Lisa",
"Momo Belia Deviluke",
"Kallen Stadtfeld",
"707",
"Mio Naruse",
"Rei Hino",
"Kurome",
"Ouro Kronii",
"Kosaki Onodera",
"Korra",
"Hanabi Hyuuga",
"Sabo",
"Makomo",
"Tooru Honda",
"Erza Knightwalker",
"Princess Bubblegum",
"Neptune",
"Chocola",
"Kizuna AI",
"Misty",
"Tifa Lockhart",
"Mona",
"Zuko",
"Beidou",
"Nanashi Mumei",
"Morgiana",
"Ayane Shirakawa",
"Snorlax",
"Rayquaza",
"Ellie",
"Chihiro Ogino",
"Haruka Tenou",
"Seele Vollerei",
"Sayu Ogiwara",
"Vanilla",
"Arataki Itto",
"Bon Clay",
"Alucard",
"Miko Yotsuya",
"Denki Kaminari",
"Kagamine Len",
"Rossweisse",
"Ceres Fauna",
"Vanitas",
"Alice Zuberg",
"Lain Iwakura",
"Minako Aino",
"Rin Okumura",
"Tamamo no Mae",
"Kurom",
"Senpai (TS)",
"Nana Shimura",
"Jessie",
"Rika Kawai",
"Blair",
"Wendy Marvell",
"Ash Lynx",
"Tsunomaki Watame",
"Lala Satalin Deviluke",
"Ryuunosuke Akutagawa",
"AE3803",
"Yona",
"Kei Tsukishima",
"Vanessa Enoteca",
"Sakura Miko",
"Trish Una",
"Konjiki no Yami",
"Tae Takemi",
"Ookami Mio",
"Yuki Nagato",
"Dark Magician Girl",
"Muzan Kibutsuji",
"TBH Creature",
"Shizue Izawa",
"Shirahoshi",
"Natsumi",
"Pikachu (Species)",
"Shirogane Noel",
"Koutarou Bokuto",
"Creeper",
"Sarada Uchiha",
"Rui Tachibana",
"Oozora Subaru",
"Juuzou Suzuya",
"Gaara",
"Douma",
"Tetsurou Kuroo",
"Yui (SAO)",
"Kagome Higurashi",
"Aki Adagaki",
"Ikumi Mito",
"Kafka",
"Gilgamesh",
"Gwen",
"The Giant Rat That Makes All of the Rules",
"Murata Himeko",
"Utahime Iori",
"Legosi",
"9S",
"Ryu Lion",
"Sanemi Shinazugawa",
"Akira Fudou",
"Yumemi Yumemite",
"Meruccubus",
"Aether",
"Sonia Nevermind",
"Kim Dokja",
"Yoshikage Kira",
"Levy McGarden",
"Mikaela Hyakuya",
"N",
"Maki Nishikino",
"Sephiroth",
"Ami Mizuno",
"Zack",
"Quinella",
"Ghislaine Dedoldia",
"Yuri",
"Bronya Zaychik",
"San",
"KAITO - VOCALOID",
"Genocider Syo",
"Sabito",
"Veliona",
"Griffith",
"Ryuk",
"Chi-Chi",
"My Melody",
"Toyomi Fujiwara",
"Pain",
"Rin",
"Yui",
"Silica",
"Aerith Gainsborough",
"Rei Miyamoto",
"Iroha Isshiki",
"Naoto Shirogane",
"Artoria Pendragon (Lancer)",
"Mami Nanami",
"Lady Nagant",
"Gintoki Sakata",
"Ada Wong",
"Sylveon",
"Tier Harribel",
"Death the Kid",
"Tomoe Koga",
"Pepe",
"Sayaka Maizono",
"May",
"Son Gohan",
"Kyouka Izumi",
"Mei Terumi",
"Sangonomiya Kokomi",
"Yoimiya",
"Mami Tomoe",
"Kei Karuizawa",
"Kasumi Yoshizawa",
"Rebecca (OP)",
"D.Va",
"Sword Maiden",
"Lola Bunny",
"Rin Nohara",
"Narberal Gamma",
"Grumpy Cat",
"Frederica Baumann",
"Rise Kujikawa",
"Satanichia McDowell Kurumizawa",
"Irina Jelavić",
"Kurenai Yuuhi",
"Inuyasha",
"Jahy",
"Koushi Sugawara",
"Ahsoka Tano",
"Isuzu Sento",
"Amelie Azazel",
"Mirio Togata",
"Yukihana Lamy",
"Durandal",
"Kokushibou",
"Shylily",
"Scarlet Witch (Wanda Maximoff)",
"Pikachu",
"Mamako Oosuki",
"Adult Neptune",
"Chifuyu Matsuno",
"Adrien Agreste",
"Hina Amano",
"Ryou Yamada",
"Kureiji Ollie",
"Komi Shuuko",
"Ray",
"Biscuit Krueger",
"Yami Yugi",
"Spider Demon (Mother)",
"Freya",
"William Afton",
"Totoro",
"Hua Cheng",
"Yuno",
"Arcueid Brunestud",
"Tooru Hagakure",
"Erza Knightwalker",
"Panty Anarchy",
"Hitoshi Shinsou",
"Kyaru",
"Sakura Kinomoto",
"Reiner Braun",
"Meliodas",
"Amane Kanata",
"Phoenix Wright",
"Obito Uchiha",
"Derieri",
"Yukana Yame",
"Hotaru Shidare",
"Ditto",
"Takina Inoue",
"Guido Mista",
"GIR",
"Shikamaru Nara",
"Megumi Katou",
"Cinnabar",
"Jeanne",
"Shiki Ryougi",
"Amity Blight",
"Vivy",
"Elaine",
"Miyuki Shiba",
"Ainz Ooal Gown",
"Paimon",
"Melascula",
"Aoi Akane",
"Shouko Makinohara",
"Mai",
"Marnie",
"Fu Hua",
"Sakuya Izayoi",
"Tenten",
"Ponyo",
"Yoichi Isagi",
"Ironmouse",
"Momosuzu Nene",
"Fiona Frost",
"Maple",
"Ash Ketchum",
"Gray Fullbuster",
"Sakamata Chloe",
"Vermeil",
"Seishirou Tsugumi",
"Ikuyo Kita",
"Rikka Takarada",
"Yuzuki Choco",
"Shouya Ishida",
"Akari Watanabe",
"Darth Vader",
"Reimu Hakurei",
"Enkidu",
"Alhaitham",
"Gyoumei Himejima",
"Bread",
"Mayoi Hachikuji",
"Star Butterfly",
"Purple Heart",
"Ryuji Sakamoto",
"Keiji Akaashi",
"Narumi Momose",
"Sophie Hatter",
"Sakura Yamauchi",
"Moona Hoshinova",
"Karen Araragi",
"Garou",
"Mizuki Akiyama",
"Loona",
"Finn",
"Mafuyu Kirisu",
"Miyamoto Musashi",
"Moka Akashiya",
"Rock Lee",
"Lugia",
"Rohan Kishibe",
"Miles Edgeworth",
"Lupusregina Beta",
"Oda Nobunaga",
"Super Sonico",
"Irisviel von Einzbern",
"Omaru Polka",
"Sadayo Kawakami",
"Helen Parr",
"Alucard (CV)",
"Coconut",
"Yotsugi Ononoki",
"Tokino Sora",
"Mukuro Ikusaba",
"Narancia Ghirga",
"Jinbe",
"Komugi",
"Robert E. O. Speedwagon",
"Amadeus",
"Shura Kirigakure",
"Elsa",
"Sistine Fibel",
"Jack the Ripper",
"Bowser",
"Kim Possible",
"Kyou Sohma",
"Meguru Bachira",
"IA",
"Mem-Cho",
"Coraline Jones",
"Xie Lian",
"Komurasaki",
"Grayfia Lucifuge",
"Ciri",
"Kofuku",
"Illumi Zoldyck",
"Mari Makinami Illustrious",
"Ado",
"Ms. Joke",
"Genya Shinazugawa",
"Akali",
"Kou Minamoto",
"Charlotte Pudding",
"Rin Tohsaka (F/EX)",
"Aquarius",
"Yelena",
"Miko",
"Charmy Pappitson",
"Susamaru",
"Koala",
"Yang Xiao Long",
"Tomoe",
"Jewelry Bonney",
"Feitan Portor",
"Touka Takanashi",
"Hifumi Togo",
"Saiko Yonebayashi",
"Arlecchino",
"Emma Sano",
"Lisbeth",
"Mabel Pines",
"Flame Princess",
"Jessica Rabbit",
"Chel",
"SCP-3008",
"Chomusuke",
"Nayuta Kani",
"Jigglypuff",
"Tamaki Suoh",
"Rachnera Arachnera",
"Subaru Natsuki",
"Shinra Kusakabe",
"Alastor",
"Mafuyu Satou",
"Rosaria",
"Cyno",
"Robin",
"Sora",
"Victor Nikiforov",
"Yanfei",
"Lady Dimitrescu",
"Escanor",
"Sousuke Mitsuba",
"Wei Wuxian",
"Yusuke Kitagawa",
"Jake",
"Baki Hanma",
"Byakuya Togami",
"Fyodor Dostoevsky",
"Iron Man (Tony Stark)",
"Thoma",
"Whitebeard",
"Yuichiro Hyakuya",
"Haruhi Fujioka",
"Aqua Hoshino",
"Daisuke Kambe",
"Elysia",
"Chihiro Fujisaki",
"Kazuma Satou",
"Neji Hyuuga",
"Cirno",
"Gundham",
"Lillie",
"Fumikage Tokoyami",
"Makoto Yuki",
"Diavolo",
"Weiss Schnee",
"Endorsi Jahad",
"Gogeta",
"Razor",
"Suu",
"Jesus",
"Blake Belladonna",
"Guren Ichinose",
"Asuka",
"Mammon",
"Toothless",
"James",
"Nozomi Tojo",
"Donquixote Doflamingo",
"Adam",
"Dainsleif",
"Pyra",
"Rui Kamishiro",
"Haise Sasaki",
"Marinette Dupain-Cheng",
"Benimaru Shinmon",
"Steve",
"MEIKO",
"Kumoko",
"Satori Tendou",
"Setsuna",
"Yoo Joonghyuk",
"Haruka Nanase",
"Rosalina",
"Vergil",
"Bam",
"Suruga Kanbaru",
"Nagisa Furukawa",
"Han Sooyoung",
"Dan Heng",
"Sawako Kuronuma",
"Lilith Asami",
"Garfield",
"Norman"

],
   "emoji_list":[
	  "kakera",	
      "kakeraT",
      "kakeraG",
      "kakeraY",
      "kakeraO",
      "kakeraR",
      "kakeraW",
      "kakeraL"
   ],
   "soulemoji_list":[
      "kakeraO",
      "kakeraR",
      "KakeraW",
      "KakeraL"
   ],
   "min_kak":500,
   "Last_True":"True",
   "last_claim_min": 61,
   "min_kak_last_min": 10
}


but the bot claimed 2 charackters thet arent on this list (or tried to)
![image](https://github.com/vivinano/MudaeAutoBot/assets/134007677/420695d6-0c73-461a-a432-4f2010408fe4)
![image](https://github.com/vivinano/MudaeAutoBot/assets/134007677/615b5640-57da-40e0-aaf7-a2b51390745c)

**Comment by vivinano** [comment]
seems resolved closing issue
