### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Aptmarrow** [vivinano/MudaeAutoBot#269]
Im new at this and i dont know what to do with the followning errors:
![imagen_2024-02-03_013805824](https://github.com/vivinano/MudaeAutoBot/assets/158111326/d8a0816d-387c-4516-86c6-1bd6e82bd062)

**Comment by vivinano** [comment]
You gotta install the dependencies Sent from my iPhoneOn Feb 2, 2024, at 11:38 PM, Aptmarrow ***@***.***> wrote:﻿
Im new at this and i dont know what to do with the followning errors:
imagen_2024-02-03_013805824.png (view on web)

**Comment by Aptmarrow** [comment]
thank you, now i got a problem at line 645
![imagen_2024-02-29_000027763](https://github.com/vivinano/MudaeAutoBot/assets/158111326/9bc4b7f1-02da-45cf-9550-2c435a79f8b1)

**Comment by vivinano** [comment]
you might have installed an older version

**Comment by HentaiRyuu** [comment]
it is typo in your current git repo code, change `buttonly` to `buttsonly` to fix this at line `645`
