### ISSUE TITLE
Doubts the functionalities that are working

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#27]
Hello I was using the version that used discord.py that stopped working many things, I would like to know if this is working with the following settings:
rolling
series_list
namelist
soulemoji_list
Kakera delay

because I'm having a problem with the bot, which when starting it presents the console with a lot of information being presented quickly that is impossible to read, I installed the discum by downloading version 1.2.1 because I couldn't use the command `python -m pip install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git`

**Comment by vivinano** [comment]
not understanding to much but 
discord.py should gradually stop working as the dev of that library has deprecated support for selfbots and will do so more and more. the only thing that is not implemented in the current version of discum is soulmate_emoji list in the list you provided as its still in a testing phase.

if you are getting discum logs on your console then you are not on version 1.2.1 as the code has that option set to false please refer to the discum repo for help installing the newest version

**Comment by BellaDona007** [comment]
If the only thing that is not working is Soulmate_emoji already helps a lot.
I will try to update again to 1.2.1

**Comment by BellaDona007** [comment]
So shouldn't this happen if you were in 1.2.1?

![image](https://user-images.githubusercontent.com/82736191/118414133-3d428600-b679-11eb-9c11-4a1fcd5fed19.png)
![image](https://user-images.githubusercontent.com/82736191/118414170-7975e680-b679-11eb-92b6-635434c25c49.png)

**Comment by vivinano** [comment]
No that should not be happening that is the logs for discum to see what is happning. if within my code the discum logging is set to "False" then you should only see the regular prints that I set. This is because you didnt install the newest version of  discum correctly. you still probably have the old version installed by the normal way of pip3 which is the 1.1.0 version


refer to https://github.com/Merubokkusu/Discord-S.C.U.M to find further information and if you have further issues. Please contact the Dev of that library. They are pretty nice

**Comment by BellaDona007** [comment]
I managed to install but after configuring this error occurs

![image](https://user-images.githubusercontent.com/82736191/118420913-4d1c9300-b696-11eb-8f48-818c3a13bf9c.png)

**Comment by vivinano** [comment]
i think guild id counts for DM's so if you receive a DM its count as a message without a guild id this is also mentioned in the discum documentations

**Comment by BellaDona007** [comment]
![image](https://user-images.githubusercontent.com/82736191/118424519-c4095a00-b69d-11eb-80b9-52f697c8cf71.png)

It was set up like that, and he ignored KakeraL

**Comment by vivinano** [comment]
Where you on kakera cooldown ?

**Comment by BellaDona007** [comment]
It was without kakera cooldown, had just opened the bot had 5 minutes

**Comment by vivinano** [comment]
what was printed ? or did it just ignore ? or did u wait for the time.sleep() to finish

**Comment by vivinano** [comment]
oh nvm i see what going on its because the limited scope version of the program is the default so multi id need to be set with the channel id you want to monitor in

**Comment by BellaDona007** [comment]
> what was printed ? or did it just ignore ? or did u wait for the time.sleep() to finish

Did not show anything

**Comment by BellaDona007** [comment]
> i think guild id counts for DM's so if you receive a DM its count as a message without a guild id this is also mentioned in the discum documentations

There is no way to disable these messages?

**Comment by vivinano** [comment]
change your multi id setting for channels you want to monitor 

> There is no way to disable these messages?

there is and its in the discum documentation you can either implement it yourself or wait for me but it will be a while as of right now working on other changes and testing bugs
