### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by verbalizations** [vivinano/MudaeAutoBot#274]
![Screenshot 2024-07-02 164740](https://github.com/vivinano/MudaeAutoBot/assets/174389714/cc4a9eb1-b693-4877-a090-86ae04e6f59d)

This error pops up on line 767, and i don't know what to do

**Comment by verbalizations** [comment]
![image](https://github.com/vivinano/MudaeAutoBot/assets/174389714/d67e2396-a774-49d9-a8bc-5bef1dd7f304)
This as well.

**Comment by SoyNexoo** [comment]
Can u send more pics about ur code?
