### ISSUE TITLE
does not claim kakera

### ISSUE THREAD

**Issue by Drey7u7** [vivinano/MudaeAutoBot#275]
I've been there for 10 hours and in those I never complain, kakera, is there anything I can do?

**Comment by SoyNexoo** [comment]
Hello, I resolved the issue of not grabbing kakera. What I did was take it out of the if statements and move it to the beginning of the on_message function. Then I added the emojis I wanted to grab. I didn't do it with the emoji_list from Settings_Mudae.json.

On line 497 add:
```
elif int(aId) == mudae:
    if butts.components != []:
        buttMoji = butts.components[0]["components"][0]["emoji"]["name"]
        print(buttMoji)
        if buttMoji in ["kakeraP", "kakeraY", "kakeraO", "kakeraR", "kakeraW", "kakeraL"]:
            bot.click(
                aId,
                channelID=m["channel_id"],
                guildID=m.get("guild_id"),
                messageID=m["id"],
                messageFlags=m["flags"],
                data=butts.getButton(emojiName=buttMoji),
            )
```
And comment out the conditional from line 585 to 600. Lastly, comment out the conditional on line 635.

**Comment by SoyNexoo** [comment]
It only has one bug: when nothing is thrown for about 40 minutes or 1 hour, the autobot stops grabbing, and you have to restart it.
