### ISSUE TITLE
Problem with reacting to an image with embeded buttons

### ISSUE THREAD

**Issue by WatameBytes** [vivinano/MudaeAutoBot#279]
For example, it did react to 
![image](https://github.com/user-attachments/assets/ec2d2d32-45d5-4e2c-b447-a148aa15394e)
It was wished by the botted user and rolled by them, so you can't say snipe protection prevented it.

As you can see, it didn't claim them. One temporarily solution I found was by using `$perstogglereact` to remove the embeds when I roll, otherwise reacting won't claim them. I said temporarly solution, cause if someone else wished for that character, it will have those buttons attached, preventing me from even claiming when I roll themed and allowing someone else to snipe them.

Wondering if this is normal, did I mess up somewhere? I did increase the sleep time in the code, but seems like if it has a heart embed attached to it, it can't claim it. Wondering if there is a work around to this. 

To recreate this problem, lower the `"min_kak":5,` to lets say 5 and type `$togglereact 2`, since most server have button embeds enabled for all rolls and also how you can recreate this problem.

Additional context
```
2024-09-09 05:04:45,285:Wished Cecilia Immergreen from hololive with 37 Value in Server id:<REDACTED>
Our user rolled in <REDACTED>
2024-09-09 05:04:47,677:Sniping time waited Reaction was added
Our user rolled in <REDACTED>
Our user rolled in <REDACTED>
Our user rolled in <REDACTED>
Our user rolled in <REDACTED>
Our user rolled in <REDACTED>
Our user rolled in <REDACTED>
Our user rolled in <REDACTED>
Our user rolled in <REDACTED>
Our user rolled in <REDACTED>
2024-09-09 05:05:14,579:Fandead from hololive appeared attempting to snipe in <REDACTED>
```
![image](https://github.com/user-attachments/assets/6e9106db-eaaf-4849-8d3d-dddb46dc7f94)

**Comment by vivinano** [comment]
So it doesn't react to buttons at all ?

**Comment by WatameBytes** [comment]
Nope, it does not react to buttons at all. It just tries to react to it with an emoji instead and of course that fails to claim.
