### ISSUE TITLE
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'

### ISSUE THREAD

**Issue by cavv-dev** [vivinano/MudaeAutoBot#282]
Happens when starting bot

![2024-09-16 18_32_14-cavv@cavvhome_ ~_MudaeAutoBot](https://github.com/user-attachments/assets/253b20c9-60b2-4ad5-adf5-4ef09afc2c90)

**Comment by vivinano** [comment]
It needs discord.py-self not the regular discord.py Sent from my iPhoneOn Sep 16, 2024, at 12:38 PM, Cavv ***@***.***> wrote:﻿
Happens when starting bot
***@***.***_._MudaeAutoBot.png (view on web)
