### ISSUE TITLE
What changes in the new update?

### ISSUE THREAD

**Issue by DaMagicFox** [vivinano/MudaeAutoBot#29]
Title. I'm interested in knowing what's new and what possibilities we have now.

**Comment by vivinano** [comment]
basically the update is the foundations for getting cleverer in the bot's interactions
the biggest change of the new update is automatic server settings detection in an attempt to maximize snipes and efficiency
which allows for:
- you no longer need to configure kak_delay/claim_delay; it will automatically adjust based on the sniping rules of the server it's attempting to claim in
- sniping will now recognize whether a given roll was rolled by bot user or wished by user, and determine whether it can insta-snipe
- no more 'multichannel' vs 'channel_id', it's all just 'channelids' now
- it will now roll only up to how many rolls there are in the channel
- full recognition of when the claim windows reset on each server

**Comment by vivinano** [comment]
No further questions have been asked. Will be resolving issue

**Comment by DaMagicFox** [comment]
> basically the update is the foundations for getting cleverer in the bot's interactions
> the biggest change of the new update is automatic server settings detection in an attempt to maximize snipes and efficiency
> which allows for:
> 
> * you no longer need to configure kak_delay/claim_delay; it will automatically adjust based on the sniping rules of the server it's attempting to claim in
> * sniping will now recognize whether a given roll was rolled by bot user or wished by user, and determine whether it can insta-snipe
> * no more 'multichannel' vs 'channel_id', it's all just 'channelids' now
> * it will now roll only up to how many rolls there are in the channel
> * full recognition of when the claim windows reset on each server

I had forgotten to reply. Does this mean that it basically knows if it is either, wished by no-one (instaclaim if settings allow it), wished by the user(instaclaim if settings allow it), or wished by someone else(if it's in settings, wait for the togglesnipe to wear off)?

**Comment by vivinano** [comment]
Yes based on $settings in theory

**Comment by DaMagicFox** [comment]
> Yes based on $settings in theory

is there a way for me to check how it's working?

**Comment by vivinano** [comment]
you can try out a test server and force a True statement to trigger to initiate a claim since with the new update the bot no longer reacts to $im characters or it shouldn't react to them

**Comment by DaMagicFox** [comment]
> and force a True statement to trigger to initiate a claim 
How would I do that?

**Comment by vivinano** [comment]
easiest for me is changing min kak to like 10 so i will attempt to snipe anything over 10 kakera if you really want to burn a claim

**Comment by vivinano** [comment]
But do keep in mind if you are trying to test on your account it will devour your claim for that hour and it will not attempt to claim until the next claim window hence ignoring the possible wished character or a character you actually want. this was implemented to follow the tread for kakera sniping where is tries to ignore kakera when you are unable to kakera react

**Comment by DaMagicFox** [comment]
> But do keep in mind if you are trying to test on your account it will devour your claim for that hour and it will not attempt to claim until the next claim window hence ignoring the possible wished character or a character you actually want. this was implemented to follow the tread for kakera sniping where is tries to ignore kakera when you are unable to kakera react

yeah, that's why I would do it in a testing server

**Comment by vivinano** [comment]
alright then changing any check criteria so that it will always be true could test the claim window setting. wish testing would be a little more harder to test you would have to get a wish to test that out but the claim window is still the same

**Comment by DaMagicFox** [comment]
> alright then changing any check criteria so that it will always be true could test the claim window setting. wish testing would be a little more harder to test you would have to get a wish to test that out but the claim window is still the same

The thing I really want to test is what happens if the character is wished by someone else and togglesnipe is activated.

**Comment by vivinano** [comment]
as long as the togglesnipe allows you to snipe it will attempt to snipe it basically there are settings that block the attempt to snipe wished characters so even if you didnt use the bot and were a user you couldnt snipe it so a attempt would not be made as this is a impossible case 

but in any other case it will snipe it and the only way to test is that I guess make that criteria happen and if there is a issue i can revisit that issue

**Comment by DaMagicFox** [comment]
> as long as the togglesnipe allows you to snipe it will attempt to snipe it basically there are settings that block the attempt to snipe wished characters so even if you didnt use the bot and were a user you couldnt snipe it so a attempt would not be made as this is a impossible case
> 
> but in any other case it will snipe it and the only way to test is that I guess make that criteria happen and if there is a issue i can revisit that issue

Yeah, but the togglesnipe is set at number 4 with 4 seconds (When someone rolls a WISHED character, this character can't be sniped for 4 seconds EXCEPT for people wishing for this character (the roller CAN'T claim this character either, except if they wished for it))

**Comment by DaMagicFox** [comment]
Which means there is in fact a moment in which I can claim.  I used to "bypass" this by using this code for character list.

time.sleep(1)
                    
                    if "reactions" in bot.getMessage(channelid, messageid).json()[0] and bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]['id'] == None:
                        bot.addReaction(channelid, messageid, bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]["name"])
                        time.sleep(1)
                        bot.removeReaction(channelid, messageid, bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]["name"])
                        time.sleep(claim_delay)
                        bot.addReaction(channelid, messageid, bot.getMessage(channelid, messageid).json()[0]["reactions"][0]["emoji"]["name"])

**Comment by vivinano** [comment]
> ![image](https://user-images.githubusercontent.com/33008397/119217243-dffa6a80-baa6-11eb-877a-dcfd9ea4c850.png)

so its coded like this if your really worried about snipe_delays vs insta_snipe scenarios in theory it will work but again since this is a big update I can't confirm if there is a bug and if something will fail 

again there is a stable branch if you don't want to chance a possible fail 

you can change the current one into the similar way  as the insta snipe or having to wait only set the snipe_delay variable

**Comment by condorsail** [comment]
> Yeah, but the togglesnipe is set at number 4 with 4 seconds (When someone rolls a WISHED character, this character can't be sniped for 4 seconds EXCEPT for people wishing for this character (the roller CAN'T claim this character either, except if they wished for it))

the claim delay does actually seem to adjust to the specific snipe settings correctly

If you run `get_snipe_time` with your proposed scenario:
r = 4  (snipe setting of the server)
d = 4.0 (locked for 4 seconds if snipe state triggered)

If you're in the wishers list,
returns 0 (instasnipe available)

If you're NOT in the wishers list -- regardless of if you rolled or not
returns `d`

get_snipe_time for example also accurately recognizes this state:
`r` = 1 (partial restriction -- only if the ROLLER wished for character, then lock sniping for `d` time to only the roller)
`d` = (a non-zero delay)

returns 0.0 if `rolled` isn't in the `wished_for` list *or* if `rolled` is our user
returns `d` *only* if `rolled` isn't us **and** `rolled` appears in `wished_for`
