### ISSUE TITLE
A problem with the bot

### ISSUE THREAD

**Issue by frannvg** [vivinano/MudaeAutoBot#30]
Hi, I speak Spanish so I know very little English I hope you understand me. I recently downloaded your bot for Mudae and I realized that the program did not claim other people's rolls, it asked you if this can be solved or if it works like this

**Comment by vivinano** [comment]
It should claim other people rolls as long as you haven't already claimed within the claim window so if something is claimed to avoid looking very bot like it will ignore trying to claim that.

I would need more information to determine if there is a problem but it should claim both personal and other peoples rolls

**Comment by vivinano** [comment]
> ![image](https://user-images.githubusercontent.com/33008397/118896640-aecb4000-b8d6-11eb-84a4-224fb0db1876.png)

as you can see here it claims different user rolls so it might have been that you have already claimed and it skipped to not be bot like so it will snipe in a 1st come 1st serve kind of basis

**Comment by vivinano** [comment]
Haven't heard back. will be closing this issue as i assume it has been resolved
