### ISSUE TITLE
Bot does not react to a kakera / waifu

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#31]
I downloaded the most up-to-date version of the boat I configured Settings_Mudae.json this way

![image](https://user-images.githubusercontent.com/82736191/119212074-8dac5000-ba8c-11eb-8caf-cf60ce529825.png)

During the roll of people this appears.
Before he asked to use $ settings and then start the bot, but if I do it every time I need to open the bot, it will be very suspicious.

![image](https://user-images.githubusercontent.com/82736191/119212039-6190cf00-ba8c-11eb-9ba4-0fa26b3960e7.png)

The bot even ignored even kakera free

EDIT: The server uses custom reaction

**Comment by vivinano** [comment]
it should find the $setting message so it shouldn't post everytime can u send me a image of a previous $settings from mudae

**Comment by BellaDona007** [comment]
Perhaps the server is in PT-BR it does not identify $settings.
I started from scratch, putting only token and channel_id

![image](https://user-images.githubusercontent.com/82736191/119213296-73767000-ba94-11eb-930c-77b7c8d0b9be.png)

**Comment by vivinano** [comment]
> ![image](https://user-images.githubusercontent.com/33008397/119214933-72dfd880-ba98-11eb-92c3-a07eda1c6ad7.png)

im still able to parse settings from pt-br lang as above it still able to parse in a different language on your test servers 

the bot will stop posting $settings if it finds "any" instance of settings in the "Server/Guild" so if it finds any message that has settings It will not post $settings 

is there an image of $settings in the server you play on ??

**Comment by vivinano** [comment]
also any issues going forward it would help if I got the issue from the live server as 
the error in your second case is that the server setting were not found and that was fixed by settings being given by mudae. 

while your 1st error was because it was unable to unpack 1 variable in 2 variables so having the actually structure of your "gaming" server would keep me fixing the issue while giving me a image of the "test" server creates a non-existent issue into a issue

**Comment by BellaDona007** [comment]
> is there an image of $settings in the server you play on ??

This is the image I sent earlier, togglesnipe is set in 4 seconds

![image](https://user-images.githubusercontent.com/82736191/119234636-58901400-bb05-11eb-9980-4f14670320b5.png)


I think I'm just being very stupid because the steps I took on the first use were:

Open Settings_Mudae.json and set the token and channel_ids, set false rolling, pkmrolling and deleted the names in series_list, namelist and set min_kak 300.

I used $settings on the channel defined in channel_ids and opened the bot

**Comment by vivinano** [comment]
compare the $settings with the one I have if there a structural difference and try to get a snipe to happen and see if there an issue as all that does is give a snipe delay that is appropriate

**Comment by vivinano** [comment]
Issue with the settings have been resolved there was a formatting error when toggle snipe settings were set to 0
