### ISSUE TITLE
instasnipe too fast for mudae?

### ISSUE THREAD

**Issue by RecentYogurt** [vivinano/MudaeAutoBot#33]
is there any way to increase the delay of the instant snipe feature. I just assume that it can sometimes not work like how when you set claim delay to zero. Setting it so that it reacts in like 0.4-0.6 seconds would be pretty cool as it's faster than most humans can react and it won't get eaten by mudae when the mudae is slow sometimes. 
EDIT: It still works it was just a potential concern of mine

**Comment by vivinano** [comment]
> ![image](https://user-images.githubusercontent.com/33008397/119301276-30e99a80-bc30-11eb-8624-d01a0199f997.png)

on line 299 there is a small delay added that can be adjusted in both cases of insta snipe and delayed snipe

**Comment by RecentYogurt** [comment]
thank you

**Comment by vivinano** [comment]
I would like to state that this delay was already in the code so @RecentYogurt you might want to increase that how you see fit 

the default value was already set to (.5) to avoid any kind of confusion about there being no change
