### ISSUE TITLE
Roll does not complete, kakera delay does not work correctly.

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#34]
Good afternoon,

I am testing the latest version and it is almost 100% thank you very much for all the work done so far.
But when starting the roll, after rolling 10x he stopped, I started rolling it manually and he took the kakera from the $embedcolor chosen in the configuration, but then the second problem came, he did not try the following ones, in the first version I used, he tried until he received a message that was not possible, and used that time for a next attempt.

![image](https://user-images.githubusercontent.com/82736191/119553226-d22c3a00-bd71-11eb-8cc5-f97b82db6426.png)

EDIT: embedcolor not work :(

**Comment by vivinano** [comment]
By any chance do you have mudae premium perks ? Like player prem or server prem

**Comment by BellaDona007** [comment]
> By any chance do you have mudae premium perks ? Like player prem or server prem

Rolls per hour: +7 (6 $k + 0 $kl + 1 $kt)

**Comment by vivinano** [comment]
ah okay basically the code was added as a safety check to prevent over spamming incase of mudae locking up and causing constant rolling spam so give me a bit to figure out how to get a stable way to get extra rolls

**Comment by BellaDona007** [comment]
Any prediction of when embedcolor will work again?

**Comment by vivinano** [comment]
Yes the safety check was added to keep the bot from spamming just in case something happens using the server setting that are parsed into the bot this didnt take into account extra rolls so a way to keep that safety check in while allowing the bot to roll is what will currently be fixed

**Comment by BellaDona007** [comment]
> Yes the safety check was added to keep the bot from spamming just in case something happens using the server setting that are parsed into the bot this didnt take into account extra rolls so a way to keep that safety check in while allowing the bot to roll is what will currently be fixed

And the problem with the kakera delay?

**Comment by vivinano** [comment]
what kakera delay ? If it was a previous issue I closed it as there was no response for a while ? Do I need to revisit an issue ?

**Comment by vivinano** [comment]
if it skips kakera can you confirm that you still had kakera power ?

**Comment by BellaDona007** [comment]
> if it skips kakera can you confirm that you still had kakera power ?

Yes, he had kakera power full, he only took it once and ignored the others.
Another thing that happened now, if you can answer, the claim is extremely slow, even if I put 0 in claim_delay

**Comment by vivinano** [comment]
when it goes to claim_delay is is effected by if you roll or another person rolls if its something u rolled its instant snipe if its rolled by someone else it waits the time set by server

**Comment by BellaDona007** [comment]
> when it goes to claim_delay is is effected by if you roll or another person rolls if its something u rolled its instant snipe if its rolled by someone else it waits the time set by server

It was in my roll, I saw it stopped for almost half a second, it was time for someone to click and then the bot click, unfortunately I play with people who are extremely fast since 2018, I would even be able to catch it if I had the mouse over the reaction .
Is it possible to make it faster for my rolls or other people's rolls?

**Comment by vivinano** [comment]
there is a small .5 delay added because in the case of instant snipes becasue instant snipes arent registered by mudae

**Comment by BellaDona007** [comment]
Is it possible to decrease to something smaller, but not zero?

**Comment by vivinano** [comment]
refer to isssue #33

**Comment by BellaDona007** [comment]
Thank you very much, I look forward to the kakera delay and the adaptive rolls

**Comment by vivinano** [comment]
commits were pushed to solve the issue here except for $embedcolor as its not a priority fix 
there might be bugs just let me know how it goes

**Comment by BellaDona007** [comment]
I just tested the roll on a server that has more than 50 rolls, after 20 rolls he used $ru and continued until he got the message "the roulette is limited to 20 uses per hour (high traffic hour). XX min left." 
I haven't had a chance to test the kakera delay yet

**Comment by vivinano** [comment]
Edit1:
i set it to default emoji because it was more general when in terms of multiserver you can change each instance of ❤️ to whatever emoji u want if its a custom emoji its need both emojiname : emojiid 

Edit2: turn tyco to "False" and it should go back

**Comment by BellaDona007** [comment]
> Edit1:
> i set it to default emoji because it was more general when in terms of multiserver you can change each instance of ❤️ to whatever emoji u want if its a custom emoji its need both emojiname : emojiid
> 
> Edit2: turn tyco to "False" and it should go back

**Comment by BellaDona007** [comment]
> refer to isssue #33

I tried to make it as fast as possible, the bot is still very slow to get things, if it is on a server where only I play, it serves, but if it is on a competitive server it will always lose, even to get the freekakera is fine slow always losing and being the last to react

claim_delay 0
time.sleep(.1)

![image](https://user-images.githubusercontent.com/82736191/119705147-cb173180-be2e-11eb-9d7a-930f620a9510.png)

**Comment by vivinano** [comment]
so does your competitive server have no snipe protection ? and its a free for all ?

**Comment by BellaDona007** [comment]
No, everything is free
togglesnipe 0
kakerasnipe 0

**Comment by vivinano** [comment]
and about how long does it wait to snipe ?

**Comment by BellaDona007** [comment]
> and about how long does it wait to snipe ?

It seems from the log a and almost 2 seconds, even with

`claim_delay 0`
`time.sleep(.1)`

In the old bot when discord.py supported it it didn't happen, it was extremely fast

**Comment by vivinano** [comment]
no that just means that its hitting 2 checks character and series check

**Comment by vivinano** [comment]
discord.py and discum are 2 different libraries and handles things differently discum is 
"Thread" based and discord.py was "async" so while my code functions the same. the things happening in the background are different but I have no control of that

**Comment by vivinano** [comment]
the original issue of the rolling not completing should now be resolved in the most recent commit 

it now will roll until either it sees the '2 ROLLS LEFT' warning if the user has `$rollsleft` enabled at which point it will only roll 2 more times, or in the worst case, rolls until it sees the message 'the roulette is limited to X uses per hour'

**Comment by BellaDona007** [comment]
> the original issue of the rolling not completing should now be resolved in the most recent commit
> 
> it now will roll until either it sees the '2 ROLLS LEFT' warning if the user has `$rollsleft` enabled at which point it will only roll 2 more times, or in the worst case, rolls until it sees the message 'the roulette is limited to X uses per hour'

I will test for about 3 hours with an account with 70 rolls, another with 20 and another with 17
