### ISSUE TITLE
Bot continues to react to already married character

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#35]
Hellos,

It occurred 2 times on the server while not looking, it has a reaction custom and the bot uses ❤ next to the custom reaction.
Both characters were on the namelist and attended the min_kak
Is that normal?

**Comment by vivinano** [comment]
it should stop but the code that sets the skip is based on when mudae edits the existing post so if mudae has not edited the 1st claim then it did not set the new claim window

**Comment by BellaDona007** [comment]
I did not understand :(

**Comment by vivinano** [comment]
i need an example as i seem to not be understand what you mean by this then ?

**Comment by BellaDona007** [comment]
I mean that the character appeared like this but with different embedcolor for having key lvl 1

![image](https://user-images.githubusercontent.com/82736191/119720138-fc4c2d80-be3f-11eb-82a3-6fa7e85fd5d2.png)

And yet the bot understood that the character was free and reacted.
This happens if the name of the character is in the namelist, I don't know if it happens if it is only for min_kak.

Just stating that the server uses custom reaction

**Comment by vivinano** [comment]
when was the last time you updated the bot ? 

`claimed = int(embeds[0].get('color',0)) not in (16751916,1360437)` 

this code should stop reaction if they are claimed as they dont have owned or wished color set

**Comment by BellaDona007** [comment]
> when was the last time you updated the bot ?

I was using the latest version when I opened the topic

**Comment by vivinano** [comment]
alright just making sure

**Comment by vivinano** [comment]
unsure currently can't reproduce the scenario so unsure how to fix. feel free to reopen if this scenario happens again
