### ISSUE TITLE
Question about bot functionality and settings.

### ISSUE THREAD

**Issue by DaMagicFox** [vivinano/MudaeAutoBot#36]
If the new bot is supposed to know the optimal wait time until claim, when does the time you set in Settings_Mudae.json come into play?

**Comment by vivinano** [comment]
just in case I have to go back to the static settings. has the snipes been optimal for you ?

**Comment by DaMagicFox** [comment]
> just in case I have to go back to the static settings. has the snipes been optimal for you?

I'm not 100% sure on the fact of if I was using the new or the stable version, but I think it was the new one. I managed to snatch a claim on a character someone else wished.

**Comment by vivinano** [comment]
well the stable version doesnt have the optimal snipe predicition so I think you were using the "main" (New) branch. I've been making some more optimizations here and there so there might be possible bugs so just feel free to let me know

**Comment by DaMagicFox** [comment]
> well the stable version doesnt have the optimal snipe predicition so I think you were using the "main" (New) branch. I've been making some more optimizations here and there so there might be possible bugs so just feel free to let me know

Yeah but i have my stable branch setup with a bypass to the togglesnipe time.

**Comment by vivinano** [comment]
well if urs use snipe_delay then it the new one if its using claim or kak delay then is the old stable version
