### ISSUE TITLE
Claim wished

### ISSUE THREAD

**Issue by PixelGM** [vivinano/MudaeAutoBot#37]
Seems like the bot doesn't claim the wished chars. Here's the screenshot:
https://imgur.com/a/S22q3ZS

**Comment by vivinano** [comment]
its not showing the image

**Comment by PixelGM** [comment]
try opening the link now, I fixed it.

**Comment by vivinano** [comment]
alright and during this did u have a claim up? how to code works now is that its trying to do what I did with kakera where if it has a cooldown it doesnt attempt to snipe.

**Comment by PixelGM** [comment]
Oh wait, so you're telling me the bot is suppossed to be claiming that? Maybe a cooldown makes it doesn't claim it?

**Comment by vivinano** [comment]
yeah it to prevent spamming if multi things appear and is like hey u know u dont have a claim right ? slowly making it less bot like in behavior 

smarter botting lol

**Comment by PixelGM** [comment]
Ok maybe it was on cooldown.

**Comment by vivinano** [comment]
if it was on cooldown and didnt snipe let me know so I can revisit it.

**Comment by PixelGM** [comment]
I think this is working pretty well actually.

**Comment by myde2001** [comment]
Keeps happening

[](https://i.imgur.com/bQyBVKX.png)
