### ISSUE TITLE
Bot rolls too early

### ISSUE THREAD

**Issue by RecentYogurt** [vivinano/MudaeAutoBot#39]
Bot will roll a minute before roll reset and then won't roll

**Comment by RecentYogurt** [comment]
I'd also like to suggest a feature where it rolls randomly between 1 and 5 minutes after the roll reset to mimic human behavior

**Comment by vivinano** [comment]
that is strange does it get a wait timer or times out ? cause
logically if it rolls a minute b4 then mudae should give the bot a wait timer of 1 min and then it will wait another minute and roll again ? can you send an image of this issue happening with the wait timer that it print in the console

**Comment by RecentYogurt** [comment]
It happened on the latest version, but I'll see if I can get it to do that again. I'm not sure what caused it

**Comment by vivinano** [comment]
basically whenever it rolls early since its dynamically obtained if it rolls at

6:14 and roll reset is at 6:15 

mudae should reply with 

Username. the roulette is limited to X uses per hour (high traffic hour). 1 min left.

and then on the console it should print `Waifu Roll:60` and wait for 60

**Comment by vivinano** [comment]
Haven't Received any other comment on this issue closing for now until issue can be reproduced
