### ISSUE TITLE
How do you correctly install discum

### ISSUE THREAD

**Issue by Effyman** [vivinano/MudaeAutoBot#40]
I tried installing through command prompt as some articles suggested but it doesn't detect the package~~
There wasn't any instructions on the Readme about that so I thought it's common sense but I'm struggling~
I'm using 3.8.1 python and got my discum zip file from github so it's latest version.

**Comment by vivinano** [comment]
you followed the instruction on discum's repo itself ?

**Comment by Effyman** [comment]
Turns out I completely missed the part where I had to run the command in git, I was running it in default command prompt~~
It works now! Thx for taking the time to help~

**Comment by Effyman** [comment]
![image](https://user-images.githubusercontent.com/85018951/120073123-51ce4780-c097-11eb-83ad-2af8b18ecb97.png)
I have another question, It says here to edit a line in .py file to make the emoji thing work, which line am I editing though?~

**Comment by vivinano** [comment]
currently that was for the bot when it was still using discord.py so its currently not implemented yet but the bot u can still technically use it but it not a simple change 

the bot does check if there is an existing emoji that was added by mudae and adds that instead

**Comment by Effyman** [comment]
Oh okay gotchu~
If you don't mind I have another question about instasnipe, for some reason when I set Claimdelay to 0 (main branch) it reacts after 1 second, I tried the stable branch and it reacts just a but faster but no where near instasniping (A lot of my friends can easily outsnipe it), how do I make it to react as fast as humanly possible without worrying about people detecting if I'm using a bot or no?

**Comment by vivinano** [comment]
So the new one in main get its snipe delays from seeing if there is snipe protection the time that you are unable to react so it does a lot of background thing to see what is the most effective sniping time there is a set .5 sec delay added to give mudae time to process that it can be reacted to 

Ultimately it comes down to runtime of the code < then goes to discum’s speed to interact with the discord api (out of my control) < and then time mudae takes to react to the bot

While the bot might only take .7 seconds you got to factor other factors 

So a lot of features were added in the main branch to try to hide that you possibly are a bot like claim Windows and kakera react Windows that get set accordingly 

So there is a time.sleep within the snipe delay function that u can remove but you might react to fast where mudae just ignores it

**Comment by Effyman** [comment]
Which line is the snipe delay function/where can I remove time sleep? I don't really understand the code but I wanna experiment with removing the delay and such~

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/120120697-f8384c80-c16c-11eb-970b-89cc64cc3bef.png)

right there if u wanna play with it

**Comment by vivinano** [comment]
Closing issue as initial problem has been resolved
