### ISSUE TITLE
Difficulty starting / running the bot

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#41]
Hello,

Whenever I try to open the bot while they are running, this message appears, even with the bot all configured, and when it works, the error of the second message occurs, I defined `min_kak 10`, to try to reach a real reaction value of the bot, when has togglesnipe on

![image](https://user-images.githubusercontent.com/82736191/120079892-7244d480-c08c-11eb-8b9b-10f3041456bd.png)

There were cases where I simply gave up on starting the bot, as I always presented the message asking for $settings

PS: I am using the latest version of the bot and my entire configuration was in Settings_Mudae.json
DisCum version 1.3.0

**Comment by vivinano** [comment]
I have my min_kak defined as 10 can i see your $settings 

there seems to be an issue parsing since its getting 2 many variables

**Comment by BellaDona007** [comment]
> can i see your $settings

![image](https://user-images.githubusercontent.com/82736191/120085697-a631f100-c0b0-11eb-936a-a91b072484ab.png)

**Comment by vivinano** [comment]
insert `print(channel_settings[channel]['claim_snipe'])` b4 `line 194` and tell me what it printed out cause im not getting any issues

**Comment by BellaDona007** [comment]
> print(channel_settings[channel]['claim_snipe'])
![image](https://user-images.githubusercontent.com/82736191/120087236-991aff00-c0bc-11eb-96d3-7f90f9c3b0a0.png)


Presented this error:
![image](https://user-images.githubusercontent.com/82736191/120087222-77217c80-c0bc-11eb-97bf-e0109a1f99f1.png)

**Comment by vivinano** [comment]
no not replace `r,d = channel_settings[channel]['claim_snipe']`

but the print statement before it

**Comment by BellaDona007** [comment]
![image](https://user-images.githubusercontent.com/82736191/120087812-9b338c80-c0c1-11eb-87db-5b8a30ab4a1d.png)


Now he reacted by marrying the waifu, and presented this error at the end
![image](https://user-images.githubusercontent.com/82736191/120087818-a7b7e500-c0c1-11eb-8fc1-1819964d8151.png)

**Comment by vivinano** [comment]
ya if it a DM then guild ID breaks

**Comment by BellaDona007** [comment]
The bot keeps asking for $settings all the time and does not start up, it was already working, but now it keeps asking.

**Comment by vivinano** [comment]
so Its blocked on the whole server and there is no channel that has a $settings instance ?

**Comment by BellaDona007** [comment]
> so Its blocked on the whole server and there is no channel that has a $settings instance ?

no channel that has a $settings instance

**Comment by vivinano** [comment]
So I replaced $setting posting with a default $settings wall of text in the code 

so it no longer will send $settings but instead go off default settings within the code

**Comment by BellaDona007** [comment]
I downloaded the new version of the bot, and the problem asking for $ settings all the time does not occur, but now it is not rolling

![image](https://user-images.githubusercontent.com/82736191/120229180-f630c500-c222-11eb-9d68-7f9c1eb2056b.png)

**Comment by vivinano** [comment]
The code changes made doesn’t effect rolling at all

**Comment by vivinano** [comment]
Alright gonna assume this is fixed

**Comment by BellaDona007** [comment]
When other people are rolling, the bot does not start and presents these 2 variables that do not start the bot

![image](https://user-images.githubusercontent.com/82736191/120361823-b6301780-c2e0-11eb-9ecc-46ecf1ce441c.png)
