### ISSUE TITLE
Discum install

### ISSUE THREAD

**Issue by NightCrii** [vivinano/MudaeAutoBot#42]
Im not entirely sure how to install this. I have python 3.9 and im not entirely sure what im supposed to do from here. The information on the main repo for discum didn't help me at all. Im not familiar with this at all to be honest.

**Comment by vivinano** [comment]
its okay what issues are you having with installing discum I will try to walk you thru it 

I had some trouble installing discum also so your not the only one basically you have to install the library thru

pip3 but also thru git if you ever use git b4

its basically goes along the lines of

'pip3 install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git'

thats if you are have both of them in your PATH

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/120090135-231f9380-c0ce-11eb-8581-e4e19b9bc41b.png)

so i ran that code in git if it helps

**Comment by NightCrii** [comment]
Im kinda confused. What is git? Is that something else I need to have installed?

**Comment by vivinano** [comment]
git is cmd thing usually used with github. your honestly just using `git` in this case to pull a repo and install it as a python library

**Comment by NightCrii** [comment]
After running that command it says "bash: pip3: command not found
I made sure I put the command in exactly as stated. I have git installed now version 2.31.1
Is there anything else I am supposed to before entering this command into git?

**Comment by vivinano** [comment]
is python and pip added into ur PATH ? if not u have to run a differenent command 
which is 
`python -m pip install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git`

**Comment by NightCrii** [comment]
I just added python to my path but git wasn't added. Ill add it now and try again. If it doesn't work Ill try the second command

**Comment by NightCrii** [comment]
Is there a specific way I need to add these to my path? I tried both commands and nothing is working for me.
![Screenshot 2021-05-30 124050](https://user-images.githubusercontent.com/82667084/120091247-4ab14300-c144-11eb-86d1-e33e80a03334.png)

**Comment by vivinano** [comment]
wrong way to do path uh you double click ur PATH
and then add the file path

**Comment by NightCrii** [comment]
Oh I made a mistake from the very beginning. When I installed python the first time I didn't check the box to add it to my path. After reinstalling it and making sure that was checked, the command worked. After that is finished, what am I supposed to do? It says it was installed

**Comment by vivinano** [comment]
discum is installed ? or python is installed ?

**Comment by NightCrii** [comment]
![image](https://user-images.githubusercontent.com/82667084/120092227-3709da80-c14c-11eb-8c9c-f93353b33e60.png)
I got to this point. Python is installed now. I ran the command through git and this popped up. What do I do now?

**Comment by vivinano** [comment]
i think your good to go now

**Comment by NightCrii** [comment]
I guess my last question would be what do I do now? I don't see an exe or anything to use. Also thank you for helping me out with the discum install. Never would have figured it out lol

**Comment by vivinano** [comment]
you launch mudaeautobot.py either with CMD or IDLE  after setting up your setting.json 
one thing that is important not to share for security reasons is your "User-Token" there are guides on how to get it online but if you need help just let me know but please do not post it any where and let it get leaked it does give full access to your discord account

and no problem It what im here

**Comment by BellaDona007** [comment]
You need git installed because you're installing from github.

https://stackoverflow.com/questions/29565779/cannot-find-command-git-windows

**Comment by vivinano** [comment]
assuming there is no longer issue and program is running successfully
