### ISSUE TITLE
Rolls sniping: 3

### ISSUE THREAD

**Issue by benjiton** [vivinano/MudaeAutoBot#43]
Hello,

If someone else rolls, but the character is still wished by me, the script still waits the seconds (in this case 8), even though Roll's sniping is set to 3 and he should claim instantaneously.

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/120176939-d9ba6b80-c1d5-11eb-90e1-81feb5c007d0.png)

logic wished it should return 0.0 as if 

r > 2 includes togglesnipe 3 and if your name was in the wish ? did you set private wish ? where ur name does not appear on top of the character ?

**Comment by benjiton** [comment]
![timetimetime](https://user-images.githubusercontent.com/13102000/120180815-86174480-c20c-11eb-9a8d-d3ebfa66b10f.jpg)

**Comment by vivinano** [comment]
it also goes off the most recent $settings call so if there is a old $setting that has a different toggle snipe that also might cause issue and make it think to act a different way

**Comment by vivinano** [comment]
Also did you see it take the whole 8 seconds cause there are cases where it could snipe 2 fast where mudae doesn’t register that u reacted unsure if you also have the logs for when the character was detected and sniped ?

**Comment by benjiton** [comment]
![mudaeboasdasdj](https://user-images.githubusercontent.com/13102000/120240265-6d387e80-c260-11eb-8c42-a5b66f80af17.png)

The thing is: I am running on only one server, on which there is only one instance, with one channel, where the settings have not been changed since the server started.
And I would still understand if he would react and the bot does not react because too fast. However, even the reaction is missing.

**Comment by vivinano** [comment]
it first tries to find a $setting instance if one is found it uses the most recent one so if u used $settings b4 doing any changes then it will use the one before any changes to fit the server is applied

the bot also has a claim window so it will attempt to claim 1 thing on a 1st come 1st serve basis and then after a successful claim it will ignore the rest regardless until the next claim window

**Comment by vivinano** [comment]
I would like to state tho the `stable branch` of the repo has less of the predective features so you could use that for a more consistent snipe if you so choose

**Comment by benjiton** [comment]
I think I have located the essential difference / problem. In gamemode two we still have $servlimroul as an additional value in the settings, which causes everything to slip by one line
![serverlimroul](https://user-images.githubusercontent.com/13102000/120241887-f8ffda00-c263-11eb-8ce1-2a117cc00b41.png)

**Comment by vivinano** [comment]
we have accounted for this and since it does not follow the schema set by the 

RegEx:  it skips this line 

![image](https://user-images.githubusercontent.com/33008397/120242287-8c201c00-c232-11eb-8d36-4f9d649158cd.png)

as you see $servimroul does not have a   Word followed by a ":" hence forth it does not change the setting values

**Comment by benjiton** [comment]
Is it possible that if you have two channels, the settings command should only be executed in the first one? Because every time I do $settings it always takes 1 as value instead of 3.

**Comment by vivinano** [comment]
It will obtain the $settings for the server using the search parameters from:mudae and text search 

But either way it is the most recent so in discord itself you can search those terms normally and see what the first result that comes up and that what the bot will receive

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/120243805-8b898480-c236-11eb-8e4f-810eab7dacf9.png)

you can try doing print(settings['claim_snipe']) and it should print out the values your are getting to see if it is correct 

it should be a list

[3,8.0]  the 1st denoting the claim mode and the 2nd denoting the wait time

**Comment by benjiton** [comment]
I got the right one out first:

![image](https://user-images.githubusercontent.com/13102000/120244010-5ba7a480-c269-11eb-82fb-b39e8dd9a6f2.png)

However, afterwards no more, there it took each time 1 as value.

The situation is this: there are two instances. The first consists of a roll channel and a mod channel. However, I have not specified these in the config. The second instance consists of two "roll" channels and one mod channel. 

![image](https://user-images.githubusercontent.com/13102000/120244047-78dc7300-c269-11eb-902a-f4de0a523f95.png)

After I got in the second roll channel unsuccessfully always the 1 set, I fetched in the first roll channel of the second instance settings and there he felt it then also with 3. However, I would not like to want to use every time because $settings command in the first channel.
It otherwise looks very suspicious every time

**Comment by vivinano** [comment]
It doesn’t matter how many channel there are it will find the $settings that is the most recent in the server what ever channel that “you” have access to and it seems that based on the print it’s correctly parsing the settings and that the problem lies elsewhere 

When does it change back to 1 ?

**Comment by vivinano** [comment]
so how you server works are there several channels that have different settings per channel within 1 server ?

**Comment by benjiton** [comment]
Bot restarted and again 1 instead of 3.
![image](https://user-images.githubusercontent.com/13102000/120316176-6b60d080-c2dd-11eb-88b0-a16dfbcf7093.png)

There are two instances (2 of 4 with server premium 2).
First instance: Gamemode 1 with claim 1

Second instance: Gamemode 2 with claim 3

But in the json are only the channels for the second instance

**Comment by benjiton** [comment]
![image](https://user-images.githubusercontent.com/13102000/120317690-40777c00-c2df-11eb-89f8-01f240eb34bd.png)
![image](https://user-images.githubusercontent.com/13102000/120317730-4bcaa780-c2df-11eb-8191-4dc59f868c09.png)

The two channels that are used only for scrolling are empty and the third (id 847036003894034432) one has the entry only once

![image](https://user-images.githubusercontent.com/13102000/120317898-77e62880-c2df-11eb-9bdc-a85484b9b270.png)
![image](https://user-images.githubusercontent.com/13102000/120318056-a82dc700-c2df-11eb-9d9a-d855e9bfe701.png)

**Comment by benjiton** [comment]
![image](https://user-images.githubusercontent.com/13102000/120319048-db248a80-c2e0-11eb-9509-4af7a0d08f5c.png)

I think the problem is simply the fact that the first message is not even the channel rangezogen to filter more precisely. When I add the channelID, I have to make sure that the channel in the json is the last, otherwise it will be overwritten by the other multichannels.

**Comment by vivinano** [comment]
yes in your case since u have multiple instances it will replace your settings because orginally this was made with 1 server having 1 instance so there basically there is several mudae instances which makes sense as long as it doesnt mess up others that dont have multiple instances in one server I will push the change

**Comment by vivinano** [comment]
So I've made some change it should Write Settings to a file which then can also be edited manually after file creation so things should function as intended now

**Comment by vivinano** [comment]
Haven't heard back. Assumed that fixes applied worked
