### ISSUE TITLE
short 1 roll

### ISSUE THREAD

**Issue by RecentYogurt** [vivinano/MudaeAutoBot#44]
the bot stops rolling 1 prior to using up all rolls

**Comment by vivinano** [comment]
its the feature trying to work on that tries to check rolls so it not always trying to hit the no rolls left warning it sometimes works but sometimes cause issues

**Comment by condorsail** [comment]
Was there someone else rolling at the same time, or is it doing this every time? @RecentYogurt

**Comment by vivinano** [comment]
Just checking in if its still doing 1 short ? @RecentYogurt
