### ISSUE TITLE
Unable to run the bot

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#45]
Hi,

The bot does not start, many people are running and using $ commands all the time.
The bot always has this error:

![image](https://user-images.githubusercontent.com/82736191/120396742-76335980-c30d-11eb-8d60-8d1a38a8a16c.png)

I made the following configuration changes.
min_kak 900
Line 354: time.sleep(.0)

**Comment by vivinano** [comment]
There wouldn't be an issue with people running many $ commands because I will literally do a snapshotted search and do calculations off that as it search message is not a live data stream and if I can't find $setting then it uses the default one within the code

**Comment by BellaDona007** [comment]
Using the latest version of the bot, unfortunately making these changes it doesn't continue and doesn't run

**Comment by vivinano** [comment]
Which changes ?

**Comment by BellaDona007** [comment]
> Which changes ?


Wait for people to shut up, but guess what, I forgot to change the claim_delay and now I'm trying to start again and it keeps asking for $settings because people keep typing ALL THE TIME

**Comment by BellaDona007** [comment]
I try to start and this ALWAYS happens:

![image](https://user-images.githubusercontent.com/82736191/120400597-8ac72000-c314-11eb-9b8e-10400400c01d.png)

**Comment by BellaDona007** [comment]
I've actually been trying to start the bot since the creation of this topic, but without success, it only happened when they were quiet for more than 20s

**Comment by vivinano** [comment]
made changes where it should write $settings to a file and then the 2nd time u run it should read from that created file instead 

so next Quiet moment you can run the bot and it should create a file Settings for future use

**Comment by BellaDona007** [comment]
> made changes where it should write $settings to a file and then the 2nd time u run it should read from that created file instead
> 
> so next Quiet moment you can run the bot and it should create a file Settings for future use
what file is this?

**Comment by BellaDona007** [comment]
Should this happen?
![image](https://user-images.githubusercontent.com/82736191/120542892-092dcb80-c3c2-11eb-9aee-78fef69bdfb7.png)
I tested it on my server and it still shows this error

**Comment by vivinano** [comment]
Update discum to newest version changes were made from their end

**Comment by BellaDona007** [comment]
> Update discum to newest version changes were made from their end

I already use version 1.3.0

**Comment by vivinano** [comment]
https://github.com/Merubokkusu/Discord-S.C.U.M/commit/44403709443e927cf42af52970aa9af96e462dc4

**Comment by BellaDona007** [comment]
> [Merubokkusu/Discord-S.C.U.M@4440370](https://github.com/Merubokkusu/Discord-S.C.U.M/commit/44403709443e927cf42af52970aa9af96e462dc4)

Even so I updated here, I will test and tell if the problem persists when starting with many people typing

**Comment by vivinano** [comment]
it should save a file so if u do get it to successfully run 1 time u can get a txt file with a setting instance saved with the name of your channel id

**Comment by BellaDona007** [comment]
Tried to update using `python -m pip install --user git+https://github.com/Merubokkusu/Discord-S.C.U.M.git` and `pip3 install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git `unsuccessfully, same error occurs when I start the bot

**Comment by vivinano** [comment]
Which error to much traffic error or 

AuthorID error ? 

If it’s authorID you have to update discum because I have no control over that

**Comment by BellaDona007** [comment]
> If it’s authorID you have to update discum because I have no control over that


This same error, do you update as your discum? I used the commands mentioned above and it didn't work

**Comment by vivinano** [comment]
uh I'm not sure what you mean but basically if its not updating then u can switch authorID >> back to userID 

that exactly as typed but you might have to contact the dev over at discum for any discum installation issues 

I have no permission over there

**Comment by BellaDona007** [comment]
How do I get help there?

![image](https://user-images.githubusercontent.com/82736191/120571317-34c7aa80-c3f0-11eb-9bdf-281db9255d4d.png)

**Comment by vivinano** [comment]
same way you get help here submit an issue and some one will assist you in getting the newest install over there as they have more knowledge on that end of things

**Comment by byronsanity** [comment]
try $settings on your server with mudae then run the bot

**Comment by vivinano** [comment]
@BellaDona007 can you do me a favor so i can help out the dev of discum 

> ![image](https://user-images.githubusercontent.com/33008397/120641783-096dab80-c442-11eb-9101-3dcc54b6af0a.png)`

change the log to `True` and when there is a no settings error can you send me the screenshot of the logs so I can describe the error to the DEV ?

**Comment by BellaDona007** [comment]
> try $settings on your server with mudae then run the bot

I will test

**Comment by BellaDona007** [comment]
> > try $settings on your server with mudae then run the bot
> 
> I will test
> 
> EDIT:
> 
> ![image](https://user-images.githubusercontent.com/82736191/120675419-6df13080-c46b-11eb-9d0d-ca1bbba6c5b7.png)
> 
> ![image](https://user-images.githubusercontent.com/82736191/120675549-8e20ef80-c46b-11eb-9a98-afa90badf60c.png)
> 
> When making these changes, it opens and closes quickly

EDIT2:  
This way, it is showing several messages quickly
![image](https://user-images.githubusercontent.com/82736191/120675972-f243b380-c46b-11eb-9d87-6c0c5f8249d6.png)

![image](https://user-images.githubusercontent.com/82736191/120677609-a3971900-c46d-11eb-88ff-8cda6020f856.png)

**Comment by vivinano** [comment]
yeah those messages are the logs of discum itself 

the discum dev need to know what is happening when settings arent obtained so we can make the search message function more consistant so if you run into an error again take a screen shot of that so i can send it to the dev

**Comment by BellaDona007** [comment]
I'm not using the bot all these days, because this problem always occurs, I've reinstalled python and discum and the problem persists
![image](https://user-images.githubusercontent.com/82736191/120965822-c2caca80-c73b-11eb-8c69-6fc4816311e4.png)

**Comment by vivinano** [comment]
As stated this specific issue is because discum has changed it’s library you have to install the latest version of discum that has the changes made 


As the keyword userID has been replaced by authorID if you having issues with the discum installation please contact the devs over at discum about the issue as it is not in my control

**Comment by BellaDona007** [comment]
Unfortunately after 2 days, no one informed me how I can upgrade to the newest version.

**Comment by vivinano** [comment]
what output does it give you when you run the upgrade ?

**Comment by BellaDona007** [comment]
> what output does it give you when you run the upgrade ?

![image](https://user-images.githubusercontent.com/82736191/121375703-50164680-c917-11eb-967f-500493b9e7fa.png)

**Comment by vivinano** [comment]
And you have tried to uninstall and reinstall it correct ?

**Comment by BellaDona007** [comment]
> And you have tried to uninstall and reinstall it correct ?

Yep

**Comment by vivinano** [comment]
well then I don't know what else to do as this is a Python/Discum issue and isn't and issue pertaining to the bot itself

**Comment by BellaDona007** [comment]
> well then I don't know what else to do as this is a Python/Discum issue and isn't and issue pertaining to the bot itself


What commands do you use to update when you need it, or to uninstall?

**Comment by vivinano** [comment]
i use the pip install method within the git bash ui

**Comment by vivinano** [comment]
your question was answered by the DEV of discum

**Comment by BellaDona007** [comment]
> your question was answered by the DEV of discum

Following the steps he indicated, it worked and the bot is working
