### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by byronsanity** [vivinano/MudaeAutoBot#46]
Traceback (most recent call last):
  File "D:\Downloads\Compressed\MudaeAutoBot-main\MudaeAutoBot-main\MudaeAutoBot.py", line 29, in <module>
    settings = json.load(jsonf)
  File "C:\Users\HIGH-GAMING\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\HIGH-GAMING\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\HIGH-GAMING\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\HIGH-GAMING\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 17 column 4 (char 376)

This is what I get when trying to run it.

**Comment by vivinano** [comment]
there an issue with your json file setting 

you can use a json validator and see if you missing commas or there a spacing issue or something

**Comment by byronsanity** [comment]
Okay will try. Will update you on this. Thanks!

**Comment by byronsanity** [comment]
Now I get this. 
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001B688913B50>>
Traceback (most recent call last):
  File "C:\Users\HIGH-GAMING\AppData\Roaming\Python\Python39\site-packages\discum\gateway\gateway.py", line 288, in _response_loop
    func(resp)
  File "D:\Downloads\Compressed\MudaeAutoBot-main\MudaeAutoBot-main\MudaeAutoBot.py", line 603, in on_message
    msg = get_server_settings(gid,matched_channel)
  File "D:\Downloads\Compressed\MudaeAutoBot-main\MudaeAutoBot-main\MudaeAutoBot.py", line 138, in get_server_settings
    msgs = bot.searchMessages(guild_id,userID=[mudae],textSearch="($togglehentai)").json()['messages']
TypeError: searchMessages() got an unexpected keyword argument 'userID'

Sorry not used to debugging Python as I just started in learning it.

**Comment by vivinano** [comment]
So I’m working on a few thing before pushing the commit but the dependency “Discum” changed the keyword on their end so eventually I will push the commit but all it is for now is changing

UserID to authorID

**Comment by vivinano** [comment]
In terms of kakera ? Or characters in the character roll it should print on the console why it is sniping it whether it be from kak value or from char list etc etc

**Comment by byronsanity** [comment]
I removed the "" in the anime list and It kinda work but returns ignore exceptions in the console. Is this okay? When rolling, it does not print the owner rolled but rather prints the exceptions.

**Comment by vivinano** [comment]
yeah so I have it print ignoring character just to have like a log of what was rolled and such  it should be fine. feel free to post a screenshot of the console if you want to be sure. and yeah for settings_mudae 

you should have it empty completly like `variable = [ ]` cause `variable = [""]` will cause issues `variable = [" "]` will probably make anything with a space valid and cause false positives 

personally I like just doing like `variable = ["aaaaaaaaa"]` since that will never be true in the grand scheme of thing but still keep what the variable is suppose to look like

**Comment by byronsanity** [comment]
![image](https://user-images.githubusercontent.com/85207959/120575216-34143000-c453-11eb-9877-a3320cb743c9.png)

here's the settings

![image](https://user-images.githubusercontent.com/85207959/120576085-c963f400-c454-11eb-9fbc-56abef33fc12.png)
this is what i get now

**Comment by byronsanity** [comment]
![image](https://user-images.githubusercontent.com/85207959/120576200-f6b0a200-c454-11eb-8e2b-ec2a3bf7cd2c.png)
heres the settings
![image](https://user-images.githubusercontent.com/85207959/120576217-016b3700-c455-11eb-9eb3-a8edbd15a1cf.png)
this is what i get now

**Comment by vivinano** [comment]
download my latest version of the code and then also download latest version of discum

"discum had a few changes in terms of keywords that been changed"

**Comment by byronsanity** [comment]
It worked. It just displays the "File not found using different method" tho it's rolling just not sure about claiming. Does this snipe other's rolls?

**Comment by vivinano** [comment]
yes it snipes any rolls that fit the criteria

**Comment by byronsanity** [comment]
So is the "file not found using different method okay?

**Comment by vivinano** [comment]
Yeah i set that up today to keep basically if file not found it will attempt to save ur $setting config to a file to use for later instead of searching it constantly

**Comment by byronsanity** [comment]
Aight thank you will be closing this now. Thanks again!

**Comment by byronsanity** [comment]
Just last question. What do I have to set the min kak for the bot to prioritize the likelist?

**Comment by vivinano** [comment]
what do u mean the likelist ? like make it only do char name snipe ??
set it to like a really high amount like 9999

**Comment by byronsanity** [comment]
Yup the namelist in the settings. Sorry I thought it was likelist. So I set it to 9999 then it only snipes the names in the namelist?

**Comment by vivinano** [comment]
yup your good to go also keep in mind that if 2 things happen at once it will do a 1st come 1st serve basis and ignore the other attempt this is normal functionality so before making an issue on character was ignored please confirm these other factors

**Comment by byronsanity** [comment]
what do you mean 2 things happen at once? like 2 chars from namelist was rolled?

**Comment by vivinano** [comment]
yeah so if 2 or 3 rolled at one time it will just attempt until succeeds then get put on a wait timer until the next claim window

**Comment by byronsanity** [comment]
Yup I understand that limitation. Thanks again! Closing issue.
