### ISSUE TITLE
Connection Keeps Dropping / Older Version of Discum 

### ISSUE THREAD

**Issue by nigerianmahogany** [vivinano/MudaeAutoBot#49]
![image](https://user-images.githubusercontent.com/36930848/120602598-2c379a00-c419-11eb-85d5-b3d43a795cce.png)

For some reason it keeps getting stuck in a connection loop. It seemed to work briefly once by spamming the channel with $wa but it stopped and went back to this loop.

**Comment by vivinano** [comment]
it seems like you are running an older version of discum 

this was an issue and discum devs made some changes to their gateway.py so update discum following their instruction 

the version u want to be on is Discum 1.3

**Comment by vivinano** [comment]
No it’s started as the discum new version has logs turned off so wait a while or do something and like something will print

**Comment by nigerianmahogany** [comment]
That's what I mean though. I left it on for an hour or so with rolls and stuff happening but it never prints anything. It's stuck on the first line. Nothing about getting settings either.

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/120714753-a0158900-c491-11eb-9e8e-bb0c12fb9819.png)
 on that line turn the console: to TRUE and see if there is the gateway connection

and also how did u download the bot ? was it thru releases or was it thru just cloning the repo ?

**Comment by nigerianmahogany** [comment]
![image](https://user-images.githubusercontent.com/36930848/120715132-2c27b080-c492-11eb-9c34-82b948760446.png)

No gateway connection. And I downloaded it through releases

**Comment by vivinano** [comment]
uh it failed to auth so it might be issue with the token ?

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/120715559-bff97c80-c492-11eb-94bf-76f2ba58f421.png)

yup right there token '1'

so you didnt put a token in to login to

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/120715979-680f4580-c493-11eb-9d5c-46e257517765.png)

that what a valid token looks like to load in and use discord API

**Comment by nigerianmahogany** [comment]
Oh that's my bad I had two directories and didn't notice I only updated settings for one of them. Thanks
