### ISSUE TITLE
Need Help with setup

### ISSUE THREAD

**Issue by srrfrhmnn** [vivinano/MudaeAutoBot#5]
Need help with first time setup. 
The Settings_Mudae file does not have a good description of what each thing does.

**Comment by vivinano** [comment]
ah okay sorry about that. I tried to make it easy to read via the json file. I'll write a guide on the settings in a bit. the basic gist of it is that is requires the user token token for it to run

**Comment by vivinano** [comment]
Alright I've updated the Readme with a settings if you want to view it and let me know if you have any more questions

**Comment by srrfrhmnn** [comment]
> Alright I've updated the Readme with a settings if you want to view it and let me know if you have any more questions

I think it would be a good addition to add what the unit of time is for the claim_delay/kak_delay values.

**Comment by vivinano** [comment]
Ah okay since most of the thing in mudae were in seconds I assumed it was default to think in seconds but I added it to the readme for future users.
