### ISSUE TITLE
No module name discum

### ISSUE THREAD

**Issue by byronsanity** [vivinano/MudaeAutoBot#51]
I have installed using the command in the discum in git but it still does not detect discum.

**Comment by vivinano** [comment]
can i see the command that was ran and the output via a screenshot ?

**Comment by byronsanity** [comment]
i used this 
python -m pip install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git

It outpust now that requirements are satisifed and it is installed already. but when running the bot its says no module found discum

**Comment by byronsanity** [comment]
![image](https://user-images.githubusercontent.com/85207959/120728570-d691e900-c50f-11eb-9e69-709a36923b89.png)

still didn't work

**Comment by vivinano** [comment]
gotta pip3 to install for python3

**Comment by vivinano** [comment]
ah i see your also using windows store version of python

**Comment by byronsanity** [comment]
Actually I installed from python.org then when I tried running it it says python not installed so I tried windows store

**Comment by vivinano** [comment]
because windows store kind of just wants to replace itself on to python uh one sec gonna link a older issue there are steps to take there

**Comment by byronsanity** [comment]
Okay thanks

**Comment by vivinano** [comment]
it should be at the bottom there were similar issues but the one you want to do is what @condorsail wrote at the end

**Comment by vivinano** [comment]
just checking in. Its been a couple hours did the other issue fix this issue ?

**Comment by byronsanity** [comment]
Oh I forgot to reply. Anyway it didn't work. I also uninstalled python and tried reinstalling it again yet to no avail, did not work. Still trying to figure out.

**Comment by vivinano** [comment]
Did you try the import pip and pip install ? Should just install thru the correct environment but yeah Windows store sometimes causes multiple python instances and it could cause issues

**Comment by vivinano** [comment]
Try to get help over at 

https://github.com/Merubokkusu/Discord-S.C.U.M/issues or email them they should be able to walk you thru how to get their module

**Comment by byronsanity** [comment]
Closing this thread I managed it to work buy uninstalling everything. Install python first before discum.
