### ISSUE TITLE
Bot doesn't roll on its own

### ISSUE THREAD

**Issue by Aries298** [vivinano/MudaeAutoBot#52]
Hello, the bot works just fine. When I run it, it starts by rolling and after that it keeps sniping kakera, characters and notifying when other users roll. However, when certain time has passed and I'm able to roll again it doesn't fo it on its own and I have to restart the script. Also, not sure if that's intended but it rolls even though I'm not able to claim.

**Comment by vivinano** [comment]
it should roll just keep rolling but if its print 

![image](https://user-images.githubusercontent.com/33008397/120766138-ec8bb380-c4e7-11eb-8d4e-801a2bb3b96e.png)

True:Waifu_wait  then give it a few minute to finish rolling but it should always roll

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/120767685-67a19980-c4e9-11eb-9bc2-ecc613b13853.png)

so if it print that then your waifu wait has been set just give it time and it will roll

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/120783527-22856380-c4f9-11eb-8fc0-a5e2d20b4952.png)
![image](https://user-images.githubusercontent.com/33008397/120783591-2c0ecb80-c4f9-11eb-80cf-8c7ae10b6cfc.png)


seems to roll just fine

**Comment by Aries298** [comment]
Yeah, you are right. The bot doesn't roll as soon as it's able to claim but you need it to give it some time. Still not entirely sure if it keeps rolling even though I cannot claim but that wasn't the main issue so I'm closing.
