### ISSUE TITLE
No module named discum

### ISSUE THREAD

**Issue by ToxicLime** [vivinano/MudaeAutoBot#53]
I've basically been tearing my hair out for the past few hours trying to figure out how to get this to work, I've tried running the various commands posted in other closed issues to no avail, I've reinstalled python as well as used Git to install Discum. Any advice?
![563ed25566e29cfbe750e7ca9bf11435_LI](https://user-images.githubusercontent.com/83319004/120865611-5cd41c80-c55c-11eb-9ad5-52d1986968a2.jpg)

**Comment by vivinano** [comment]
so you have tried the commands on #48 
that seems to be more of the fix 
but it might be easier to get more help from discum dev himself 

https://github.com/Merubokkusu/Discord-S.C.U.M/issues

if the commands on the closed issue isnt working then go to the link provided and they can provide more help

**Comment by ToxicLime** [comment]
I tried doing these two commands in IDLE but it gave me an error

> import pip
> pip.main(['install','git+https://github.com/Merubokkusu/Discord-S.C.U.M.git'])

![image](https://user-images.githubusercontent.com/83319004/120870498-1506c280-c567-11eb-886e-770bdd2efe90.png)

**Comment by vivinano** [comment]
try to install a simple package like discord.py and then try the discum install agian

**Comment by ToxicLime** [comment]
I assume you meant install through Git bash, so I tried that. Didn't work. Still can't detect the discum module.

**Comment by vivinano** [comment]
have you tried replace the keyword pip with pip3 ?

**Comment by ToxicLime** [comment]
Let me try that

**Comment by ToxicLime** [comment]
Nope same error

**Comment by vivinano** [comment]
try #51 he seemed to get it working

**Comment by vivinano** [comment]
Well it’s more an issue with python installation process usually multiple instances where pip is installing the discum in the wrong place so I was 
Testing it on a new machine and I saw that 

When using python from the install location doing “import discum” worked but in idle doing import discum didn’t work so the issue that happening it that you do have the discum module but pip installed it in the wrong location 

Unfortunately I do not know where my idle version is going off of yet but if I find out I’ll let you know

**Comment by vivinano** [comment]
A small work around is you can use python within the cmd. 

you can traverse the file structure of your computer using `cd (folder name)` and `dir` and when you get into the folder with mudaeautobot.py

you can run the command

`python mudaeautobot.py` which should get it to run 

and you can figure out the separate instances issue later
