### ISSUE TITLE
time to claim

### ISSUE THREAD

**Issue by frannvg** [vivinano/MudaeAutoBot#54]
hi i have a question, can i put on the setting.txt a claim delay smaller than 1? like 0.3?

**Comment by vivinano** [comment]
so with the never version it does predective claim delay from $settings command unsure if this will effect snipe protections but you are free to try the worse it can do it error out

**Comment by frannvg** [comment]
So it doesn't matter what number I put in the settings?
Oh and another question, if I have more than 8 or 10 rolls, how do I tell the bot to do more?

**Comment by vivinano** [comment]
it should now roll until you run into 2 rolls left and it rolls until the end

and the setting apply to the default settings
