### ISSUE TITLE
Bot does not start error

### ISSUE THREAD

**Issue by frannvg** [vivinano/MudaeAutoBot#55]
this error happens when i start the bot
![Screenshot_2](https://user-images.githubusercontent.com/84478031/120881570-6d11e900-c5a8-11eb-8dbb-11d2fff13054.png)

**Comment by vivinano** [comment]
https://github.com/Merubokkusu/Discord-S.C.U.M/commit/d8e810adc536fe7ed5641e386fb85d03fbe35270

discum made changes please download latest version of discum
