### ISSUE TITLE
What is supposed to happen when I open the bot?

### ISSUE THREAD

**Issue by verge111** [vivinano/MudaeAutoBot#56]
I configured all settings, installed the latest version of python and discum and when I open up "MudaeAutoBot.py" there's a black cmd window for a second then it goes away, is that supposed to happen?

**Comment by vivinano** [comment]
No I recommend opening it thru IDLE  1st and seeing what errors popped up

**Comment by vivinano** [comment]
checking in as i havent heard back ?
