### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#58]
Hi,

Thank you very much for the bot and for all the support you have given me, especially putting up with me, I really appreciate your work, after having fixed my problem to run the latest version, it is working fine, but if you allow me, I would like to make some suggestions for features that could be added to the bot in the future:

1 - Show channel name and server name, currently shows the Server_id.
2 - Possibility of deactivating Kakera free claim.
3 - See if it is possible to improve the bot's snipe speed, even putting it as fast as possible, it loses to everyone, being viable ONLY against very slow people or simply to run on its own server alone.
4 - Possibility of using the $daily command automatically
5 - Possibility of receiving any notification or audible warning when there is a claim, either kakera or waifu, choosing notification from the 2 or only one.
6- React to a specific kakera of a defined embedcolor
7 - Rolling more agile, currently occurs when the bot runs slowly d+ and when it runs, it sometimes plays 2 commands together and changes only one, this occurs repeatedly and easily fills a pattern. as the screenshot below

![image](https://user-images.githubusercontent.com/82736191/121825485-10d65580-cc89-11eb-8fe5-181a3431d971.png)

**Comment by vivinano** [comment]
1. Read Discum Docs as its not the same as Discord.py only works with ID strings and don't see a way to print name from ID
2. To be determined 
3. Total time is takes varies on many factors ( Bot Calculation time , Discord API interaction [Internet speed], Mudae reaction time ) I have control of the 1st one
4. Starting another thread to only run once every 20 hours seems unnecessary , might also conflict with others ppl rolling or self rolling
5. Outside the scope of the project being that I'm only using (Discum [Discord Api interaction] , Python Standard Library)
6. to be determine if enough demand (Was Extra Checks slowing runtime for non-end game users)
7. Non-Issue Will; not fix as I can create that without using a bot   
![image](https://user-images.githubusercontent.com/33008397/121830533-3e280100-cc93-11eb-8b8d-40b2d44ce246.png)
( Because Ctrl - V to paste is a human action there is no pattern mudae is being slow this Non-issue will not Fix)


will leave open for answer on the 1st suggestion but most suggestions fall outside scope of project

**Comment by BellaDona007** [comment]
2 - How do I disable claim freekakera?
7 - The bot always rolls like this:
![image](https://user-images.githubusercontent.com/82736191/121833175-24da8100-cca2-11eb-8d7a-dd196f925fc1.png)

Before solving the problem that it ignored the last 2 rolls, it ran relatively fast, looking like a person using ctrl -v

**Comment by vivinano** [comment]
7- this issue is only applying to you cause my test shows consistent rolls no matter what even on limited internet 
![image](https://user-images.githubusercontent.com/33008397/121838398-be576200-cca5-11eb-8357-9dc281e9446b.png)

**Comment by BellaDona007** [comment]
> 7- this issue is only applying to you cause my test shows consistent rolls no matter what even on limited internet
> ![image](https://user-images.githubusercontent.com/33008397/121838398-be576200-cca5-11eb-8357-9dc281e9446b.png)

It stays that way throughout the roll?

**Comment by vivinano** [comment]
yup i scrolled up and down for like a 24 hour interval and it was consistent

**Comment by BellaDona007** [comment]
I have no idea why this occurs, it is always in this interval and it runs extremely slow, even mobile is that slow.
My internet is not so bad, I have 300mb download and 50mb upload

**Comment by vivinano** [comment]
many factors could also be code execution time on your computer so the faster connection you have and the faster process power could all factor into things

**Comment by BellaDona007** [comment]
> many factors could also be code execution time on your computer so the faster connection you have and the faster process power could all factor into things

So how can I increase or decrease the roll speed?

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/122123875-8e6ea280-cdfc-11eb-9c1d-8e9f8566f72e.png)

basically this function but honestly i think that is based on speed of your connection to the discord API cause there isnt a sleep command in here

**Comment by BellaDona007** [comment]
So I don't know why it's so slow, people are complaining that I take d+, so I've kept `"rolling":"False"`
takes more than 2 minutes to roll 50x

**Comment by vivinano** [comment]
and you said earlier version of the bot rolled faster ?

**Comment by BellaDona007** [comment]
Yes, in the version that was missing 2 rolls, it was running perfectly, it looked like a person rolling

**Comment by vivinano** [comment]
you could go thru the versions history of this repo and just replace the waifu roll function of the current one with a previous one and try that out as im not having issues with rolling so far

**Comment by BellaDona007** [comment]
This is the speed of rolls


https://user-images.githubusercontent.com/82736191/122629934-c133c780-d096-11eb-96e7-5263325b7ef4.mp4

**Comment by vivinano** [comment]
yeah this is something on your end as looking at that clip its took 3 mins to roll 10 while mine takes only at most 1 min 

1st roll
![image](https://user-images.githubusercontent.com/33008397/122996968-81602f00-d379-11eb-9001-b65d00b111d1.png)

2 rolls remaining roll
![image](https://user-images.githubusercontent.com/33008397/122997031-9341d200-d379-11eb-8d15-155b23314496.png)

Last roll
![image](https://user-images.githubusercontent.com/33008397/122997105-a5bc0b80-d379-11eb-88b2-10516078fff8.png)

its either your connection speed or maybe with the discum module but I'm not experiencing an issue on my end

**Comment by BellaDona007** [comment]
I have another machine without python and discum installed, I will test it, installing it and see if the problem persists
