### ISSUE TITLE
Confused about how the bot is supposed to look in active state.

### ISSUE THREAD

**Issue by Sourin99** [vivinano/MudaeAutoBot#59]
The bot is up and running. It writes "Retrieving Discord's build number" then goes on to process some stuff and then writes "entering heartbeat".  Following which it keeps on writing stuff continuously. Is it how it is supposed to be ?
I tried enabling auto rolls by setting it as True in the JSON file but that doesn't seem to help. No auto rolls happen even after 30-ish minutes of keeping it running.

I apologize if the question seems stupid, but I am not sure how the active and working bot is supposed to look like.

**Comment by vivinano** [comment]
seems like you are running an old version of Discum as all that stuff is set to false 

so it should only post things like pokerolling: or waifurolling:

**Comment by Sourin99** [comment]
I went through the archived issues earlier and saw you asking someone to update Discum. So I went ahead and looked into it's docs. I uninstalled discum via pip and reinstalled it freshly via "pip install discum -U" as mentioned in the doc. 

![1](https://user-images.githubusercontent.com/56649012/121936810-a3e5bd00-cd67-11eb-9edd-c4e74ddaa9fa.PNG)

This is the message I get if I go ahead and do pip install discum. I believe I am using that latest version of discum which is 1.1.0

**Comment by Sourin99** [comment]
Also, the kakera snipe isn't working properly or is slow. I just lost 2 kake snipes, even though there are in the emoji list and I could react to it.

**Comment by vivinano** [comment]
no latest version of discum is 1.3 which is also the minimum requirement for the functions to get accurate snipe times other wise it using 8 secs so the snipes being 2 slow still is branching off the issue that you are using the incorrect version of discum as it cannot get correct settings parse to get the correct snipe time

**Comment by Sourin99** [comment]
Thank you for answering and I am sorry that it's related to an environment/setting up problem. Since uninstalling and reinstalling didn't help, can you please provide a guide as to how to go about installing discum 1.3 ? Thank you.

**Comment by vivinano** [comment]
its fine to ask questions but I spent several long conversations talking around in circles on how to install a dependency library which in term stopped me from working on actually bot issues 

https://github.com/Merubokkusu/Discord-S.C.U.M

there is the github page for Di.s.c.u.m they can provide you more help in terms of installing their library their pip install from pypi is outdated so installing thru github is the recommended way

**Comment by Sourin99** [comment]
The discum docs said to use git clone and clone the repo and go on to install it from there. I also tried it via this method but the same thing happens. 

Anyways thanks for the help. I'll try uninstalling discum and doing a fresh install via the repo readme help.

**Comment by vivinano** [comment]
If you can’t do it you can either message the email provided or create an issue on their page and would provide you with greater help than I can with that

**Comment by Sourin99** [comment]
I was able to install Discum1.3. However, I am still facing some issues. 

![3](https://user-images.githubusercontent.com/56649012/121991913-344eec80-cdbe-11eb-94d0-485f418853e4.PNG)
This shows that the installed version is 1.3

![2](https://user-images.githubusercontent.com/56649012/121991939-416bdb80-cdbe-11eb-8899-18c9cbe08447.PNG)
I am getting this error now.

**Comment by vivinano** [comment]
send the (channelid).txt file so i can see what was saved as settings that it is unable to parse

**Comment by Sourin99** [comment]
It's generating an empty (channelid).txt file.

**Comment by Sourin99** [comment]
Okay, so I went ahead and created a new account and tested it with that. It worked. My original account is rather old, so can that be reason why it isn't working ?

**Comment by vivinano** [comment]
delete that and have it pool a different .txt file as its trying to look for a $settings instance

**Comment by Sourin99** [comment]
![1](https://user-images.githubusercontent.com/56649012/122000569-aa5a5000-cdcc-11eb-902c-6786b444c657.PNG)

Deleted the (channelid).txt file. And retried. New error this time...

**Comment by Sourin99** [comment]
`UnicodeEncodeError: 'charmap' codec can't encode characters in position 29-31: character maps to <undefined>
2021-06-15 11:30:00,220:Could not find settings for 843011498468966451, please trigger the '$settings' command in the server and run the bot again.` 

This is what I get each time I roll or use any other comman.

**Comment by vivinano** [comment]
can i see the $setting command ? is it using a different emoji char ?

**Comment by Sourin99** [comment]
![1](https://user-images.githubusercontent.com/56649012/122004486-18eddc80-cdd2-11eb-8862-6e9322cea67b.PNG)

**Comment by vivinano** [comment]
hmm nice i didnt account for server premium
alright ill account for that also one second

**Comment by vivinano** [comment]
alright redownload the the bot and it should work

**Comment by Sourin99** [comment]
Okay Thanks. Will try it out.

**Comment by Sourin99** [comment]
It's working. I am closing this for now. Will open a new one if any other issues pop up. Thank you for you work and bearing with me.
