### ISSUE TITLE
How to $wa in multiple channel

### ISSUE THREAD

**Issue by PixelGM** [vivinano/MudaeAutoBot#6]
I've seen the source code, "channel_id" is channel where we do $wa, but "multichannel" only claims for us (not do $wa), so how do we $wa automatically on multiple channel?

**Comment by vivinano** [comment]
It should be the same setting 
it turns off rolling normal code and instead creates X coroutines with different channel id's

so just set multirolling to True and type in the all the channel-ids in multiid and it should roll $wa in multiple servers

**Comment by PixelGM** [comment]
So, set "Multirollenable" to true. Thank you for your assistance!

**Comment by vivinano** [comment]
Please know that you also have to set rolling to false

**Comment by PixelGM** [comment]
i can see it here
`if settings["rolling"] != "True" and settings["Multirollenable"] == "True":
            await asyncio.sleep(8)
            for multichannel in multiids:
                self.loop.create_task(self.bg_task(multichannel))
                await asyncio.sleep(30)`
