### ISSUE TITLE
Bot doesn't seem to detect if a character is wished by someone else

### ISSUE THREAD

**Issue by DaMagicFox** [vivinano/MudaeAutoBot#60]
So I had a character in my character list, but the character was wished by someone else, and the bot didn't wait the time specified in the togglesnipe setting, in fact, it tried to instasnipe. Shouldn't it have detected that the character was wished by someone else and since i have the togglesnipe setting in my server, it should've known how much to wait?

**Comment by vivinano** [comment]
send settings for that channel ? and the text doc

**Comment by DaMagicFox** [comment]
> send settings for that channel ? and the text doc

![image](https://user-images.githubusercontent.com/67620778/122056717-80466500-cdaf-11eb-9804-8aaa329b13ec.png)
[824430937211142144.txt](https://github.com/vivinano/MudaeAutoBot/files/6655709/824430937211142144.txt)

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/122070865-4df33280-cdc4-11eb-8379-5100041a4366.png)

so right here is the function for that basically determines snipe time 

so how the logic there works is if it finds your user id on the character then it will insta snipe 

did you also wish the character ?

**Comment by DaMagicFox** [comment]
> did you also wish the character ?

No I didn't wish for it, it was on my char list. I thought the bot had a way to detect if there is someone else's wish and how much to wait if it is.

**Comment by vivinano** [comment]
it only detects if your name is in there and if not wait normal unless something else procced and you instant sniped

**Comment by DaMagicFox** [comment]
> it only detects if your name is in there and if not wait normal unless something else procced and you instant sniped

Oh, so that means that there isn't a bypass for togglesnipe?

**Comment by vivinano** [comment]
as you see in the above image if it return 0.0 that means instant snipe if its return d is mean return delay so based on that logic it should not have attempted to instant snipe

**Comment by vivinano** [comment]
did the issue happen again ?

**Comment by DaMagicFox** [comment]
> did the issue happen again ?

I've been trying to see if it happens again... but there hasn't been a chance to replicate yet.

**Comment by vivinano** [comment]
alright let me know when or if this happens again the logs should be time stamped if it tries to roll and instant snipes so just screenshot the log and i will figure it out from there

**Comment by vivinano** [comment]
going to close this issue as there hasn't been any other users who had this issue. 

any chance computer went on sleep mode ? and caused some issues anyway if there is another instance of this issue occurring feel free to reopen or making a new issue
