### ISSUE TITLE
Whenever run I get this

### ISSUE THREAD

**Issue by anger** [vivinano/MudaeAutoBot#61]
https://i.imgur.com/Ge8nz8m.png

**Comment by vivinano** [comment]
incorrect version of discum you are running 1.1 
while 1.3+ is the latest discum version

**Comment by anger** [comment]
> 
> 
> incorrect version of discum you are running 1.1
> while 1.3+ is the latest discum version

https://i.imgur.com/slbMLxN.png what about this one?

**Comment by vivinano** [comment]
it was unable to find a settings so it used default

**Comment by vivinano** [comment]
havent heard back will be closing
