### ISSUE TITLE
The bot stops logging after a prolonged period of inactivity.

### ISSUE THREAD

**Issue by Sourin99** [vivinano/MudaeAutoBot#62]
The bot stops logging, after a period of time. I usually keep it running 24 x 7. However, during the night, if no one rolls for a certain period, the bot stops logging. The command prompt still remains active, however, the bot doesn't log self or other user rolls.

This has happened for the past 2 days. The bot stopped logging anything and therefore it couldn't do a couple of waifu snipes and kake snipes.

**Comment by vivinano** [comment]
I think I’ve experience this also I’m gonna be talking to the dev of discum as this retain to the discord api gateway I think . Cause what going on is that the discord api is no longer serving back messages to run the code on 

So if you can turn the discum logging to true and take some screenshots of if the bot closes its web socket cause I think it’s the web socket not keeping alive

**Comment by Sourin99** [comment]
Yeah, I think so too. The first day, we got a server reset, the bot worked throughout 24 hours, because it was active and people kept rolling. As the crazy slightly reduced, the last two days, the bot automatically turned off after some period of inactivity (no rolling).

I'll try turning on discord logging and running it again and post screenshots.

**Comment by Sourin99** [comment]
Also, I have got some problems with the sniping. I am running it on a server which has Instasnipe, i.e. Togglesnipe at 0. I have set the claim delay for both kake and waifu at 0.5. The bot does react to the waifu/kake rolled, but in some cases it's delayed, which means the character ends up getting claimed by someone else. It's kinda a hit or miss with around 50-60% accuracy. I have successfully sniped a few characters and also have failed to do so for almost the same number of them. 

I went through the source code and apparently there's a thread.sleep of 0.5 seconds in the snipe function. Does it mean, the bot automatically considers a delay of extra 0.5 seconds? So for claim delay of 0.5s in the json, does it mean the actual claim delay is 0.5 + 0. 5 = 1s ?

**Comment by Sourin99** [comment]
So, it seems it's actually taking around 1second to snipe the character.

![1](https://user-images.githubusercontent.com/56649012/122643701-fc81d500-d12e-11eb-8213-bdb075ead2fb.PNG)

**Comment by vivinano** [comment]
In terms of instant snipe there is always a .5 sec delay because I tested without it and it would react to fast sometimes based on Internet connection so mudae doesn’t register it 

The rest of the time is based on connection to the discord api as it sends the command and discord api has it from there (internet speed)

I would like to know if this is a separate issue and if leaving it on has issues over prolonged periods of time still has problems ?

**Comment by vivinano** [comment]
Nvm I saw the rest of the message I apologize replying from mobile

**Comment by Sourin99** [comment]
> 
> In terms of instant snipe there is always a .5 sec delay because I tested without it and it would react to fast sometimes based on Internet connection so mudae doesn’t register it The rest of the time is based on connection to the discord api as it sends the command and discord api has it from there (internet speed) I would like to know if this is a separate issue and if leaving it on has issues over prolonged periods of time still has problems ?
> […](#)
> Sent from my iPhone
> On Jun 19, 2021, at 9:19 AM, Sourin Roy ***@***.***> wrote: ﻿ So, it seems it's actually taking around 1second to snipe the character. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Regarding the issue about prolonged period, I'll try running it throughout the night and let you know. As for the 0.5 second delay, is it possible to bring it down by editing the value in the thread.sleep ? Or can we set the claim delay value in the JSON as 0?

**Comment by vivinano** [comment]
The json use to set the delay but now it only sets if default setting instance is used 

In the .py that u run there should be a 

Def snipe 

And at the bottom is a time.sleep(.5) that can be removed or edited based on needs if removed there is still some time that needs to be factored in IE internet connection so that factors into time needed to snipe still

**Comment by vivinano** [comment]
on github code line count it should be on `line 366`

if you want to mess with that "time.sleep value only" like i said b4 removing it or tweakin it 

ill let the discum dev know about times of inactivity and see what he says about it

**Comment by Sourin99** [comment]
> 
> The json use to set the delay but now it only sets if default setting instance is used In the .py that u run there should be a Def snipe And at the bottom is a time.sleep(.5) that can be removed or edited based on needs if removed there is still some time that needs to be factored in IE internet connection so that factors into time needed to snipe still
> […](#)
> Sent from my iPhone
> On Jun 19, 2021, at 10:41 AM, Sourin Roy ***@***.***> wrote: ﻿ In terms of instant snipe there is always a .5 sec delay because I tested without it and it would react to fast sometimes based on Internet connection so mudae doesn’t register it The rest of the time is based on connection to the discord api as it sends the command and discord api has it from there (internet speed) I would like to know if this is a separate issue and if leaving it on has issues over prolonged periods of time still has problems ? … Sent from my iPhone On Jun 19, 2021, at 9:19 AM, Sourin Roy @.***> wrote: ﻿ So, it seems it's actually taking around 1second to snipe the character. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Regarding the issue about prolonged period, I'll try running it throughout the night and let you know. As for the 0.5 second delay, is it possible to bring it down by editing the value in the thread.sleep ? Or can we set the claim delay value in the JSON as 0? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

What do you mean by default setting instance ? And does the time in thread.sleep() and claim delay in JSON file get summed (ignoring the connection time to the API and so on) ?

**Comment by vivinano** [comment]
If the bot doesn’t find a file , or a searched instance in discord , then it will have a default $setting is uses for cases like running it on a new server you can see it within the code there is like a multi line block of text string weirdly in the code

**Comment by vivinano** [comment]
has it stopped working during the time ?

**Comment by Sourin99** [comment]
There's been a power outrage here for the last couple days, so I haven't been able to keep it running throughout the night. I did keep it running last night, but there weren't any issues as such. I'll confirm about the issue, after doing another test on it. Sorry for the delay.


Apart from that, there's another issue, although it's not really an issue as per se. When the bot runs, it sometimes generates a message and stops working for a few seconds to one minute. It automatically restarts back and start working normally.
The log message is - 
```
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000002E7A003BC40>>
Traceback (most recent call last):
  File "C:\Users\GhostPC\AppData\Roaming\Python\Python38\site-packages\discum\gateway\gateway.py", line 288, in _response_loop
    func(resp)
  File "MudaeAutoBot.py", line 534, in on_message
    embeds = r['embeds']
KeyError: 'embeds'
```

**Comment by Sourin99** [comment]
Example of how it actually looks while running - 

```
Someone else rolled in 843011498468966451 at 2021-06-22 05:05:24.936042
Someone else rolled in 843011498468966451 at 2021-06-22 05:05:27.622653
Someone else rolled in 843011498468966451 at 2021-06-22 05:05:28.421522
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000002E7A003BC40>>
Traceback (most recent call last):
  File "C:\Users\GhostPC\AppData\Roaming\Python\Python38\site-packages\discum\gateway\gateway.py", line 288, in _response_loop
    func(resp)
  File "MudaeAutoBot.py", line 534, in on_message
    embeds = r['embeds']
KeyError: 'embeds'
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000002E7A003BC40>>
Traceback (most recent call last):
  File "C:\Users\GhostPC\AppData\Roaming\Python\Python38\site-packages\discum\gateway\gateway.py", line 288, in _response_loop
    func(resp)
  File "MudaeAutoBot.py", line 534, in on_message
    embeds = r['embeds']
KeyError: 'embeds'
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000002E7A003BC40>>
Traceback (most recent call last):
  File "C:\Users\GhostPC\AppData\Roaming\Python\Python38\site-packages\discum\gateway\gateway.py", line 288, in _response_loop
    func(resp)
  File "MudaeAutoBot.py", line 534, in on_message
    embeds = r['embeds']
KeyError: 'embeds'
Someone else rolled in 843011498468966451 at 2021-06-22 06:44:42.094472
Someone else rolled in 843011498468966451 at 2021-06-22 06:44:44.306442
Someone else rolled in 843011498468966451 at 2021-06-22 06:44:49.562690
```

I have edited the default messages with a timestamp, so that's why the output is like this.

**Comment by vivinano** [comment]
I tried to account for any embeds mudae might provide ? Like I know vote commands gave me issues originally is there specific 

Basically mudae provide a embed that is unable to be parsed into useable data so if you can send me a picture of the thing that mudae have issues with I can implement a fix maybe

**Comment by Sourin99** [comment]
What are embeds specifically ? I can try finding one.

**Comment by Sourin99** [comment]
![1](https://user-images.githubusercontent.com/56649012/122864260-ebf57880-d341-11eb-8006-b929fce72a60.jpg)

There wasn't any messages sent between 05:05 and 06:44.

**Comment by vivinano** [comment]
basically an embed is anything in the box with the color tab on the side

**Comment by Sourin99** [comment]
Okay. But as you can see there's no messages sent between the two time stamps.

**Comment by vivinano** [comment]
okay based on the error message it something from mudae that has an embed that isnt able to be parsed out

**Comment by Sourin99** [comment]
The origin discum issue is probably in the fact that my laptop goes into Sleep after a certain time.
As for the embed issue, I haven't been able to find anything, because it occurs randomly at times even when no one is rolling or doing anything in the channel. It also sometimes occurs during the start of the program.

**Comment by vivinano** [comment]
yeah if ur laptop goes to sleep than usually you no longer have internet so that would be a correct assessment 

alright well as long as the embed issue doesnt interfere with normal operation then it should be fine
