### ISSUE TITLE
SyntaxError: Non-ASCII character '\xf0

### ISSUE THREAD

**Issue by Lucas-topper** [vivinano/MudaeAutoBot#67]
whenever I turn on the bot this error could help me?

**Comment by vivinano** [comment]
send your $settings if it's premium there issues transcribing but send me the picture of the error so I can determine where in the code it is crashing

**Comment by Lucas-topper** [comment]
could you send me your discord? over there it's better to talk about it.

**Comment by vivinano** [comment]
Currently only have my personal discord set up and I don't really check on it much so I would respond quicker here

**Comment by Lucas-topper** [comment]
![IMG_20210627_201253](https://user-images.githubusercontent.com/65551118/123562279-19985280-d784-11eb-8bba-cbe1346f5836.jpg)
oh ok this is the error

**Comment by vivinano** [comment]
made some changes which should force the interpreter to read it in unicode instead of asc-II so redownload the repo and try again

**Comment by Lucas-topper** [comment]
I just cloned the repository and changed the config.json, that was the only change I made to the code.

**Comment by vivinano** [comment]
Same error ? And are you using Windows or Linux ?

**Comment by Lucas-topper** [comment]
i'm trying on the glitch site to host the selfbot, they use the Debian system (The Linux distro)

**Comment by vivinano** [comment]
Ah yes so there a thing that won't write to file because it's code for windows 

I was gonna implement the change to support Linux 

Basically 

Channaldata/file Is windows

Channeldata\file is Linux

**Comment by Lucas-topper** [comment]
also forgot to mention, i tried running the code on my linux and the error is the same.

**Comment by vivinano** [comment]
Yeah basically currently implementation is write for a windows file structure didn't write it for Linux since no one asked but I can quickly implement a fix but it's still giving the same asc II error ? Or is it a different error

**Comment by vivinano** [comment]
Added support for linux Filesystems now try to reclone and run it now and tell me if there are errors

**Comment by vivinano** [comment]
@Lucas-topper just checking in to make sure you tried to run it ?

**Comment by Lucas-topper** [comment]
I saw this message now, I'm going to clone the repository again and test it. and yes I ran it several times and the error was always the same.

**Comment by Lucas-topper** [comment]
now gave this error: (I think it's just a configuration error not a problem with the system)
![IMG_20210628_174541](https://user-images.githubusercontent.com/65551118/123701894-d21fce00-d838-11eb-800c-5bbe62acb56e.jpg)

**Comment by vivinano** [comment]
well this error is a python error I think you are using a older version of python and the 

`F` is a format string and older versions of python doesnt support that so what python version are u running ?  the minimum requirments are `python 3.6+`

**Comment by Lucas-topper** [comment]
i upgraded to python 3.6 and gave this error
![IMG_20210628_191016](https://user-images.githubusercontent.com/65551118/123710119-8d9a2f80-d844-11eb-8f8c-58f9959ff0f7.jpg)

**Comment by vivinano** [comment]
On the read me there should be a site paste you setting_json into the textbox and it should validate your json

**Comment by vivinano** [comment]
Issue still persist ?

**Comment by Lucas-topper** [comment]
now I managed to run without any error, however the selfbot that is my secondary account does not go online and also does not Rolling / claim.

**Comment by Lucas-topper** [comment]
yes the problem continues even after validating the json.

**Comment by vivinano** [comment]
and the settings.json is in the same folder as the bot ?

**Comment by vivinano** [comment]
is it the same json load error ?

**Comment by Lucas-topper** [comment]
yes, the settings are in the same folder as the main code file and the error is the same.
![IMG_20210629_081412](https://user-images.githubusercontent.com/65551118/123788254-2ca94080-d8b2-11eb-8a6f-600cc90e1247.jpg)
![IMG_20210629_081434](https://user-images.githubusercontent.com/65551118/123788267-2fa43100-d8b2-11eb-9178-816da68d7c94.jpg)

**Comment by vivinano** [comment]
Can you post your Json file and let me see if there any issues 
Keep in mind to blur out ur user token B4 posting

**Comment by Lucas-topper** [comment]
{
   "token":"o",
   "channel_ids":[
      854166713704644629,
      854166713704644629,
      854166713704644629
   ],
   "claim_delay":3,
   "kak_delay":4,
   "use_emoji":"<:gadani:750702893212106843>",
   "roll_this":"wa",
   "rolling":"True",
   "pkmrolling":"false",
   "series_list":[
      "Jujutsu Kaisen",
      "Hunter × Hunter"
   ],
   "namelist":[
      "killua Zoldyck"
   ],
   "emoji_list":[
      "kakera",
      "kakeraT",
      "kakeraG",
      "kakeraY",
      "kakeraO",
      "kakeraR",
      "kakeraW",
      "kakeraL"
   ],
   "soulemoji_list":[
      "kakeraO",
      "kakeraR",
      "KakeraW",
      "KakeraL"
   ],
   "min_kak":500,
   "Last_True":"True",
   "last_claim_min":10,
   "min_kak_last_min":30
}"min"": 10,
   ""min_kak_last_min""\": 30
}"}

 este é o meu json depois de validado

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/123831245-21fea380-d8d2-11eb-87c2-f4a5c9b7e04b.png)

it is saying its invalid ??

did it say it was valid for you ?

**Comment by vivinano** [comment]
so unless this is a copy paste error that is your problem. just fix the errors in your json file

**Comment by Lucas-topper** [comment]
yes, it said it was valid when I put it there

**Comment by vivinano** [comment]
Well I copy and pasted the one you posted and it’s saying it’s invalid  

Just remove the ones in red and you should be fine

**Comment by Lucas-topper** [comment]
I fixed errors in json and started without any error But the terminal is flooding profile information and does not send messages in chat

**Comment by Lucas-topper** [comment]
![IMG_20210629_174324](https://user-images.githubusercontent.com/65551118/123864821-913fbc00-d901-11eb-9191-65922b0a530f.jpg)
esse tipo de coisa

**Comment by vivinano** [comment]
You are using an older version of discum you are running version 1.1 


The bot needs discum 1.3+

**Comment by vivinano** [comment]
since this is falling down the path of being a python enviroment issue or a Discum specific issue. I will be closing this issue soon as stated in my readme I'm no longer gonna offer support for discum issues as there is a whole other dev team that handles that.

If there is anymore questions about the bot itself feel free to ask as if not I will be closing this issue in a couple of hours

**Comment by Lucas-topper** [comment]
![IMG_20210629_213856](https://user-images.githubusercontent.com/65551118/123884793-73368380-d922-11eb-8f28-dfb6f0e36d6e.jpg)

**Comment by vivinano** [comment]
https://github.com/Merubokkusu/Discord-S.C.U.M 

please refer to the discum repo

**Comment by vivinano** [comment]
alright since this issue has been moved over into discum territory I will be closing this issue if there is an issue that is not related to discum I'll glady answer when this issue is reopened

**Comment by vivinano** [comment]
I know i closed this issue but was making sure you were able to read the reply from discum as i see the issue has been answered and you have no replied to them yet
![image](https://user-images.githubusercontent.com/33008397/124394011-5f48a400-dccb-11eb-8357-16b667e873f4.png)

**Comment by Lucas-topper** [comment]
I know this issue was closed but I'll send it right here, after I managed to install discum 1.3 it gave this error when running (this is on my computer and not on vps) File `/MudaeAutoBot/MudaeAutoBot.py", line 653, in on_message
    for matched_channel in (set(guild['channels'].keys()) & chs):
KeyError: 'channels'`

**Comment by vivinano** [comment]
basically the program is design in a way that if $settings is not found either 
by file , via search , or via the default settings then it get removed from the list hence then it is an "empty"

**Comment by Lucas-topper** [comment]
worked, thank you

**Comment by Lucas-topper** [comment]
Hi, it's been a while since I've been around here, I was wondering if there's a way I can create a file with my wishes because my wish list is over 500 characters and it's going to take a lot of work to put in config.json (I'm doing this for my friend, don't think I'm addicted to the point of wanting 500 wishes)
