### ISSUE TITLE
authorID GatewayServer Error

### ISSUE THREAD

**Issue by munchipo** [vivinano/MudaeAutoBot#68]
Hey, 

Thanks for the bot by the way! I just want to make sure you know that I appreciate your work before I start asking questions (sorry in advance). 

After configuring the settings to how I liked, I tried running MudaeAutoBot.py in a command prompt. It seemed that I was getting connection errors leading to an infinite loop of reloading and trying again. I ran the code in IDLE and I am frequently seeing this error:

![image](https://user-images.githubusercontent.com/86893969/124391724-f60f6380-dcbf-11eb-97a0-ce073f113661.png)

I have the most recent version of DISCUM downloaded, and successfully installed it using pip. I have not touched any of the files from DISCUM. 

If you have any advice or help, that would be highly appreciated! :)

**Comment by vivinano** [comment]
hello if you installed using pip then most likey you got discum version 1.1

discum version 1.3 converted userID to authorID which would cause that issue

I appreciate the thanks tho 😄 

but for more info on how to install 1.3 discum let me link you to their repo and you can ask them 
https://github.com/Merubokkusu/Discord-S.C.U.M 

keep in mind the usually reply by editing your comment so keep and eye on it if you do make an issue over there

ill keep this issue open until you let me know the status

**Comment by munchipo** [comment]
Ah thank you so much, I was not expecting a quick response! 

Installing using the git command seemed to do the trick, I didn't even realize the pip installation was a different version. 

And your repo is stared! It's a great bot from what I've seen :)

**Comment by vivinano** [comment]
Thanks you. me and a friend have put a lot of work in to it

It started off as a simple bot but now it's has alot of predictive features. If you run in the any problems just let me know and I'll be sure to patch it if it's within my power if not I'll try to direct you to someone who does

**Comment by munchipo** [comment]
The only issue I've noticed so far is that it stops with 1 roll left. It doesn't bother me, but I wonder if that is a settings thing or a software bug.

**Comment by vivinano** [comment]
Yeah I'm not sure why the fix was implemented just in case the server crashes to prevent from trying to spam the server constantly making it look like a bot since there is no response from mudae or etc 

At a point I just accepted that it gonna be one short might be just a number I have to adjust but I'll check it out 

But if you think you can fix it anything that deals with rolling is within the

Def waifu_roll 

So if you think it bugs you and you find a consistent way you can make changes there

**Comment by munchipo** [comment]
I'll look at, but python and I hate each other. If I touch the code too much my PC will explode lol. Thanks though :)

**Comment by vivinano** [comment]
I assume this issue has been resolved ^^ and I shall be closing this one up
