### ISSUE TITLE
Hey I have this issue whenever I try to run the script

### ISSUE THREAD

**Issue by pentuhhh** [vivinano/MudaeAutoBot#69]
![rqwer](https://user-images.githubusercontent.com/77160847/124501537-53a4cc80-ddf4-11eb-9cc9-afea7c29e76f.png)
 
so ive been spending the past hour of the night trying to figure out what i am doing wrong or what i need to do. it just repeats over and over. I am really tired and i dont know what to do. Pls help. (i might take a while to respond thats because i might be out cold)

**Comment by vivinano** [comment]
your technically doing everything right it is just discum log data but in my script has it set to false

so if you installed Discum thru pip then you get the version 1.1

you need version 1.3+ for it to run correctly in the long run 

The please go to the link below as they will guide you to installing the latest version if discum:
 https://github.com/Merubokkusu/Discord-S.C.U.M

**Comment by vivinano** [comment]
just checking in ? on the status of the issue

**Comment by pentuhhh** [comment]
hi yes i am currently installing discum 1.3

**Comment by pentuhhh** [comment]
so update: im using this to install but it gives me this error

python -m pip install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git

ERROR: Error [WinError 2] The system cannot find the file specified while executing command
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by vivinano** [comment]
So you don't have "git" installed on your computer is why your getting this error

**Comment by vivinano** [comment]
Still having git installation issues ? checking in haven't heard a reply in 24 hours

**Comment by pentuhhh** [comment]
Yea im all set ty

Sent from Yahoo Mail on Android 
 
  On Thu, 8 Jul 2021 at 1:10 PM, Richard ***@***.***> wrote:   


Still having git installation issues ? checking in haven't heard a reply in 24 hours

**Comment by vivinano** [comment]
alright thanks for letting me know I will be closing the issue now
