### ISSUE TITLE
Disable claiming in specific servers.

### ISSUE THREAD

**Issue by DaMagicFox** [vivinano/MudaeAutoBot#7]
I think this should be a feature, maybe the channels you choose can be made the only places you want to claim.

**Comment by vivinano** [comment]
> ![image](https://user-images.githubusercontent.com/33008397/116124105-db9e8580-a691-11eb-8d53-ac5f6421b420.png)

change `if message.author.id == mudae:` >>> `if message.author.id == mudae and message.channel.id in [111111,22222]:`

> ![image](https://user-images.githubusercontent.com/33008397/116124131-e527ed80-a691-11eb-9f6c-d07ecd8f841f.png)`

change `if user.id == mudae:` >>> `if user.id == mudae and reaction.message.channel.id in [111111,222222]:`

or change `[11111,22222]` to in `multiids` and use that variable 
those changes should get you what you want. Personally I don't see the need to add this as it just limits the bot function and adds more checks the more it scales.

**Comment by DaMagicFox** [comment]
Fair enough. Thanks for the quick support btw, I gladly appreciate that.

**Comment by DaMagicFox** [comment]
2 (and a few extra)more questions.

1. Is it possible for the bot to always react with the same reaction as mudae? (Making it look less fishy)

2. My server has the togglesnipe feature on, so i put the timer for claim to 4.5 (0.5 secs after the protect snipe wears off). Does that work? 
2.a Is it possible for the bot to know when togglesnipe is not affecting the roll and setup another timer for when there is no togglesnipe involved? (In my case, you wouldn't care about togglesnipe when it is a character you have on your wishlist or is in nobody's wishlist.)

**Comment by vivinano** [comment]
1. It is possible but since mudae doesnt always have reaction to claim ? (This is a Mudae premium feature) it is hard to account for and I can't assume that every1 plays on a premium server 

**Note** about emoji's or emoji usage  

> ![image](https://user-images.githubusercontent.com/33008397/116167139-9f891600-a6cd-11eb-95e7-a83166634861.png)

this here will allow you to use a **custom emoji** if u uncomment out the line and comment out the ❤️  but keep in mind back to the note of mudae bot reacting the same as mudae that normal emojis like 🕯️ , 💞 , 💖 , ❤️ etc etc. do NOT have a reaction.emoji.name and to use them you actually have to copy and paste the actually emoji into the code  as shown in both examples making it kinda of frustrating to deal with

> ![image](https://user-images.githubusercontent.com/33008397/116167337-027aad00-a6ce-11eb-96ea-e45519b5d111.png)

2. I had a user use #.5 so to my knowledge it will work if it doesn't work it would throw an error
2a. so that would have to implement something with message history which I don't wanna get into really since it would have to know who rolled it and who has priority so my work around is similar to what I do with free kakeraP sniping.


> ![image](https://user-images.githubusercontent.com/33008397/116167609-8fbe0180-a6ce-11eb-8ee9-a8f7040dd294.png)

this way the 1st snipe gets applied which either works or doesn't them it removes the reaction , waits for the remaining delay and attempt the second snipe

I can add that to Wishlist'd characters atleast if you would like that option basically adding

> ![image](https://user-images.githubusercontent.com/33008397/116167749-e62b4000-a6ce-11eb-8de6-90a51e45a0d6.png)

`await asyncio.sleep(1)`
`await message.add_reaction(emoji)`
`await asyncio.sleep(1)`
`await message.remove_reaction(emoji,self.user)`

**Comment by DaMagicFox** [comment]
how or where would I implement your answer to 2.a?

**Comment by DaMagicFox** [comment]
About 1... 
I'm pretty sure it isn't, we don't have premium mudae yet it is adding the hearts and other reactions to the rolls.
How would I implement it?

**Comment by vivinano** [comment]
hmm i can implement it with a push atleast for the wished characters since they are immune to snipe protection in some servers
give me a few and ill push the code

and with 1:

> ![image](https://user-images.githubusercontent.com/33008397/116170016-f1349f00-a6d3-11eb-93a2-618ae0028d3e.png)

example of mudae not adding a reaction by default it based on time so it changes on the time played

**Comment by DaMagicFox** [comment]
I mean, i could personally add the "way the 1st snipe gets applied which either works or doesn't them it removes the reaction , waits for the remaining delay and attempt the second snipe" if you give me the where to put it and what to put.

I'm pretty sure you can in fact allow it without premium, with the downside of reducing the amount of rolls you can make. In the server I'm in it works anytime.

**Comment by vivinano** [comment]
I added the code already so it should be good 

with the emoji thing since it only your server and not in mine I can't really implement that function without having to probably fix it for others or if someone misses their wishlist because mudae didnt add a emoji on their server. I will look into it tho and see if its possible if i do need to implement it in the future tho

**Comment by DaMagicFox** [comment]
Ok, do i have to do something for the "way the 1st snipe gets applied which either works or doesn't them it removes the reaction , waits for the remaining delay and attempt the second snipe"?

I will check about the reactions, but i'm pretty sure it's not premium, I'll inform.

**Comment by DaMagicFox** [comment]
I just checked. "$togglereact 2" makes it so that every roll has a reaction by mudae at the cost of removing some rolls.

**Comment by vivinano** [comment]
yeah but again that very "Specific" to your server what if someone else's server doesn't use togglereact 2 because they dont like less rolls ? 

but anyway I've made change to the code and pushed it 

> ![image](https://user-images.githubusercontent.com/33008397/116184122-213c6c00-a6ed-11eb-9462-cd2bae502f64.png)

this update should allow the bot to 1st see if emoji is available after the delay and if not it defaults back to the use_emoji setting

**Comment by DaMagicFox** [comment]
I'll try the update and see if there's any problem. Again, I'm very grateful towards you for being so open to comments.

**Comment by DaMagicFox** [comment]
I tried the update. I can't check the wished characters thing, but the code to match mudae's reaction works.

Has the update that you mentioned about making a similar bypass to then one with KakeraP bypass, which was basically adding a "snipe gets applied which either works or doesn't them it removes the reaction , waits for the remaining delay and attempt the second snipe"? If it is implemented then it isn't working. If I am the one that has to implement it then tell me what to do.

**Comment by vivinano** [comment]
right now its only added to wished list characters and kakeraP other than that the others just make 1 attempt.
if you want it on ever other check you can just copy the code from the ones that have the method to the ones without

**Comment by DaMagicFox** [comment]
How would I do that?

**Comment by DaMagicFox** [comment]
by "wished list characters" you mean the ones in json file?

**Comment by vivinano** [comment]
No those are just characters you need 

"wished" is what I classify as if mudae says

"Wished by str({self.user.id})"

**Comment by DaMagicFox** [comment]
yeah, then I want the snipe thing for the characters in json

**Comment by vivinano** [comment]
you can copy the code from await and move it on the  other checks which are 

the series list check , name check and the kak value check 

currently just testing out if the method stated cause any issues so I personally didnt push that until i feel like its stable but if you want that method then copy and pasting would be the fix

**Comment by DaMagicFox** [comment]
await asyncio.sleep(1)
                print(f"Free Kakera was detected in {reaction.message.guild.name} : {reaction.message.channel.name} @ {reaction.message.created_at}")
                await reaction.message.add_reaction(reaction.emoji)
                await asyncio.sleep(1)
                await reaction.message.remove_reaction(reaction.emoji,self.user)
                await asyncio.sleep(kak_delay - 2)
                await reaction.message.add_reaction(reaction.emoji)

**Comment by DaMagicFox** [comment]
where do I copy that?

**Comment by vivinano** [comment]
the series list check , name check and the kak value check 

so basically every check that isnt the wish check

**Comment by DaMagicFox** [comment]
Could you add me on discord DaMagicFox#0001 so that I can send you the file and you tell me if it's good?

**Comment by vivinano** [comment]
just take screencaps for now and show me if we need to do more then we can proceed

**Comment by DaMagicFox** [comment]
sure

**Comment by DaMagicFox** [comment]
![c4cb8aa4b3abef19178d052694e3ebf4 (1)](https://user-images.githubusercontent.com/67620778/116330479-4388c500-a793-11eb-9dcc-0e55bdd45f16.jpg)

**Comment by DaMagicFox** [comment]
![Captura de pantalla 2021-04-27 200001](https://user-images.githubusercontent.com/67620778/116330531-57ccc200-a793-11eb-9347-eb8f9ad6f992.png)

**Comment by DaMagicFox** [comment]
That's what I did, and it's not working as intended. What did I do wrong? I'm looking to learn python btw, so any tips or reasons for why it broke can help.

**Comment by vivinano** [comment]
doesn't seem wrong did u get an error ? and i think i see the problem 

> ![image](https://user-images.githubusercontent.com/33008397/116332433-bc8e1980-a79f-11eb-99b1-d42f9ecd8317.png)


so since you are learning why do u think this is not working correctly here ???

**Comment by DaMagicFox** [comment]
The error I get is in the (emoji) section for line 130

**Comment by DaMagicFox** [comment]
I tried changing it to ❤️ (copy pasting the emoji) but it just started doing it on every roll

**Comment by vivinano** [comment]
yeah but there an issue with your logic there look at what different from this vs the others

**Comment by DaMagicFox** [comment]
![image](https://user-images.githubusercontent.com/67620778/116335796-0cb7ac80-a79d-11eb-8eae-bac0987e027c.png)

**Comment by DaMagicFox** [comment]
is it that?

**Comment by vivinano** [comment]
Yes that looks correct lol but do you understand what happened ? and why u had to do that

**Comment by DaMagicFox** [comment]
what I got is that the other ones were "if" and then, in the next line "print" and below that the rest of the code. The series list starts with a "for" and then "if", i just followed the if sequence the others had.

**Comment by vivinano** [comment]
basically your old code attempted to add a emoji that was never set X( count of things in your series list) number of times so it will do for example 5 times , remove emoji that was never added , and try to add another emoji that was never set 


the new code change does 
for X in List do 
    if X1 in "X1" then do 
        stuff
        if stuff = something then do
               other stuff
   if X2 in "X1" then do 
       stuff (False never runs)

**Comment by DaMagicFox** [comment]
I'm kinda understanding, but not much tbh

**Comment by vivinano** [comment]
So old one adds reaction 5 times 

The new one add 1 reaction if it meets the requirements of being in the list

**Comment by DaMagicFox** [comment]
Now the only other thing I don't fully understand is how the delay works for the snipe check thing

**Comment by vivinano** [comment]
Which ones ? the kakera one is a little bit more complex while the character sniping is more simple in terms of explaining

**Comment by vivinano** [comment]
closing issue for now

**Comment by DaMagicFox** [comment]
No, i mean, how do i customize the delay for the snipe thing I just added, like, which number does what

**Comment by vivinano** [comment]
anytime you see

asyncio.sleep(x) imagine telling the bot to wait x amount of secs

so u can set the delay there in the code if you want  and have it make more sense

**Comment by DaMagicFox** [comment]
asyncio.sleep(claim_delay - 3)

**Comment by DaMagicFox** [comment]
how does that one work?

**Comment by DaMagicFox** [comment]
is it the claim delay in json file - 3?

**Comment by DaMagicFox** [comment]
Big props for the quick support, I really appreciate it. For now, I don't see any issues with the bot, and will inform if anything. Again, I appreciate the hard work you're putting into this, and for being so tolerant.

**Comment by vivinano** [comment]
no problem at all

**Comment by marcobiso** [comment]
> > ![image](https://user-images.githubusercontent.com/33008397/116124105-db9e8580-a691-11eb-8d53-ac5f6421b420.png)
> 
> change `if message.author.id == mudae:` >>> `if message.author.id == mudae and message.channel.id in [111111,22222]:`
> 
> > ![image](https://user-images.githubusercontent.com/33008397/116124131-e527ed80-a691-11eb-9f6c-d07ecd8f841f.png)`
> 
> change `if user.id == mudae:` >>> `if user.id == mudae and reaction.message.channel.id in [111111,222222]:`
> 
> or change `[11111,22222]` to in `multiids` and use that variable
> those changes should get you what you want. Personally I don't see the need to add this as it just limits the bot function and adds more checks the more it scales.

sorry for the dumb question but I'm new to this, does this mean that if I want to allow the bot to claim ONLY in a specific channel, I need to substitute the "111111" with the channel ID?

**Comment by DaMagicFox** [comment]
> > > ![image](https://user-images.githubusercontent.com/33008397/116124105-db9e8580-a691-11eb-8d53-ac5f6421b420.png)
> > 
> > 
> > change `if message.author.id == mudae:` >>> `if message.author.id == mudae and message.channel.id in [111111,22222]:`
> > > ![image](https://user-images.githubusercontent.com/33008397/116124131-e527ed80-a691-11eb-9f6c-d07ecd8f841f.png)`
> > 
> > 
> > change `if user.id == mudae:` >>> `if user.id == mudae and reaction.message.channel.id in [111111,222222]:`
> > or change `[11111,22222]` to in `multiids` and use that variable
> > those changes should get you what you want. Personally I don't see the need to add this as it just limits the bot function and adds more checks the more it scales.
> 
> sorry for the dumb question but I'm new to this, does this mean that if I want to allow the bot to claim ONLY in a specific channel, I need to substitute the "111111" with the channel ID?

Yes, you change the "111111" to the channel ID (To get channel ID activate developer mode in advanced settings and then right click a channel) the number is just a reference number. if you want to add more just put another comma and no space and insert the other one.

**Comment by vivinano** [comment]
@Regi49 make a seperate issue next time and i can provide faster and better assistance 

and I guess since i see that more people are wanting limited scope i will just add the same code but with the limited scope changes and have 2 versions for future pushes

**Comment by Regi49** [comment]
alright, thanks for the replies

**Comment by DaMagicFox** [comment]
Is the bot not working? I haven't changed anything in the code and it just doesn't detect characters anymore.

**Comment by vivinano** [comment]
It might be a fault with mudae more than likely if it was originally working and been failing recently

**Comment by DaMagicFox** [comment]
> It might be a fault with mudae more than likely if it was originally working and been failing recently

Any ways I could fix it?

**Comment by vivinano** [comment]
Since it’s a problem with mudae and discord itself it’s falls outside of being able to fix 

Basically discord already thinks of mudae as a spam bot and has been blocking mudae from operating 

Someone else reported an issue with a failed snipe
After 4 successes there was 1 fail (reason unknown) and after was a success so currently not sure 
If you are able to isolate a reason I could implement a fix

**Comment by DaMagicFox** [comment]
> Since it’s a problem with mudae and discord itself it’s falls outside of being able to fix Basically discord already thinks of mudae as a spam bot and has been blocking mudae from operating Someone else reported an issue with a failed snipe After 4 successes there was 1 fail (reason unknown) and after was a success so currently not sure If you are able to isolate a reason I could implement a fix

Yeah I know, they had recently banned mudae's api, but I don't know why it would make sniping not work.

**Comment by vivinano** [comment]
Ultimately discord py is a wrapper of discord api so maybe changes from discord side mgiht have temporary caused message content not to be parsed correctly hence failing the check 

basically if discord is not giving the program input then there will be no output

but again unsure if the problem persist tho let me know what you think the probably cause is as this hasn't happened to me personally yet so I cant fix a possible "bug" that I have not found

**Comment by DaMagicFox** [comment]
> Ultimately discord py is a wrapper of discord api so maybe changes from discord side mgiht have temporary caused message content not to be parsed correctly hence failing the check
> 
> basically if discord is not giving the program input then there will be no output
> 
> but again unsure if the problem persist tho let me know what you think the probably cause is as this hasn't happened to me personally yet so I cant fix a possible "bug" that I have not found

Yeah it's probably a discord problem, it's weird that it hasn't happened to you, but I tried isolating the problem, (By using default settings, not using the snipe thing, not using the specific channels, and even having the default characters in json!) but I couldn't find anything. Although kakera seems to be working i think.
