### ISSUE TITLE
Question about how the bot will claim

### ISSUE THREAD

**Issue by pentuhhh** [vivinano/MudaeAutoBot#70]
If someone rolls and it meets the conditions for it to be claimed. But togglereact was turned off. will it use the emoji i set it to use and how do i know it will work. I currently set mine to :heart:

**Comment by vivinano** [comment]
So there are safety checks to be less bot like for example it will only claim after the the snipe protection if someone else hasn't already claimed it 

It also has a fallback emoji use for example at night mudae adds emoji on some rolls so it will use the that emoji 
Ex: mudae add emoji candle the bot will add emoji candle to claim 

And you can do a test by setting min_kak to like 10 so it will snipe anything to test out how it snipes

**Comment by pentuhhh** [comment]
Oh I see and Im also wondering if the formatting I used for the emoji was right. When I opened the settings json the default emoji was like :keqing: followed by numbers. I didn't know what It does but I completely replaced it to something easy like :heart:

Sent from Yahoo Mail on Android 
 
  On Fri, 9 Jul 2021 at 3:40 AM, Richard ***@***.***> wrote:   

So there are safety checks to be less bot like for example it will only claim after the the snipe protection if someone else hasn't already claimed it 

It also has a fallback emoji use for example at night mudae adds emoji on some rolls so it will use the that emoji 
Ex: mudae add emoji candle the bot will add emoji candle to claim 

And you can do a test by setting min_kak to like 10 so it will snipe anything to test out how it snipes

**Comment by vivinano** [comment]
so currently because custom emoji only work for one server it doesnt work at the moment but the bot will default add ❤️  so no worries it because you have to acutally use the emoji ❤️ within the code becasue json doesnt understand ❤️ but doesnt understand ":heart:"  in the code 

overall unless you want to change it from something other than heart I wouldnt worry about it 

you will see how it work when you get your 1st claim

**Comment by pentuhhh** [comment]
Alright I'll try to test it tomorrow

Sent from Yahoo Mail on Android 
 
  On Fri, 9 Jul 2021 at 3:57 AM, Richard ***@***.***> wrote:   


so currently because custom emoji only work for one server it doesnt work at the moment but the bot will default add ❤️ so no worries it because you have to acutally use the emoji ❤️ within the code becasue json doesnt understand ❤️ but doesnt understand " ❤️ " in the code

overall unless you want to change it from something other than heart I wouldnt worry about it

you will see how it work when you get your 1st claim

**Comment by vivinano** [comment]
assuming issue has been resolved and will be closing issue
