### ISSUE TITLE
Claiming

### ISSUE THREAD

**Issue by byronsanity** [vivinano/MudaeAutoBot#71]
The bot stops claiming after one claim. Is it really like this? Even after the reset, it ignores the other rolls unless the bot has been restarted.

**Comment by vivinano** [comment]
The bot has a claim window so upon a successful claim it will wait until the next claim window to claim again it to be less bot like cause if you already claimed within the hour why would u claim again right ?

**Comment by vivinano** [comment]
do you have multiple claims in one claim window ??? if there is im gonna have to rethink claim windows at that point do my knowledge is one per 3h for regualr , or one per 2h for server premium and 1 per 1h for server premim 2

**Comment by byronsanity** [comment]
No i dont hsve multiple claim. What I meant was once it has claimed, it does not claim again even after the reset. It just displays our user rolled

**Comment by byronsanity** [comment]
Lets say I claimed one hour before the claim reset. After the claim reset, it still ignores the rolls even after the reset even though the rolls match with the settings in the json file.

**Comment by vivinano** [comment]
`if waifu_wall.get(channelid,0) != next_claim(channelid)[0]:` 
so right above that line 
do `print(waifu_wall.get(channelid,0)` and `print(next_claim(channelid)[0]`

this will print some timestamps 

so basically if timestamp is == timestamp then no happen so it will print the timestamp of the timer 

any time those 2 values match up then no sniping will occur until next claim window

**Comment by vivinano** [comment]
Just checking in making sure things are doing okay ?

I will close the issue later today if I don't hear back
