### ISSUE TITLE
Instant Claim

### ISSUE THREAD

**Issue by Seiso1** [vivinano/MudaeAutoBot#74]
Your bot works perfectly but is there any way to instant claim characters? I had changed claim_delay value to 0.5 but there is someone still can claim before the bot claim. So what i need to change to claim faster than everyone but it won't get eaten by mudae when the mudae is slow sometimes.
I am very appreciate if you can help me

**Comment by vivinano** [comment]
In regards to instant snipe there is but it's usually calculated in case of snipe protection are u in a server that doesn't have snipe protection ?

**Comment by Seiso1** [comment]
yes, also this is the settings of the server 
![image](https://user-images.githubusercontent.com/87368882/125588111-cdade0d8-1ed9-4fd1-8542-c51844d5bd7f.png)

**Comment by vivinano** [comment]
In the 
Def snipe()

Function there is a small delay added that you can remove and it should just instant snipe the reason the delay is there is in cases where mudae says it’s no good and ignores the claim attempt 

But from there if it still to slow then it’s comes down to internet speeds and computer processing speeds which are factors that can’t be controlled easily

**Comment by Seiso1** [comment]
so i just need replace time.sleep(.5) to time.sleep(0) ?

**Comment by vivinano** [comment]
You could remove the entire line but yeah basically

**Comment by Seiso1** [comment]
ok thank you very much

**Comment by Tachayang** [comment]
i've optimized my setting to be as fast as possible but there's still a second delay between when the bot detects roll and claims any fix?
![image_2022-05-29_072315555](https://user-images.githubusercontent.com/106417747/170846874-b92a7d92-a5e3-421a-a791-ce885edc5eca.png)
![image_2022-05-29_072153612](https://user-images.githubusercontent.com/106417747/170846842-cc7ceab2-6e65-411c-9a50-f2ff96a11abb.png)
![image_2022-05-29_072222734](https://user-images.githubusercontent.com/106417747/170846851-48a57652-6a41-4566-8b5e-2a53c1b996ac.png)
