### ISSUE TITLE
The bot was working but suddenly stopped working

### ISSUE THREAD

**Issue by pentuhhh** [vivinano/MudaeAutoBot#75]
![asfasfafasfsafsafasfasf](https://user-images.githubusercontent.com/77160847/125614749-61fa93ac-4ed1-43ae-aa68-49bdfb41fe65.png)

So I have successfully started and used the mudae auto bot and suddenly it wont launch or work anymore. Tried reinstalling python and discum 1.3. Tried to launch but its just blank

**Comment by vivinano** [comment]
Your user token might have changed, it is technically a “static” thing but it will occasionally change 

You could try to turn discum logs to True

And it should tell you what happens if you can decipher the gateway logs

**Comment by pentuhhh** [comment]
Yep it's the user token that broke it. I thought it only changes only when I change password guess not. Thanks for the help again

Sent from Yahoo Mail on Android 
 
  On Thu, 15 Jul 2021 at 2:08 AM, Richard ***@***.***> wrote:   

Your user token might have changed, it is technically a “static” thing but it will occasionally change 

You could try to turn discum logs to True

And it should tell you what happens if you can decipher the gateway logs

**Comment by vivinano** [comment]
yeah user tokens usually expire not often but they do expire just need  to keep that in mind if something happens 
it usually logs it in discum logs so you can always see what happened and what to do to fix it 

but anyway remember to give this repo a star if you haven't already its keep me inspire to support this repo and its free so 

Thank you ^^
