### ISSUE TITLE
Hi I'm having this problem could someone help me?

### ISSUE THREAD

**Issue by gs566** [vivinano/MudaeAutoBot#77]
![image](https://user-images.githubusercontent.com/87499921/125852218-56225b8a-a168-442c-b2f6-9966b574c2e7.png)
I did everything right but I don't know what's going on

**Comment by vivinano** [comment]
Wrong version of discum please refer to discum repo 

https://github.com/Merubokkusu/Discord-S.C.U.M

**Comment by vivinano** [comment]
let me know if this has been resolved basically what is going on is your probably installed thru pypi and that version is on 1.1 

this application needs 1.3++ to run so just go to the repo linked above and they should lend a hand in getting you the most up to date version

**Comment by vivinano** [comment]
closing issue as havent recieved a response assumed issues has been resolved
