### ISSUE TITLE
Need some help setting this up... (Possible JSON error)

### ISSUE THREAD

**Issue by 75hrtz** [vivinano/MudaeAutoBot#79]
I tried using this the original way it was intended. I changed the settings to correspond with the server I am currently in and installed discum and even got it on Python as well. I tried running the main .Py file after doing those prerequisites but it would immediately close out. So I looked at the page and found you said to run it in IDLE mode. I did that and it continues to give me this error. Sorry for the inconvenience but can I get some help with this issue. 
![515](https://user-images.githubusercontent.com/87623325/126086019-06f5befc-8506-45e2-98e6-65214f2e42ff.PNG)

**Comment by vivinano** [comment]
On the read me there is a link for a Json validatior so copy the content of your json file into the text box and it will point out errors in ur json file

**Comment by 75hrtz** [comment]
Alright. So i did what you said and fixed it up but now its giving me this error
![1255](https://user-images.githubusercontent.com/87623325/126089147-5c528ea2-ab00-419c-8d5c-06e68baae316.PNG)

**Comment by 75hrtz** [comment]
Wait im sorry, turns out i had named it 'Channel_id' instead of 'Channel_ids' i changed it and its working properly now. Thank you very much for your super quick response and help!
