### ISSUE TITLE
Bot Error

### ISSUE THREAD

**Issue by Medxaka** [vivinano/MudaeAutoBot#80]
Hello I have a problem with the bot every time I try to put the id of a channel and I launch the bot it displays this and I do not know what to do
![Capture d’écran 2021-07-27 031919](https://user-images.githubusercontent.com/85975017/127079700-2c186470-e19f-4efe-b2b8-b48492e515d2.png)

**Comment by vivinano** [comment]
Can you check the file in the channeldata folder and see if it’s an empty .txt file if it is delete and retry to obtain one automatically or manually enter in the $settings of the channel into that .txt

**Comment by Medxaka** [comment]
> Can you check the file in the channeldata folder and see if it’s an empty .txt file if it is delete and retry to obtain one automatically or manually enter in the $settings of the channel into that .txt
> […](#)
> Sent from my iPhone
> On Jul 26, 2021, at 9:19 PM, Medxaka ***@***.***> wrote: ﻿ Hello I have a problem with the bot every time I try to put the id of a channel and I launch the bot it displays this and I do not know what to do — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you very much, I was able to solve the problem
