### ISSUE TITLE
About opening 2 bot at once

### ISSUE THREAD

**Issue by Seiso1** [vivinano/MudaeAutoBot#83]
Your bot work perfectly but I just want to ask can I open two bots at once ?

**Comment by vivinano** [comment]
you could but you would have to add random variable to the waifu_roll function 

#76 

basically multi bots rolling at the same time will cause Mudae on the server to lag so adding a delay for the bots allow them to function properly

**Comment by Seiso1** [comment]
> you could but you would have to add random variable to the waifu_roll function
could you help me to do this ?
> 
> #76
> 
> basically multi bots rolling at the same time will cause Mudae on the server to lag so adding a delay for the bots allow them to function properly

so I am using 2 accounts to roll in my private server, maybe it wont lag.

**Comment by vivinano** [comment]
basically `import random` and then on the last line of the waifu wait function you change the 
![image](https://user-images.githubusercontent.com/33008397/128378978-3053caa4-1993-47fe-9f4d-6ba7f419e221.png)

to something with a random value other than that I can't help as that would venture into giving custom code variations that I then also have to remember who I gave custom code to and why X isnt working which is more headache

**Comment by Seiso1** [comment]
oh thanks and btw when I rolled today, there was a problem.
I rolled this 
![image](https://user-images.githubusercontent.com/87368882/128594995-d8a9d429-c67d-43f2-a38a-b10e95bd5597.png)
but the bot didn't claim the waifu, idk why
![image](https://user-images.githubusercontent.com/87368882/128595026-6970e84c-7613-472e-a84a-bbc029b55373.png)
this is my settings
![image](https://user-images.githubusercontent.com/87368882/128595053-1cfb1673-f078-44fd-a87d-115179ae1a7d.png)

**Comment by Seiso1** [comment]
also i removed the kakera snipe function
![image](https://user-images.githubusercontent.com/87368882/128595130-5894e967-b527-4a22-8c74-ea56995484b6.png)

**Comment by vivinano** [comment]
The bot will still roll but will only claim if there is still a claim available. Did the bot already claim during this time ?

**Comment by vivinano** [comment]
yeah if you can confirm that the bot didnt successfully grab a different character as if it does then claim function cease until next timer

**Comment by Seiso1** [comment]
> The bot will still roll but will only claim if there is still a claim available. Did the bot already claim during this time ?
> […](#)
> Sent from my iPhone
> On Aug 7, 2021, at 5:06 AM, Seiso1 ***@***.***> wrote: ﻿ also i removed the kakera snipe function — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Seiso1** [comment]
> yeah if you can confirm that the bot didnt successfully grab a different character as if it does then claim function cease until next timer

it skipped 2 characters despite of their kakera values is above the min_kakera value

**Comment by vivinano** [comment]
Are you running 2 bots and they are rolling at the same time ?

**Comment by vivinano** [comment]
Trying to get more info atm and i havent got a reply

**Comment by Seiso1** [comment]
> Are you running 2 bots and they are rolling at the same time ?
> […](#)
> Sent from my iPhone
> On Aug 8, 2021, at 9:30 AM, Seiso1 ***@***.***> wrote: ﻿ yeah if you can confirm that the bot didnt successfully grab a different character as if it does then claim function cease until next timer it skipped 2 characters despite of their kakera values is above the min_kakera value — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

No, because i dont know how to do that so I only open a bot

**Comment by vivinano** [comment]
So this issue is happening with one bot ?

**Comment by Seiso1** [comment]
> So this issue is happening with one bot ?
> […](#)
> Sent from my iPhone
> On Aug 10, 2021, at 5:58 AM, Seiso1 ***@***.***> wrote: ﻿ Are you running 2 bots and they are rolling at the same time ? … Sent from my iPhone On Aug 8, 2021, at 9:30 AM, Seiso1 @.***> wrote: ﻿ yeah if you can confirm that the bot didnt successfully grab a different character as if it does then claim function cease until next timer it skipped 2 characters despite of their kakera values is above the min_kakera value — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. No, because i dont know how to do that so I only open a bot — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

yes, i dont know why its stop sniping characters

**Comment by vivinano** [comment]
After Reviewing the images I think this is still intended cause it seem like it was on your name list and wasnt a personal wished character depending on what sniping protection your server is on

so how it normally works is that wish priority goes to the wisher atleast in that case cause i dont see your name on their and that it only exist on namelist 

you could tell me other wise but

the bot will attempt to snipe only if a character has also not already been claimed by some1 else

example 

User Wishes character "Kiana" snipe protection of 8 
Bot sees the character will now wait 8 secs 
User claims character at 6 / 8 secs of timer
bot sees that "Kiana" has already been claimed alright it will pass because it has already been taken

**Comment by Seiso1** [comment]
> After Reviewing the images I think this is still intended cause it seem like it was on your name list and wasnt a personal wished character depending on what sniping protection your server is on
> 
> so how it normally works is that wish priority goes to the wisher atleast in that case cause i dont see your name on their and that it only exist on namelist
> 
> you could tell me other wise but
> 
> the bot will attempt to snipe only if a character has also not already been claimed by some1 else
> 
> example
> 
> User Wishes character "Kiana" snipe protection of 8
> Bot sees the character will now wait 8 secs
> User claims character at 6 / 8 secs of timer
> bot sees that "Kiana" has already been claimed after 8 (Snipe Protection) alright it will pass because it has already been taken

no, that character was wished by someone else but he wasn't there and someone try to snipe it
and the bot didn't attempt to snipe

**Comment by Seiso1** [comment]
maybe you should add the "turn on/off kakera snipe" function

**Comment by vivinano** [comment]
the fix for turning off kakera snipe is just taking the kakera off the list of kakera to snipe as adding a on / off function will just add another check it has to go thru which is technically not needed.

**Comment by Seiso1** [comment]
> the fix for turning off kakera snipe is just taking the kakera off the list of kakera to snipe as adding a on / off function will just add another check it has to go thru which is technically not needed.

but when I remove the kakera off its still claim the free kakera

**Comment by vivinano** [comment]
cause free kakera is hard coded in so u can change that one to like kakerax or something of the sort which will never be true

**Comment by Seiso1** [comment]
![image](https://user-images.githubusercontent.com/87368882/129172107-ecb677b5-b3f3-42ea-be2b-d81d3f51e664.png)
so I just change the kakeraP to kakeraX ?

**Comment by vivinano** [comment]
Yeah technically

**Comment by Seiso1** [comment]
thank you
