### ISSUE TITLE
Claim problem

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#84]
Hi, thanks for the great bot and all the patience in support.

I left the bot running 24 hours on a server and when I went to see it, I didn't get anything, because when the bot raged like this:

![image](https://user-images.githubusercontent.com/82736191/128125344-b8009392-1319-4f76-973c-1b7933ed3a4c.png)

The server is set to $togglereact 0, so the reaction only appears on characters that have wish.

Another problem I faced is the bot not starting when I delete the `# `of the lines indicated by you in this image
![image](https://user-images.githubusercontent.com/82736191/128125435-af777071-25dd-477b-a771-22d8f45bb231.png)
![image](https://user-images.githubusercontent.com/82736191/128125450-a6ead12e-f0c4-4139-aecf-bdae76ce5163.png)

**Comment by vivinano** [comment]
1) Not enough information don't know what this is even in context to

2) when removing the # you have to keep the correct spacing needed for python and it should work

**Comment by BellaDona007** [comment]
> 1. Not enough information don't know what this is even in context to

![image](https://user-images.githubusercontent.com/82736191/128128710-4a90f84c-67ba-4186-b664-bb7e21f6f019.png)
The bot adds a reaction, the correct thing would be to react to the existing reaction.
This happened several times

**Comment by vivinano** [comment]
1) 
![image](https://user-images.githubusercontent.com/33008397/128216098-0e2c487d-4481-48a1-998f-67132d15dcd4.png)
logic seems fine only thing i expect is that the snipe delay is low meaning it is not able to wait for correct mudae react. I already let you know that if the delay is 2 short thing like this would happen.



2)
![image](https://user-images.githubusercontent.com/33008397/128216585-4dc53ae2-a1cc-4e8f-8411-40ef533e18f3.png)
this whole section is where it detects choas keys so if there is a issue then find the problem and fix it as again `I can't Test Choas keys`

**Comment by BellaDona007** [comment]
> ![image](https://user-images.githubusercontent.com/33008397/128216098-0e2c487d-4481-48a1-998f-67132d15dcd4.png)
> logic seems fine only thing i expect is that the snipe delay is low meaning it is not able to wait for correct mudae react. I already let you know that if the delay is 2 short thing like this would happen.
> 
I even tried to increase 0.1, 0.2, 0.3 but the same problem occurred, I'm waiting for a wish to come, without having placed it in the `namelist`, I'll be back as soon as I get the result

> 
> ![image](https://user-images.githubusercontent.com/33008397/128216585-4dc53ae2-a1cc-4e8f-8411-40ef533e18f3.png)
> this whole section is where it detects choas keys so if there is a issue then find the problem and fix it as again `I can't Test Choas keys`

Unfortunately I don't understand anything about programming, even so, thanks for all the help in trying to implement this feature.

**Comment by vivinano** [comment]
1) well no1 else is reporting issue with it and i know based on previous issues you did shorten the snipe delay and also that sometime you have the longest delay in regards to rolling. so it might be tied to that issue also maybe do a reinstall

**Comment by BellaDona007** [comment]
> 1. well no1 else is reporting issue with it and i know based on previous issues you did shorten the snipe delay and also that sometime you have the longest delay in regards to rolling. so it might be tied to that issue also maybe do a reinstall

I've been using the default since the roll was fast, that is, I've been using stock for 1 month, the only thing that is dumb is this:
![image](https://user-images.githubusercontent.com/82736191/128222444-4bf6b522-fd4e-4492-a8ac-e4613f652905.png)

**Comment by vivinano** [comment]
Those values have been deprecated for a while and are only being used when no settings are found for default sniping mode

**Comment by BellaDona007** [comment]
> …

The only modification I made was this: 

![image](https://user-images.githubusercontent.com/82736191/128224660-8bff3440-93ec-4bf3-a8be-e0be6bd0c929.png)

**Comment by vivinano** [comment]
make sure any of the changes made dont effect any type of spacing

**Comment by vivinano** [comment]
haven't heard back. Will be closing issue
