### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by Leroys2019** [vivinano/MudaeAutoBot#86]
I'm kinda new to python so I'm sorry if any of these are dumb questions. So I think I've done the installations on python and Discord-S.C.U.M correctly. I made sure to add my discord id into the config and I made a test server to try to run the file. Whenever trying to run the 'MudaeAutoBot' with python it instantly closes. I ran the file through CMD and also IDLE and here is where I'm stuck in the setup process.
![image](https://user-images.githubusercontent.com/72043750/128403930-42c87f85-035b-43ef-8a3b-7d46de7449e6.png)
![image](https://user-images.githubusercontent.com/72043750/128405190-18e33e26-df90-499a-8c11-8b53080e3787.png)

Thank you for taking the time to help out.

**Comment by vivinano** [comment]
your json file is not properly formatted so copy paste your file into the json validator website

**Comment by Leroys2019** [comment]
I think i got it to work now thanks

**Comment by vivinano** [comment]
No problem just remember to give the repo a star to support the project :)
