### ISSUE TITLE
Bot no longer working

### ISSUE THREAD

**Issue by banana-vacuum** [vivinano/MudaeAutoBot#88]
Was working for a while, but when using a different accounts token, the console stays empty and refuses to do anything.
I have re-downloaded, and same result.

**Comment by vivinano** [comment]
Might be a discum issue I have to check but in the mean time try to contact them as code hasn't changed

**Comment by MegaMillf** [comment]
do you have discord by chance, to make things easier?

**Comment by vivinano** [comment]
I do but i keep discord as a personal thing and If I'm gonna be on call for support I rather get paid for that which is why I leave that behind patreon

**Comment by MegaMillf** [comment]
ah sorry about that bro, i dont have money with me rn, but if you find the issue please let me know

**Comment by vivinano** [comment]
No problem sorry about that this is a for fun project and I use my discord for work stuff as is and I would like to keep those interactions separate. 

But back to the issue at hand it's possibly a issue with discum and as I have my birthday coming up I will not be able to work on this issue until after your best bet would be to go to discum and make and issue there and see if there message module is functioning as intended

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/128800068-14edb703-1891-48a8-8a89-cf8171c4d9d8.png)

bot is still able to roll so I do not know the issue that is causing the issue for you

**Comment by MegaMillf** [comment]
Happy early birthday, sorry for causing trouble for you. 
i have created an issue at the discum rep, and am facing this issue after waiting about 30 min of a blank console screen.
https://github.com/Merubokkusu/Discord-S.C.U.M/issues/136

**Comment by MegaMillf** [comment]
![image](https://user-images.githubusercontent.com/88290308/128915046-feb577c3-0e7a-4c5f-ae19-0e111d651d64.png)

**Comment by vivinano** [comment]
seems like channel setting werent found

**Comment by MegaMillf** [comment]
channels are in the correct folder
![image](https://user-images.githubusercontent.com/88290308/128920278-4f7b5b76-5ceb-4dc9-b66c-8ecab016fc4c.png)

**Comment by vivinano** [comment]
Check the content of them and make sure they aren't empty

**Comment by MegaMillf** [comment]
they are not empty
![image](https://user-images.githubusercontent.com/88290308/128920840-37d521af-a9f4-4538-a7c4-521e8d637b99.png)
the first error was about "_heartbeat" now its about messages

**Comment by vivinano** [comment]
Really sounds like maybe your using a outdated version of discum 
The bot really relies on the ability to make discord interactions but unsure as the issue is not consistent enough for me to make interpretations the best bet is the wait for discum Dev to check it out

**Comment by MegaMillf** [comment]
ive just found a workaround, just using default channel file, and renaming it to the channel id of choice, seems to fix the issue, but the bot no longer creates the files by default. I still dont know why i got that "_heartbeat" error once though

**Comment by vivinano** [comment]
I will delete my file and see if it creates on

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/128949054-3033fb93-c98d-4703-83e3-8e7468a291e5.png)
 file still created successfully after delete

**Comment by MegaMillf** [comment]
The bot still cannot create the file for some reason, currently the bot is working, But the claim time doesnt work, it claims instantly instead of using the set claim time, any thoughts on that?

**Comment by vivinano** [comment]
I really don't think this is an issue with my the bot but on discum side I feel like you may have the wrong version of discum

**Comment by MegaMillf** [comment]
i have discum 1.3.1, i have unistalled, downgraded, upgraded, and still the issue persists.
Sorry for troubling you.

**Comment by banana-vacuum** [comment]
![image](https://user-images.githubusercontent.com/88290308/129063010-b23a0a75-a1e4-44c2-b358-b09d9152bd0f.png)

**Comment by vivinano** [comment]
that means that its not able to get a prefix so there was no $settings instance found so there wasnt a prefix to use

**Comment by banana-vacuum** [comment]
shouldnt the bot create a channeldata file with default settings? or do i have to say $settings once in the server?

**Comment by vivinano** [comment]
$settings once in the server but if no $settings are found it uses a default version which then searches for the commands to find if your using "$" or "?" just whatever the settings_prefix 

it only write channeldata if one is found

**Comment by banana-vacuum** [comment]
ok thanks for helping, the bot is working at this point, but i still cant fix the instant claiming.

**Comment by vivinano** [comment]
alright for now i will close then but claiming maybe related to the channeldata settings the snipe protection
