### ISSUE TITLE
Not claiming wished characters

### ISSUE THREAD

**Issue by banana-vacuum** [vivinano/MudaeAutoBot#89]
When a wished character is rolled, the bot does not claim, regardless of the "min_kak" limit.

**Comment by vivinano** [comment]
Wished characters will only be claimed If you name is in the message.content

Ex: wished by @me 

If not then it will not be seen as a possible snipe 

Anything thing is that due to specific snipe protections there might be a wait period and in that time if the character is already claimed it will be skipped by the bot , and also if you have already claimed once in the claim period then all rolled chars are ignored until next claim period

**Comment by banana-vacuum** [comment]
Would there be a way to detect a wished roll that isn't wished by the user? And is there a timer for claiming wished characters that the user has wished?

**Comment by vivinano** [comment]
In terms of self wished character it will attempt to claim them if no1 else has claimed them already. In terms of other users you would have to know each one of their User ID and add them to an array to check basically

**Comment by banana-vacuum** [comment]
Alright bro, you again have solved my issue. The only persisting one, is that the bot reacts after 1 second and is not changeable. I have tried many times but it still claims after 1 second, is there a workaround for this? Also all the channel settings are correct and sniping is on level 0, so there shouldn't be any issues with that.

**Comment by vivinano** [comment]
There is a small .5 sec delay added by default for time for mudae to process interactions but any other amount of time is based on factors out of control 

IE internet speeds , discord processing time

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/129855004-d6a4f3a3-1627-4bc8-91d3-ee90e7630184.png)

right there there is a small delay added feel free to take out that delay but it might be to fast for mudae to recognize interactions 
so speed isnt always the best but feel free to make changes as needed the claims for me were consistent enough with the small delay added

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/129855283-a114463b-1c53-47f6-9399-9b5bfeb7712d.png)

for your future reference if you want to edit how wishes work overall but that will be on you 

with that i will be closing this issue
