### ISSUE TITLE
More of a concern than an issue

### ISSUE THREAD

**Issue by Kaizuk-O** [vivinano/MudaeAutoBot#90]
![image](https://user-images.githubusercontent.com/89078343/129717850-89ee5721-5ef1-47cc-b54c-4c6c4d2869d5.png)

Recently the server has switched to Togglesnipe 2 with 1.5 second timer - the settings for the channel has been updated respectively as shown in the attached images.
![image](https://user-images.githubusercontent.com/89078343/129718078-2a00bce5-f293-4b89-a8cf-6947832dc031.png)

However, after every roll it will show valueError and a bunch of other messages relating to get_snipe_time and snipe_delay and things like that as shown in the first image.

As of right now, no wishes have dropped, and it still claims kakera as it should. 

Is there anything in those messages that should raise concern?

**Comment by Kaizuk-O** [comment]
Just an update, this is what it looks like when I roll myself: 
![image](https://user-images.githubusercontent.com/89078343/129719078-11d22d05-4501-4014-b645-9b869809883d.png)

The first three were me using the $mk command, the fourth was me using $ma

**Comment by Kaizuk-O** [comment]
Update: A wish of mine appeared and it was not able to claim or even attempted to claim

![image](https://user-images.githubusercontent.com/89078343/129725915-c748e565-0247-4e84-b1cb-675acb1b583b.png)

I wasn't there for this so I didn't see exactly what happened, but before the togglesnipe came into play this would've claimed no problem

**Comment by Kaizuk-O** [comment]
Update: the additional error type messages that show up after every roll seem to only coming up when I have claim - when I no longer have claim it shows someone else rolled in the channel as normal
![image](https://user-images.githubusercontent.com/89078343/129750889-8682a804-fda0-4c7a-b16e-509765c3dfc9.png)

The first few rolls at the start of the screenshot are when I don't have claim, the last one is **after** my claim time has reset.

When a wish shows up, the script isn't able to pick it up likely due to the message it shows when I do have claim.

Any advice?

**Comment by vivinano** [comment]
Basically the claim delay is getting to many variables and not getting proper settings let me test when I change mine to a value with a decimal it might be an easy fix we shall see another work around is to set ur 1.5 > 2 so that way it can still snipe

**Comment by Kaizuk-O** [comment]
Yep, I just tested it in a server with 3 sec delay instead of a number with a decimal number and it seems to be fine.

For a server using 2 sec, 3sec, 4sec. etc. delay; what would you say is the best claim delay to use in the Settings_mudae.json file to ensure it still claims as instantly as it can?

**Comment by vivinano** [comment]
alright I've push code changes the new revision to support decimal numbers in $settings if found

**Comment by vivinano** [comment]
2cff11b930cd742f9ca4b7a7e0e1bd3cd9a679db
