### ISSUE TITLE
Won't claim during first rolls of a reset

### ISSUE THREAD

**Issue by chriskiihne** [vivinano/MudaeAutoBot#91]
The bot appears to not claim during the first hour of a reset. The resets on my server happen at 12:28, 3:28, 6:28 and so on, ![Screenshot_20210819-092335.png](https://user-images.githubusercontent.com/46977523/130086503-8de14803-aa7a-4d13-b589-324edaf16e77.png) the bot claimed sekmet an hour before the reset as it should but then once the reset happened at 6:28 it did not claim Beatrice. ![Screenshot_20210819-092319.png](https://user-images.githubusercontent.com/46977523/130086597-25b938bc-edaf-482f-9206-a1e61d62acd5.png) I have double checked and Beatrice is in the name list in the settings. My only idea is that maybe since the bot rolls so soon after reset maybe the bot doesn't know the reset had happened and that it should be able to claim?

**Comment by vivinano** [comment]
So there is a guard code that stop is from sniping all the time after a successful claim and doesn’t reset until the next reset which is 6:28 what I think happened here is that it hit reset time but it still had a few seconds wait left and it was case of bad timing try to test a bit more or remove the safe guard code

**Comment by chriskiihne** [comment]
what could would I need to remove to get rid of the safe guard code?

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/130101170-b3457f59-18a3-466a-8ba4-2a6f1fa492f8.png)

i think that whole chunk of code not to sure as I havent really changed this section for a while. I think maybe pushing the roll wait back 1 min maybe would fix this possibility for the future

![image](https://user-images.githubusercontent.com/33008397/130101791-a6e4f77f-2cbb-48e4-91f4-88b135d64f0e.png)

**Comment by chriskiihne** [comment]
ok, looking at the
`time.sleep(next_reset(tide)-time.time())+1)` 
code to push back the roll wait back 1 minute would I just make the 1 into 61 since time.sleep uses seconds as its parameter? Sorry not the best at programming, especially in python as I have no experience with it

**Comment by vivinano** [comment]
Yeah that sounds correct u can test it out and see how it goes

**Comment by vivinano** [comment]
closing as no reply has been received in several days
