### ISSUE TITLE
"No such file or directory: 'Settings_Mudae.json" Error

### ISSUE THREAD

**Issue by GiornoGiobama** [vivinano/MudaeAutoBot#92]
It says this but the json file is right htere
![hmmm](https://user-images.githubusercontent.com/76965733/130087195-e22fb12b-240f-41fb-8fe7-1cb2f401a0d7.PNG)

**Comment by vivinano** [comment]
Need a picture of the file structure of the folder

**Comment by GiornoGiobama** [comment]
![Here](https://user-images.githubusercontent.com/76965733/130097018-a21b2528-9efc-422f-951e-2fb5461b322b.PNG)
Here it is

**Comment by vivinano** [comment]
Those files looks like their still compressed did you unzip them at any point ?

**Comment by GiornoGiobama** [comment]
those are unzipped yes

**Comment by vivinano** [comment]
well I see the blue compression icons on the top right of the files is why I ask.

**Comment by GiornoGiobama** [comment]
I used 7zip and the extract option to extract them

**Comment by vivinano** [comment]
https://www.thewindowsclub.com/small-blue-arrow-overlays-desktop-icons#:~:text=What%20are%20these%202%20small,which%20appear%20on%20desktop%20icons%3F&text=If%20you%20have%20noticed%20an,compressed%20to%20save%20disk%20space.

**Comment by vivinano** [comment]
i found that thing saying window OS has compressed

**Comment by GiornoGiobama** [comment]
I decompressed them
didnt fix the issue

**Comment by vivinano** [comment]
Windows correct ?

**Comment by GiornoGiobama** [comment]
yep it is windows, and I'm launching it by CMD (sorry for the late response)

**Comment by vivinano** [comment]
https://stackoverflow.com/questions/24722212/python-cant-find-module-in-the-same-folder

maybe this will help ?

**Comment by vivinano** [comment]
it honestly would probably be better to search up and answer on google. As this issue falls more on python environment issues which varies on the user itself

**Comment by GiornoGiobama** [comment]
Alright, I'll do just that

**Comment by vivinano** [comment]
Yeah sorry about that last time I dealt with a python environment issue it took like 300+ Replies and I want to avoid doing that again as it takes lot of time if you still need help after all of that then I will make an attempt to look into it but no promises
