### ISSUE TITLE
Incomplete Rolls

### ISSUE THREAD

**Issue by FiveFiveTwo** [vivinano/MudaeAutoBot#95]
Hi, so I've been testing your bot (2.0v3) on a private server with only me in it. 
I let it run for 24 hours:
In those 24 hours it only fully completed all of my available rolls 9 times. 
So for 15 roll intervals, it was always short by exactly 1 roll. 
![Missed One Roll - Copy](https://user-images.githubusercontent.com/89508407/130896289-e22834dc-2475-48b9-b1de-4b91d09e4efe.jpg)
I have 36 rolls on this server, but during those times it only does 35.
![missing1 - Copy](https://user-images.githubusercontent.com/89508407/130896848-5f53d914-93dd-4508-9b36-237e2d55fe1d.jpg)

I checked the closed Issues and saw that there was another user who reported the same problem, but he never responded if he resolved it or not.

Here are my settings if that is helpful. These are the only things I have changed. I have not modified the main bot code itself:
![ServerSettingsIssue1 - Copy](https://user-images.githubusercontent.com/89508407/130897430-4579a193-e2b7-42f1-a954-8290b6751dba.jpg)
![JsonSettingsIssue1 - Copy](https://user-images.githubusercontent.com/89508407/130897442-d6ab9102-a3d8-4065-8481-bf4c281525c1.jpg)

If this is an issue on my end, is there perhaps a way to just add +1 extra roll at the end? Overrolling by 1 is common behavior on the servers I play in, but missing 1 roll is not, if that makes sense.

**Comment by vivinano** [comment]
didnt hear response will be closing
