### ISSUE TITLE
Bot won't work when I try to run the py. file

### ISSUE THREAD

**Issue by Kolopoto** [vivinano/MudaeAutoBot#96]
Pretty new to python and discum so not sure what I did wrong but whenever I tried to launch the MudaeAutoBot.py I get a blank cmd prompt and when I try to run it on Python IDLE nothing happens.
![AUTOERROR2](https://user-images.githubusercontent.com/90133606/132135200-53871bdc-0d1f-46c7-89aa-0fb16ef62bec.png)

**Comment by vivinano** [comment]
What was the issue ? Exactly

**Comment by Kolopoto** [comment]
Nothing was happening on IDLE because I put the User ID instead of the token in the JSON file didn't know those two things were different.
