### ISSUE TITLE
Slow claim when a wish appear, even if i got it in the JSON

### ISSUE THREAD

**Issue by xd-mau5** [vivinano/MudaeAutoBot#98]
I put a wish in my settings but when they appear the bot have a second or sometimes more delay to claim it, even if is my wish and i got it in the settings.
![image](https://user-images.githubusercontent.com/73971855/132249260-f1cccc17-344c-413e-9eb8-91c96c5e24ac.png)
![image](https://user-images.githubusercontent.com/73971855/132249277-a20111b9-be29-4a63-9d39-943a9e34e4a1.png)
I lost this wish to someone.
![image](https://user-images.githubusercontent.com/73971855/132249416-ebd7c1b9-e770-4218-8cc9-9f747ba60f14.png)

**Comment by vivinano** [comment]
what is the claim sniping setting on your channel ? the bot tries to figure out the most optimal time to snipe the character

**Comment by xd-mau5** [comment]
` Rolls sniping: **4** ($togglesnipe) => **8** sec.`
```
 "claim_delay":0,
   "kak_delay":0,
```

**Comment by vivinano** [comment]
so the bot was able to add the reaction tho correct ? as it should have attempted to snipe when it saw your name on the message.content 

there is a .5 flat delay added to snipes just to ensure that mudae fully recognizes a character is rolled and is able to be sniped.

any other types of delay is from connection speed to the discord api.

as for the few seconds the 1 sec via the `name list` it has to process all the names 1 by 1 til it get to "Ichinose" which is at the bottom of your list

**Comment by xd-mau5** [comment]
>so the bot was able to add the reaction tho correct ? as it should have attempted to snipe when it saw your name on the message.content

It was slow, even i was watching the rolls i can react faster to claim it

>there is a .5 flat delay added to snipes just to ensure that mudae fully recognizes a character is rolled and is able to be sniped.

There is a way i can modify this?

>as for the few seconds the 1 sec via the name list it has to process all the names 1 by 1 til it get to "Ichinose" which is at the bottom of your list
i wanna ask if the bot detects my wishes automatically or if he reads firts the JSON.

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/132252621-a7f14592-812d-4cd2-aab4-2dac012419ff.png)

the time.sleep(.5) can be modified to your liking



![image](https://user-images.githubusercontent.com/33008397/132252685-7d10927f-688a-4a3b-9de4-8d0c738266c6.png)
![image](https://user-images.githubusercontent.com/33008397/132252705-7eddeabf-b559-4c14-a195-ab429b7147b8.png)

Anything on your wishlist that shows your name on it will be wished on and based on your screen it was able to find it

also based on timestamps alone. the bot found the wish character @11:13 and 55 seconds and an attempt was made so threortically the attempt was sent thru the discord api at `11:13:55.5` anything else is connection based as I do not control the interaction with the API that will be a thing to take up with the Developer Discum


`they do have a Developmental Version which I was told was faster if you would like to upgrade to that version`

**Comment by vivinano** [comment]
ive added a log report function so it should tell you relative time that it snipe x character so you can use it as a reference for how long before a reaction is added
