### ISSUE TITLE
how i roll only one channel

### ISSUE THREAD

**Issue by TFPume** [vivinano/MudaeAutoBot#99]
https://prnt.sc/1ri0wqc

my server has 2 channel to rotate, but i only want to rotate in 2. how do i do this?

i don't know anything about python

**Comment by vivinano** [comment]
It seems like only one of them are for rolls so I think you only need to add one of them

**Comment by vivinano** [comment]
well if its channel instance there might be a small issue as ive only set this up for 1 server 1 channel unless both channels have the same setting this might cause issues

**Comment by TFPume** [comment]
i can't sniper both channel ?

**Comment by vivinano** [comment]
You can but you might have to manually set the $settings for each channel

**Comment by TFPume** [comment]
ok thanks
